// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zlmj/zlmj.proto

package zlmj

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type State int32

const (
	State_initing     State = 0
	State_cheating    State = 1
	State_can_discard State = 2
	State_over        State = 3
)

var State_name = map[int32]string{
	0: "initing",
	1: "cheating",
	2: "can_discard",
	3: "over",
}

var State_value = map[string]int32{
	"initing":     0,
	"cheating":    1,
	"can_discard": 2,
	"over":        3,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{0}
}

// 操作码
type ActionId int32

const (
	ActionId_pass            ActionId = 0
	ActionId_chi             ActionId = 1
	ActionId_peng            ActionId = 2
	ActionId_gang            ActionId = 3
	ActionId_an_gang         ActionId = 4
	ActionId_guolu_gang      ActionId = 5
	ActionId_ting            ActionId = 6
	ActionId_yao_gang        ActionId = 7
	ActionId_jiu_gang        ActionId = 8
	ActionId_bu_yao_gang     ActionId = 9
	ActionId_bu_jiu_gang     ActionId = 10
	ActionId_an_xi_gang      ActionId = 11
	ActionId_ming_xi_gang    ActionId = 12
	ActionId_bu_an_xi_gang   ActionId = 13
	ActionId_bu_ming_xi_gang ActionId = 14
)

var ActionId_name = map[int32]string{
	0:  "pass",
	1:  "chi",
	2:  "peng",
	3:  "gang",
	4:  "an_gang",
	5:  "guolu_gang",
	6:  "ting",
	7:  "yao_gang",
	8:  "jiu_gang",
	9:  "bu_yao_gang",
	10: "bu_jiu_gang",
	11: "an_xi_gang",
	12: "ming_xi_gang",
	13: "bu_an_xi_gang",
	14: "bu_ming_xi_gang",
}

var ActionId_value = map[string]int32{
	"pass":            0,
	"chi":             1,
	"peng":            2,
	"gang":            3,
	"an_gang":         4,
	"guolu_gang":      5,
	"ting":            6,
	"yao_gang":        7,
	"jiu_gang":        8,
	"bu_yao_gang":     9,
	"bu_jiu_gang":     10,
	"an_xi_gang":      11,
	"ming_xi_gang":    12,
	"bu_an_xi_gang":   13,
	"bu_ming_xi_gang": 14,
}

func (x ActionId) String() string {
	return proto.EnumName(ActionId_name, int32(x))
}

func (ActionId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{1}
}

// 组合码
type CombinationId int32

const (
	CombinationId_c_pass         CombinationId = 0
	CombinationId_c_chi          CombinationId = 1
	CombinationId_c_peng         CombinationId = 2
	CombinationId_c_gang         CombinationId = 3
	CombinationId_c_an_gang      CombinationId = 4
	CombinationId_c_yao_gang     CombinationId = 5
	CombinationId_c_jiu_gang     CombinationId = 6
	CombinationId_c_an_xi_gang   CombinationId = 7
	CombinationId_c_ming_xi_gang CombinationId = 8
)

var CombinationId_name = map[int32]string{
	0: "c_pass",
	1: "c_chi",
	2: "c_peng",
	3: "c_gang",
	4: "c_an_gang",
	5: "c_yao_gang",
	6: "c_jiu_gang",
	7: "c_an_xi_gang",
	8: "c_ming_xi_gang",
}

var CombinationId_value = map[string]int32{
	"c_pass":         0,
	"c_chi":          1,
	"c_peng":         2,
	"c_gang":         3,
	"c_an_gang":      4,
	"c_yao_gang":     5,
	"c_jiu_gang":     6,
	"c_an_xi_gang":   7,
	"c_ming_xi_gang": 8,
}

func (x CombinationId) String() string {
	return proto.EnumName(CombinationId_name, int32(x))
}

func (CombinationId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{2}
}

// 游戏选项
type Option struct {
	Cheat                bool     `protobuf:"varint,1,opt,name=cheat,proto3" json:"cheat,omitempty"`
	XiDingXi             bool     `protobuf:"varint,2,opt,name=xiDingXi,proto3" json:"xiDingXi,omitempty"`
	YaoJiuGang           bool     `protobuf:"varint,3,opt,name=yaoJiuGang,proto3" json:"yaoJiuGang,omitempty"`
	YaoJiuJiaFan         bool     `protobuf:"varint,4,opt,name=yaoJiuJiaFan,proto3" json:"yaoJiuJiaFan,omitempty"`
	QiangTing            bool     `protobuf:"varint,5,opt,name=qiangTing,proto3" json:"qiangTing,omitempty"`
	GuaDaFeng            bool     `protobuf:"varint,6,opt,name=guaDaFeng,proto3" json:"guaDaFeng,omitempty"`
	XiaDaYu              bool     `protobuf:"varint,7,opt,name=xiaDaYu,proto3" json:"xiaDaYu,omitempty"`
	KuaiBao              bool     `protobuf:"varint,8,opt,name=kuaiBao,proto3" json:"kuaiBao,omitempty"`
	BaoGang              bool     `protobuf:"varint,9,opt,name=baoGang,proto3" json:"baoGang,omitempty"`
	QiDui                bool     `protobuf:"varint,10,opt,name=qiDui,proto3" json:"qiDui,omitempty"`
	BeiKaoBei            bool     `protobuf:"varint,11,opt,name=beiKaoBei,proto3" json:"beiKaoBei,omitempty"`
	XiBuGuaFeng          bool     `protobuf:"varint,12,opt,name=xiBuGuaFeng,proto3" json:"xiBuGuaFeng,omitempty"`
	NoChiCha             bool     `protobuf:"varint,13,opt,name=noChiCha,proto3" json:"noChiCha,omitempty"`
	DianPaoFirst         bool     `protobuf:"varint,14,opt,name=dianPaoFirst,proto3" json:"dianPaoFirst,omitempty"`
	Ming5An10            bool     `protobuf:"varint,15,opt,name=ming5an10,proto3" json:"ming5an10,omitempty"`
	XiaoFan              bool     `protobuf:"varint,16,opt,name=xiaoFan,proto3" json:"xiaoFan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{0}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetCheat() bool {
	if m != nil {
		return m.Cheat
	}
	return false
}

func (m *Option) GetXiDingXi() bool {
	if m != nil {
		return m.XiDingXi
	}
	return false
}

func (m *Option) GetYaoJiuGang() bool {
	if m != nil {
		return m.YaoJiuGang
	}
	return false
}

func (m *Option) GetYaoJiuJiaFan() bool {
	if m != nil {
		return m.YaoJiuJiaFan
	}
	return false
}

func (m *Option) GetQiangTing() bool {
	if m != nil {
		return m.QiangTing
	}
	return false
}

func (m *Option) GetGuaDaFeng() bool {
	if m != nil {
		return m.GuaDaFeng
	}
	return false
}

func (m *Option) GetXiaDaYu() bool {
	if m != nil {
		return m.XiaDaYu
	}
	return false
}

func (m *Option) GetKuaiBao() bool {
	if m != nil {
		return m.KuaiBao
	}
	return false
}

func (m *Option) GetBaoGang() bool {
	if m != nil {
		return m.BaoGang
	}
	return false
}

func (m *Option) GetQiDui() bool {
	if m != nil {
		return m.QiDui
	}
	return false
}

func (m *Option) GetBeiKaoBei() bool {
	if m != nil {
		return m.BeiKaoBei
	}
	return false
}

func (m *Option) GetXiBuGuaFeng() bool {
	if m != nil {
		return m.XiBuGuaFeng
	}
	return false
}

func (m *Option) GetNoChiCha() bool {
	if m != nil {
		return m.NoChiCha
	}
	return false
}

func (m *Option) GetDianPaoFirst() bool {
	if m != nil {
		return m.DianPaoFirst
	}
	return false
}

func (m *Option) GetMing5An10() bool {
	if m != nil {
		return m.Ming5An10
	}
	return false
}

func (m *Option) GetXiaoFan() bool {
	if m != nil {
		return m.XiaoFan
	}
	return false
}

// 游戏数据结构
type GameData struct {
	State                State         `protobuf:"varint,1,opt,name=state,proto3,enum=zlmj.State" json:"state,omitempty"`
	Option               *Option       `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	Players              []*PlayerData `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	BackCardCount        int32         `protobuf:"varint,4,opt,name=backCardCount,proto3" json:"backCardCount,omitempty"`
	Cards                []int32       `protobuf:"varint,5,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	LastDisCard          int32         `protobuf:"varint,6,opt,name=lastDisCard,proto3" json:"lastDisCard,omitempty"`
	CurDiscardIndex      int32         `protobuf:"varint,7,opt,name=curDiscardIndex,proto3" json:"curDiscardIndex,omitempty"`
	LastDiscardIndex     int32         `protobuf:"varint,8,opt,name=lastDiscardIndex,proto3" json:"lastDiscardIndex,omitempty"`
	CardCount            int32         `protobuf:"varint,9,opt,name=cardCount,proto3" json:"cardCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameData) Reset()         { *m = GameData{} }
func (m *GameData) String() string { return proto.CompactTextString(m) }
func (*GameData) ProtoMessage()    {}
func (*GameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{1}
}

func (m *GameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameData.Unmarshal(m, b)
}
func (m *GameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameData.Marshal(b, m, deterministic)
}
func (m *GameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameData.Merge(m, src)
}
func (m *GameData) XXX_Size() int {
	return xxx_messageInfo_GameData.Size(m)
}
func (m *GameData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameData.DiscardUnknown(m)
}

var xxx_messageInfo_GameData proto.InternalMessageInfo

func (m *GameData) GetState() State {
	if m != nil {
		return m.State
	}
	return State_initing
}

func (m *GameData) GetOption() *Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *GameData) GetPlayers() []*PlayerData {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameData) GetBackCardCount() int32 {
	if m != nil {
		return m.BackCardCount
	}
	return 0
}

func (m *GameData) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *GameData) GetLastDisCard() int32 {
	if m != nil {
		return m.LastDisCard
	}
	return 0
}

func (m *GameData) GetCurDiscardIndex() int32 {
	if m != nil {
		return m.CurDiscardIndex
	}
	return 0
}

func (m *GameData) GetLastDiscardIndex() int32 {
	if m != nil {
		return m.LastDiscardIndex
	}
	return 0
}

func (m *GameData) GetCardCount() int32 {
	if m != nil {
		return m.CardCount
	}
	return 0
}

// 玩家数据结构
type PlayerData struct {
	UserId               int32     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Index                int32     `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	HoldsCount           int32     `protobuf:"varint,3,opt,name=holdsCount,proto3" json:"holdsCount,omitempty"`
	Holds                []int32   `protobuf:"varint,4,rep,packed,name=holds,proto3" json:"holds,omitempty"`
	Folds                []int32   `protobuf:"varint,5,rep,packed,name=folds,proto3" json:"folds,omitempty"`
	CanChupai            bool      `protobuf:"varint,6,opt,name=canChupai,proto3" json:"canChupai,omitempty"`
	Score                int32     `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	TotalScore           int32     `protobuf:"varint,8,opt,name=totalScore,proto3" json:"totalScore,omitempty"`
	IsMaster             bool      `protobuf:"varint,9,opt,name=isMaster,proto3" json:"isMaster,omitempty"`
	CurCard              int32     `protobuf:"varint,10,opt,name=curCard,proto3" json:"curCard,omitempty"`
	DisableCards         []int32   `protobuf:"varint,11,rep,packed,name=disableCards,proto3" json:"disableCards,omitempty"`
	IsReportTing         bool      `protobuf:"varint,12,opt,name=isReportTing,proto3" json:"isReportTing,omitempty"`
	Actions              []*Action `protobuf:"bytes,13,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{2}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PlayerData) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PlayerData) GetHoldsCount() int32 {
	if m != nil {
		return m.HoldsCount
	}
	return 0
}

func (m *PlayerData) GetHolds() []int32 {
	if m != nil {
		return m.Holds
	}
	return nil
}

func (m *PlayerData) GetFolds() []int32 {
	if m != nil {
		return m.Folds
	}
	return nil
}

func (m *PlayerData) GetCanChupai() bool {
	if m != nil {
		return m.CanChupai
	}
	return false
}

func (m *PlayerData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *PlayerData) GetTotalScore() int32 {
	if m != nil {
		return m.TotalScore
	}
	return 0
}

func (m *PlayerData) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *PlayerData) GetCurCard() int32 {
	if m != nil {
		return m.CurCard
	}
	return 0
}

func (m *PlayerData) GetDisableCards() []int32 {
	if m != nil {
		return m.DisableCards
	}
	return nil
}

func (m *PlayerData) GetIsReportTing() bool {
	if m != nil {
		return m.IsReportTing
	}
	return false
}

func (m *PlayerData) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

// 玩家操作
type Action struct {
	ActionId             ActionId `protobuf:"varint,1,opt,name=actionId,proto3,enum=zlmj.ActionId" json:"actionId,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	From                 int32    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Card                 int32    `protobuf:"varint,4,opt,name=card,proto3" json:"card,omitempty"`
	Cards                []int32  `protobuf:"varint,5,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionId() ActionId {
	if m != nil {
		return m.ActionId
	}
	return ActionId_pass
}

func (m *Action) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Action) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Action) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *Action) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 组合
type Combination struct {
	CombinationId        CombinationId `protobuf:"varint,1,opt,name=combinationId,proto3,enum=zlmj.CombinationId" json:"combinationId,omitempty"`
	From                 int32         `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Card                 int32         `protobuf:"varint,3,opt,name=card,proto3" json:"card,omitempty"`
	Cards                []int32       `protobuf:"varint,4,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Combination) Reset()         { *m = Combination{} }
func (m *Combination) String() string { return proto.CompactTextString(m) }
func (*Combination) ProtoMessage()    {}
func (*Combination) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{4}
}

func (m *Combination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Combination.Unmarshal(m, b)
}
func (m *Combination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Combination.Marshal(b, m, deterministic)
}
func (m *Combination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Combination.Merge(m, src)
}
func (m *Combination) XXX_Size() int {
	return xxx_messageInfo_Combination.Size(m)
}
func (m *Combination) XXX_DiscardUnknown() {
	xxx_messageInfo_Combination.DiscardUnknown(m)
}

var xxx_messageInfo_Combination proto.InternalMessageInfo

func (m *Combination) GetCombinationId() CombinationId {
	if m != nil {
		return m.CombinationId
	}
	return CombinationId_c_pass
}

func (m *Combination) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Combination) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *Combination) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Req struct {
	// Types that are valid to be assigned to Req:
	//	*Req_DiscardsReq
	//	*Req_WantHoldsReq
	//	*Req_DoActionReq
	//	*Req_PassReq
	Req                  isReq_Req `protobuf_oneof:"req"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{5}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

type isReq_Req interface {
	isReq_Req()
}

type Req_DiscardsReq struct {
	DiscardsReq *DiscardsReq `protobuf:"bytes,1,opt,name=discardsReq,proto3,oneof"`
}

type Req_WantHoldsReq struct {
	WantHoldsReq *WantHoldsReq `protobuf:"bytes,2,opt,name=wantHoldsReq,proto3,oneof"`
}

type Req_DoActionReq struct {
	DoActionReq *DoActionReq `protobuf:"bytes,3,opt,name=doActionReq,proto3,oneof"`
}

type Req_PassReq struct {
	PassReq *PassReq `protobuf:"bytes,4,opt,name=passReq,proto3,oneof"`
}

func (*Req_DiscardsReq) isReq_Req() {}

func (*Req_WantHoldsReq) isReq_Req() {}

func (*Req_DoActionReq) isReq_Req() {}

func (*Req_PassReq) isReq_Req() {}

func (m *Req) GetReq() isReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *Req) GetDiscardsReq() *DiscardsReq {
	if x, ok := m.GetReq().(*Req_DiscardsReq); ok {
		return x.DiscardsReq
	}
	return nil
}

func (m *Req) GetWantHoldsReq() *WantHoldsReq {
	if x, ok := m.GetReq().(*Req_WantHoldsReq); ok {
		return x.WantHoldsReq
	}
	return nil
}

func (m *Req) GetDoActionReq() *DoActionReq {
	if x, ok := m.GetReq().(*Req_DoActionReq); ok {
		return x.DoActionReq
	}
	return nil
}

func (m *Req) GetPassReq() *PassReq {
	if x, ok := m.GetReq().(*Req_PassReq); ok {
		return x.PassReq
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Req) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Req_DiscardsReq)(nil),
		(*Req_WantHoldsReq)(nil),
		(*Req_DoActionReq)(nil),
		(*Req_PassReq)(nil),
	}
}

type Rsp struct {
	// Types that are valid to be assigned to Rsp:
	//	*Rsp_ErrorRsp
	//	*Rsp_DiscardsRsp
	Rsp                  isRsp_Rsp `protobuf_oneof:"rsp"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Rsp) Reset()         { *m = Rsp{} }
func (m *Rsp) String() string { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()    {}
func (*Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{6}
}

func (m *Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsp.Unmarshal(m, b)
}
func (m *Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsp.Marshal(b, m, deterministic)
}
func (m *Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsp.Merge(m, src)
}
func (m *Rsp) XXX_Size() int {
	return xxx_messageInfo_Rsp.Size(m)
}
func (m *Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Rsp proto.InternalMessageInfo

type isRsp_Rsp interface {
	isRsp_Rsp()
}

type Rsp_ErrorRsp struct {
	ErrorRsp *ErrorRsp `protobuf:"bytes,1,opt,name=errorRsp,proto3,oneof"`
}

type Rsp_DiscardsRsp struct {
	DiscardsRsp *DiscardsRsp `protobuf:"bytes,2,opt,name=discardsRsp,proto3,oneof"`
}

func (*Rsp_ErrorRsp) isRsp_Rsp() {}

func (*Rsp_DiscardsRsp) isRsp_Rsp() {}

func (m *Rsp) GetRsp() isRsp_Rsp {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func (m *Rsp) GetErrorRsp() *ErrorRsp {
	if x, ok := m.GetRsp().(*Rsp_ErrorRsp); ok {
		return x.ErrorRsp
	}
	return nil
}

func (m *Rsp) GetDiscardsRsp() *DiscardsRsp {
	if x, ok := m.GetRsp().(*Rsp_DiscardsRsp); ok {
		return x.DiscardsRsp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Rsp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Rsp_ErrorRsp)(nil),
		(*Rsp_DiscardsRsp)(nil),
	}
}

type Event struct {
	// Types that are valid to be assigned to Event:
	//	*Event_DiscardsEvent
	//	*Event_GameStartEvent
	//	*Event_DealCardsEvent
	//	*Event_ResumeEvent
	//	*Event_DrawCardEvent
	//	*Event_NewActionEvent
	//	*Event_RemoveActionEvent
	//	*Event_DispatchActionEvent
	//	*Event_ChangeBaoCardEvent
	Event                isEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{7}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Event interface {
	isEvent_Event()
}

type Event_DiscardsEvent struct {
	DiscardsEvent *DiscardsEvent `protobuf:"bytes,1,opt,name=discardsEvent,proto3,oneof"`
}

type Event_GameStartEvent struct {
	GameStartEvent *GameStartEvent `protobuf:"bytes,2,opt,name=gameStartEvent,proto3,oneof"`
}

type Event_DealCardsEvent struct {
	DealCardsEvent *DealCardsEvent `protobuf:"bytes,3,opt,name=dealCardsEvent,proto3,oneof"`
}

type Event_ResumeEvent struct {
	ResumeEvent *ResumeEvent `protobuf:"bytes,4,opt,name=resumeEvent,proto3,oneof"`
}

type Event_DrawCardEvent struct {
	DrawCardEvent *DrawCardEvent `protobuf:"bytes,5,opt,name=drawCardEvent,proto3,oneof"`
}

type Event_NewActionEvent struct {
	NewActionEvent *NewActionEvent `protobuf:"bytes,6,opt,name=newActionEvent,proto3,oneof"`
}

type Event_RemoveActionEvent struct {
	RemoveActionEvent *RemoveActionEvent `protobuf:"bytes,7,opt,name=removeActionEvent,proto3,oneof"`
}

type Event_DispatchActionEvent struct {
	DispatchActionEvent *DispatchActionEvent `protobuf:"bytes,8,opt,name=dispatchActionEvent,proto3,oneof"`
}

type Event_ChangeBaoCardEvent struct {
	ChangeBaoCardEvent *ChangeBaoCardEvent `protobuf:"bytes,9,opt,name=changeBaoCardEvent,proto3,oneof"`
}

func (*Event_DiscardsEvent) isEvent_Event() {}

func (*Event_GameStartEvent) isEvent_Event() {}

func (*Event_DealCardsEvent) isEvent_Event() {}

func (*Event_ResumeEvent) isEvent_Event() {}

func (*Event_DrawCardEvent) isEvent_Event() {}

func (*Event_NewActionEvent) isEvent_Event() {}

func (*Event_RemoveActionEvent) isEvent_Event() {}

func (*Event_DispatchActionEvent) isEvent_Event() {}

func (*Event_ChangeBaoCardEvent) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetDiscardsEvent() *DiscardsEvent {
	if x, ok := m.GetEvent().(*Event_DiscardsEvent); ok {
		return x.DiscardsEvent
	}
	return nil
}

func (m *Event) GetGameStartEvent() *GameStartEvent {
	if x, ok := m.GetEvent().(*Event_GameStartEvent); ok {
		return x.GameStartEvent
	}
	return nil
}

func (m *Event) GetDealCardsEvent() *DealCardsEvent {
	if x, ok := m.GetEvent().(*Event_DealCardsEvent); ok {
		return x.DealCardsEvent
	}
	return nil
}

func (m *Event) GetResumeEvent() *ResumeEvent {
	if x, ok := m.GetEvent().(*Event_ResumeEvent); ok {
		return x.ResumeEvent
	}
	return nil
}

func (m *Event) GetDrawCardEvent() *DrawCardEvent {
	if x, ok := m.GetEvent().(*Event_DrawCardEvent); ok {
		return x.DrawCardEvent
	}
	return nil
}

func (m *Event) GetNewActionEvent() *NewActionEvent {
	if x, ok := m.GetEvent().(*Event_NewActionEvent); ok {
		return x.NewActionEvent
	}
	return nil
}

func (m *Event) GetRemoveActionEvent() *RemoveActionEvent {
	if x, ok := m.GetEvent().(*Event_RemoveActionEvent); ok {
		return x.RemoveActionEvent
	}
	return nil
}

func (m *Event) GetDispatchActionEvent() *DispatchActionEvent {
	if x, ok := m.GetEvent().(*Event_DispatchActionEvent); ok {
		return x.DispatchActionEvent
	}
	return nil
}

func (m *Event) GetChangeBaoCardEvent() *ChangeBaoCardEvent {
	if x, ok := m.GetEvent().(*Event_ChangeBaoCardEvent); ok {
		return x.ChangeBaoCardEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_DiscardsEvent)(nil),
		(*Event_GameStartEvent)(nil),
		(*Event_DealCardsEvent)(nil),
		(*Event_ResumeEvent)(nil),
		(*Event_DrawCardEvent)(nil),
		(*Event_NewActionEvent)(nil),
		(*Event_RemoveActionEvent)(nil),
		(*Event_DispatchActionEvent)(nil),
		(*Event_ChangeBaoCardEvent)(nil),
	}
}

// region 请求
// 替换想要的牌请求
type WantHoldsReq struct {
	Cards                []int32  `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WantHoldsReq) Reset()         { *m = WantHoldsReq{} }
func (m *WantHoldsReq) String() string { return proto.CompactTextString(m) }
func (*WantHoldsReq) ProtoMessage()    {}
func (*WantHoldsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{8}
}

func (m *WantHoldsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WantHoldsReq.Unmarshal(m, b)
}
func (m *WantHoldsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WantHoldsReq.Marshal(b, m, deterministic)
}
func (m *WantHoldsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WantHoldsReq.Merge(m, src)
}
func (m *WantHoldsReq) XXX_Size() int {
	return xxx_messageInfo_WantHoldsReq.Size(m)
}
func (m *WantHoldsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WantHoldsReq.DiscardUnknown(m)
}

var xxx_messageInfo_WantHoldsReq proto.InternalMessageInfo

func (m *WantHoldsReq) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 出牌请求
type DiscardsReq struct {
	Card                 int32    `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardsReq) Reset()         { *m = DiscardsReq{} }
func (m *DiscardsReq) String() string { return proto.CompactTextString(m) }
func (*DiscardsReq) ProtoMessage()    {}
func (*DiscardsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{9}
}

func (m *DiscardsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardsReq.Unmarshal(m, b)
}
func (m *DiscardsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardsReq.Marshal(b, m, deterministic)
}
func (m *DiscardsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardsReq.Merge(m, src)
}
func (m *DiscardsReq) XXX_Size() int {
	return xxx_messageInfo_DiscardsReq.Size(m)
}
func (m *DiscardsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardsReq proto.InternalMessageInfo

func (m *DiscardsReq) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

// 做action请求
type DoActionReq struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoActionReq) Reset()         { *m = DoActionReq{} }
func (m *DoActionReq) String() string { return proto.CompactTextString(m) }
func (*DoActionReq) ProtoMessage()    {}
func (*DoActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{10}
}

func (m *DoActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoActionReq.Unmarshal(m, b)
}
func (m *DoActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoActionReq.Marshal(b, m, deterministic)
}
func (m *DoActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoActionReq.Merge(m, src)
}
func (m *DoActionReq) XXX_Size() int {
	return xxx_messageInfo_DoActionReq.Size(m)
}
func (m *DoActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DoActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_DoActionReq proto.InternalMessageInfo

func (m *DoActionReq) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 过请求
type PassReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassReq) Reset()         { *m = PassReq{} }
func (m *PassReq) String() string { return proto.CompactTextString(m) }
func (*PassReq) ProtoMessage()    {}
func (*PassReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{11}
}

func (m *PassReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassReq.Unmarshal(m, b)
}
func (m *PassReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassReq.Marshal(b, m, deterministic)
}
func (m *PassReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassReq.Merge(m, src)
}
func (m *PassReq) XXX_Size() int {
	return xxx_messageInfo_PassReq.Size(m)
}
func (m *PassReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PassReq.DiscardUnknown(m)
}

var xxx_messageInfo_PassReq proto.InternalMessageInfo

// region 响应
// 错误响应
type ErrorRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorRsp) Reset()         { *m = ErrorRsp{} }
func (m *ErrorRsp) String() string { return proto.CompactTextString(m) }
func (*ErrorRsp) ProtoMessage()    {}
func (*ErrorRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{12}
}

func (m *ErrorRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorRsp.Unmarshal(m, b)
}
func (m *ErrorRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorRsp.Marshal(b, m, deterministic)
}
func (m *ErrorRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorRsp.Merge(m, src)
}
func (m *ErrorRsp) XXX_Size() int {
	return xxx_messageInfo_ErrorRsp.Size(m)
}
func (m *ErrorRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorRsp proto.InternalMessageInfo

// 出牌响应
type DiscardsRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardsRsp) Reset()         { *m = DiscardsRsp{} }
func (m *DiscardsRsp) String() string { return proto.CompactTextString(m) }
func (*DiscardsRsp) ProtoMessage()    {}
func (*DiscardsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{13}
}

func (m *DiscardsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardsRsp.Unmarshal(m, b)
}
func (m *DiscardsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardsRsp.Marshal(b, m, deterministic)
}
func (m *DiscardsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardsRsp.Merge(m, src)
}
func (m *DiscardsRsp) XXX_Size() int {
	return xxx_messageInfo_DiscardsRsp.Size(m)
}
func (m *DiscardsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardsRsp proto.InternalMessageInfo

// region 事件
type GameStartEvent struct {
	State                State    `protobuf:"varint,1,opt,name=state,proto3,enum=zlmj.State" json:"state,omitempty"`
	Cards                []int32  `protobuf:"varint,2,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	DrawCount            int32    `protobuf:"varint,3,opt,name=drawCount,proto3" json:"drawCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStartEvent) Reset()         { *m = GameStartEvent{} }
func (m *GameStartEvent) String() string { return proto.CompactTextString(m) }
func (*GameStartEvent) ProtoMessage()    {}
func (*GameStartEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{14}
}

func (m *GameStartEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStartEvent.Unmarshal(m, b)
}
func (m *GameStartEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStartEvent.Marshal(b, m, deterministic)
}
func (m *GameStartEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStartEvent.Merge(m, src)
}
func (m *GameStartEvent) XXX_Size() int {
	return xxx_messageInfo_GameStartEvent.Size(m)
}
func (m *GameStartEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStartEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameStartEvent proto.InternalMessageInfo

func (m *GameStartEvent) GetState() State {
	if m != nil {
		return m.State
	}
	return State_initing
}

func (m *GameStartEvent) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *GameStartEvent) GetDrawCount() int32 {
	if m != nil {
		return m.DrawCount
	}
	return 0
}

// 玩家打牌事件
type DiscardsEvent struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Card                 int32    `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardsEvent) Reset()         { *m = DiscardsEvent{} }
func (m *DiscardsEvent) String() string { return proto.CompactTextString(m) }
func (*DiscardsEvent) ProtoMessage()    {}
func (*DiscardsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{15}
}

func (m *DiscardsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardsEvent.Unmarshal(m, b)
}
func (m *DiscardsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardsEvent.Marshal(b, m, deterministic)
}
func (m *DiscardsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardsEvent.Merge(m, src)
}
func (m *DiscardsEvent) XXX_Size() int {
	return xxx_messageInfo_DiscardsEvent.Size(m)
}
func (m *DiscardsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardsEvent proto.InternalMessageInfo

func (m *DiscardsEvent) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DiscardsEvent) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

// 发牌事件
type DealCardsEvent struct {
	Players              []*PlayerData `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DealCardsEvent) Reset()         { *m = DealCardsEvent{} }
func (m *DealCardsEvent) String() string { return proto.CompactTextString(m) }
func (*DealCardsEvent) ProtoMessage()    {}
func (*DealCardsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{16}
}

func (m *DealCardsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealCardsEvent.Unmarshal(m, b)
}
func (m *DealCardsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealCardsEvent.Marshal(b, m, deterministic)
}
func (m *DealCardsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealCardsEvent.Merge(m, src)
}
func (m *DealCardsEvent) XXX_Size() int {
	return xxx_messageInfo_DealCardsEvent.Size(m)
}
func (m *DealCardsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DealCardsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DealCardsEvent proto.InternalMessageInfo

func (m *DealCardsEvent) GetPlayers() []*PlayerData {
	if m != nil {
		return m.Players
	}
	return nil
}

// 轮到某人打牌事件
type ResumeEvent struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	DiscardLeft          int32    `protobuf:"varint,2,opt,name=discardLeft,proto3" json:"discardLeft,omitempty"`
	IsNewRound           bool     `protobuf:"varint,3,opt,name=isNewRound,proto3" json:"isNewRound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeEvent) Reset()         { *m = ResumeEvent{} }
func (m *ResumeEvent) String() string { return proto.CompactTextString(m) }
func (*ResumeEvent) ProtoMessage()    {}
func (*ResumeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{17}
}

func (m *ResumeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeEvent.Unmarshal(m, b)
}
func (m *ResumeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeEvent.Marshal(b, m, deterministic)
}
func (m *ResumeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeEvent.Merge(m, src)
}
func (m *ResumeEvent) XXX_Size() int {
	return xxx_messageInfo_ResumeEvent.Size(m)
}
func (m *ResumeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeEvent proto.InternalMessageInfo

func (m *ResumeEvent) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ResumeEvent) GetDiscardLeft() int32 {
	if m != nil {
		return m.DiscardLeft
	}
	return 0
}

func (m *ResumeEvent) GetIsNewRound() bool {
	if m != nil {
		return m.IsNewRound
	}
	return false
}

// 玩家抓牌事件
type DrawCardEvent struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Card                 int32    `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	Back                 bool     `protobuf:"varint,3,opt,name=back,proto3" json:"back,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardEvent) Reset()         { *m = DrawCardEvent{} }
func (m *DrawCardEvent) String() string { return proto.CompactTextString(m) }
func (*DrawCardEvent) ProtoMessage()    {}
func (*DrawCardEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{18}
}

func (m *DrawCardEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardEvent.Unmarshal(m, b)
}
func (m *DrawCardEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardEvent.Marshal(b, m, deterministic)
}
func (m *DrawCardEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardEvent.Merge(m, src)
}
func (m *DrawCardEvent) XXX_Size() int {
	return xxx_messageInfo_DrawCardEvent.Size(m)
}
func (m *DrawCardEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardEvent proto.InternalMessageInfo

func (m *DrawCardEvent) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DrawCardEvent) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *DrawCardEvent) GetBack() bool {
	if m != nil {
		return m.Back
	}
	return false
}

// 玩家有新的操作
type NewActionEvent struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewActionEvent) Reset()         { *m = NewActionEvent{} }
func (m *NewActionEvent) String() string { return proto.CompactTextString(m) }
func (*NewActionEvent) ProtoMessage()    {}
func (*NewActionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{19}
}

func (m *NewActionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewActionEvent.Unmarshal(m, b)
}
func (m *NewActionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewActionEvent.Marshal(b, m, deterministic)
}
func (m *NewActionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewActionEvent.Merge(m, src)
}
func (m *NewActionEvent) XXX_Size() int {
	return xxx_messageInfo_NewActionEvent.Size(m)
}
func (m *NewActionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NewActionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NewActionEvent proto.InternalMessageInfo

func (m *NewActionEvent) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

// 取消玩家的action
type RemoveActionEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveActionEvent) Reset()         { *m = RemoveActionEvent{} }
func (m *RemoveActionEvent) String() string { return proto.CompactTextString(m) }
func (*RemoveActionEvent) ProtoMessage()    {}
func (*RemoveActionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{20}
}

func (m *RemoveActionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveActionEvent.Unmarshal(m, b)
}
func (m *RemoveActionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveActionEvent.Marshal(b, m, deterministic)
}
func (m *RemoveActionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveActionEvent.Merge(m, src)
}
func (m *RemoveActionEvent) XXX_Size() int {
	return xxx_messageInfo_RemoveActionEvent.Size(m)
}
func (m *RemoveActionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveActionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveActionEvent proto.InternalMessageInfo

// 操作分发事件 即别人做了操作
type DispatchActionEvent struct {
	Action               *Action  `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DispatchActionEvent) Reset()         { *m = DispatchActionEvent{} }
func (m *DispatchActionEvent) String() string { return proto.CompactTextString(m) }
func (*DispatchActionEvent) ProtoMessage()    {}
func (*DispatchActionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{21}
}

func (m *DispatchActionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchActionEvent.Unmarshal(m, b)
}
func (m *DispatchActionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchActionEvent.Marshal(b, m, deterministic)
}
func (m *DispatchActionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchActionEvent.Merge(m, src)
}
func (m *DispatchActionEvent) XXX_Size() int {
	return xxx_messageInfo_DispatchActionEvent.Size(m)
}
func (m *DispatchActionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchActionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchActionEvent proto.InternalMessageInfo

func (m *DispatchActionEvent) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

// 宝牌更换事件
type ChangeBaoCardEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeBaoCardEvent) Reset()         { *m = ChangeBaoCardEvent{} }
func (m *ChangeBaoCardEvent) String() string { return proto.CompactTextString(m) }
func (*ChangeBaoCardEvent) ProtoMessage()    {}
func (*ChangeBaoCardEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba28b2cf51ceff1b, []int{22}
}

func (m *ChangeBaoCardEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeBaoCardEvent.Unmarshal(m, b)
}
func (m *ChangeBaoCardEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeBaoCardEvent.Marshal(b, m, deterministic)
}
func (m *ChangeBaoCardEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeBaoCardEvent.Merge(m, src)
}
func (m *ChangeBaoCardEvent) XXX_Size() int {
	return xxx_messageInfo_ChangeBaoCardEvent.Size(m)
}
func (m *ChangeBaoCardEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeBaoCardEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeBaoCardEvent proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("zlmj.State", State_name, State_value)
	proto.RegisterEnum("zlmj.ActionId", ActionId_name, ActionId_value)
	proto.RegisterEnum("zlmj.CombinationId", CombinationId_name, CombinationId_value)
	proto.RegisterType((*Option)(nil), "zlmj.Option")
	proto.RegisterType((*GameData)(nil), "zlmj.GameData")
	proto.RegisterType((*PlayerData)(nil), "zlmj.PlayerData")
	proto.RegisterType((*Action)(nil), "zlmj.Action")
	proto.RegisterType((*Combination)(nil), "zlmj.Combination")
	proto.RegisterType((*Req)(nil), "zlmj.Req")
	proto.RegisterType((*Rsp)(nil), "zlmj.Rsp")
	proto.RegisterType((*Event)(nil), "zlmj.Event")
	proto.RegisterType((*WantHoldsReq)(nil), "zlmj.WantHoldsReq")
	proto.RegisterType((*DiscardsReq)(nil), "zlmj.DiscardsReq")
	proto.RegisterType((*DoActionReq)(nil), "zlmj.DoActionReq")
	proto.RegisterType((*PassReq)(nil), "zlmj.PassReq")
	proto.RegisterType((*ErrorRsp)(nil), "zlmj.ErrorRsp")
	proto.RegisterType((*DiscardsRsp)(nil), "zlmj.DiscardsRsp")
	proto.RegisterType((*GameStartEvent)(nil), "zlmj.GameStartEvent")
	proto.RegisterType((*DiscardsEvent)(nil), "zlmj.DiscardsEvent")
	proto.RegisterType((*DealCardsEvent)(nil), "zlmj.DealCardsEvent")
	proto.RegisterType((*ResumeEvent)(nil), "zlmj.ResumeEvent")
	proto.RegisterType((*DrawCardEvent)(nil), "zlmj.DrawCardEvent")
	proto.RegisterType((*NewActionEvent)(nil), "zlmj.NewActionEvent")
	proto.RegisterType((*RemoveActionEvent)(nil), "zlmj.RemoveActionEvent")
	proto.RegisterType((*DispatchActionEvent)(nil), "zlmj.DispatchActionEvent")
	proto.RegisterType((*ChangeBaoCardEvent)(nil), "zlmj.ChangeBaoCardEvent")
}

func init() { proto.RegisterFile("zlmj/zlmj.proto", fileDescriptor_ba28b2cf51ceff1b) }

var fileDescriptor_ba28b2cf51ceff1b = []byte{
	// 1414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xcf, 0x8f, 0xdb, 0xc4,
	0x17, 0x8f, 0xe3, 0x38, 0x71, 0x9e, 0x93, 0x6c, 0x76, 0xb6, 0xfa, 0x7e, 0x0d, 0xaa, 0xd0, 0xd6,
	0x54, 0x68, 0x59, 0xa1, 0x02, 0x8b, 0x2a, 0xb5, 0x2a, 0x20, 0xb1, 0x49, 0xbb, 0x69, 0xa1, 0xa5,
	0x9a, 0x22, 0x01, 0xa7, 0x68, 0xe2, 0x4c, 0x9d, 0x69, 0x13, 0x3b, 0xf1, 0x8f, 0xee, 0x96, 0x13,
	0x27, 0xc4, 0x9d, 0xbf, 0x8c, 0x0b, 0x57, 0xb8, 0xf0, 0x7f, 0xa0, 0x79, 0x33, 0xb1, 0xc7, 0xbb,
	0x29, 0xf4, 0x12, 0xf9, 0x7d, 0x3e, 0xef, 0xcd, 0xfb, 0x6d, 0x4f, 0x60, 0xef, 0xa7, 0xe5, 0xea,
	0xc5, 0xc7, 0xf2, 0xe7, 0xd6, 0x3a, 0x4d, 0xf2, 0x84, 0xb4, 0xe4, 0x73, 0xf0, 0x87, 0x0d, 0xed,
	0x6f, 0xd7, 0xb9, 0x48, 0x62, 0x72, 0x0d, 0x9c, 0x70, 0xc1, 0x59, 0xee, 0x5b, 0x87, 0xd6, 0x91,
	0x4b, 0x95, 0x40, 0xde, 0x05, 0xf7, 0x42, 0x8c, 0x45, 0x1c, 0xfd, 0x20, 0xfc, 0x26, 0x12, 0xa5,
	0x4c, 0xde, 0x03, 0x78, 0xcd, 0x92, 0x47, 0xa2, 0x38, 0x63, 0x71, 0xe4, 0xdb, 0xc8, 0x1a, 0x08,
	0x09, 0xa0, 0xa7, 0xa4, 0x47, 0x82, 0x3d, 0x60, 0xb1, 0xdf, 0x42, 0x8d, 0x1a, 0x46, 0xae, 0x43,
	0x77, 0x23, 0x58, 0x1c, 0x7d, 0x27, 0xe2, 0xc8, 0x77, 0x50, 0xa1, 0x02, 0x24, 0x1b, 0x15, 0x6c,
	0xcc, 0x1e, 0xf0, 0x38, 0xf2, 0xdb, 0x8a, 0x2d, 0x01, 0xe2, 0x43, 0xe7, 0x42, 0xb0, 0x31, 0xfb,
	0xb1, 0xf0, 0x3b, 0xc8, 0x6d, 0x45, 0xc9, 0xbc, 0x2c, 0x98, 0x38, 0x65, 0x89, 0xef, 0x2a, 0x46,
	0x8b, 0x92, 0x99, 0xb1, 0x04, 0x03, 0xee, 0x2a, 0x46, 0x8b, 0x32, 0xff, 0x8d, 0x18, 0x17, 0xc2,
	0x07, 0x95, 0x3f, 0x0a, 0x32, 0x82, 0x19, 0x17, 0x5f, 0xb3, 0xe4, 0x94, 0x0b, 0xdf, 0x53, 0x11,
	0x94, 0x00, 0x39, 0x04, 0xef, 0x42, 0x9c, 0x16, 0x67, 0x85, 0x8a, 0xb0, 0x87, 0xbc, 0x09, 0xc9,
	0xfa, 0xc5, 0xc9, 0x68, 0x21, 0x46, 0x0b, 0xe6, 0xf7, 0x55, 0xfd, 0xb6, 0xb2, 0xac, 0xcf, 0x5c,
	0xb0, 0xf8, 0x29, 0x4b, 0x1e, 0x88, 0x34, 0xcb, 0xfd, 0x81, 0xaa, 0x8f, 0x89, 0x49, 0xff, 0x2b,
	0x11, 0x47, 0xb7, 0x59, 0xfc, 0xe9, 0x27, 0xfe, 0x9e, 0xf2, 0x5f, 0x02, 0xba, 0x02, 0x89, 0x2c,
	0xee, 0xb0, 0xac, 0x80, 0x14, 0x83, 0xdf, 0x9b, 0xe0, 0x9e, 0xb1, 0x15, 0x1f, 0xb3, 0x9c, 0x91,
	0x1b, 0xe0, 0x64, 0x39, 0xcb, 0x39, 0xb6, 0x76, 0x70, 0xe2, 0xdd, 0xc2, 0x39, 0x78, 0x26, 0x21,
	0xaa, 0x18, 0x72, 0x13, 0xda, 0x09, 0xce, 0x01, 0x76, 0xd9, 0x3b, 0xe9, 0x29, 0x1d, 0x35, 0x1b,
	0x54, 0x73, 0xe4, 0x18, 0x3a, 0xeb, 0x25, 0x7b, 0xcd, 0xd3, 0xcc, 0xb7, 0x0f, 0xed, 0x23, 0xef,
	0x64, 0xa8, 0xd4, 0x9e, 0x22, 0x28, 0x7d, 0xd1, 0xad, 0x02, 0xb9, 0x09, 0xfd, 0x19, 0x0b, 0x5f,
	0x8e, 0x58, 0x3a, 0x1f, 0x25, 0x45, 0x9c, 0x63, 0xfb, 0x1d, 0x5a, 0x07, 0x71, 0xea, 0x58, 0x3a,
	0xcf, 0x7c, 0xe7, 0xd0, 0x3e, 0x72, 0xa8, 0x12, 0x64, 0x5d, 0x97, 0x2c, 0xcb, 0xc7, 0x22, 0x93,
	0x9a, 0xd8, 0x79, 0x87, 0x9a, 0x10, 0x39, 0x82, 0xbd, 0xb0, 0x48, 0xc7, 0x22, 0x93, 0x06, 0x0f,
	0xe3, 0x39, 0xbf, 0xc0, 0x19, 0x70, 0xe8, 0x65, 0x98, 0x1c, 0xc3, 0x50, 0x1b, 0x56, 0xaa, 0x2e,
	0xaa, 0x5e, 0xc1, 0x65, 0xb5, 0xc3, 0x32, 0xde, 0x2e, 0x2a, 0x55, 0x40, 0xf0, 0xb3, 0x0d, 0x50,
	0x65, 0x4a, 0xfe, 0x07, 0xed, 0x22, 0xe3, 0xe9, 0xc3, 0x39, 0x96, 0xd5, 0xa1, 0x5a, 0x92, 0x29,
	0x09, 0xf4, 0xd2, 0x44, 0x58, 0x09, 0x72, 0x59, 0x16, 0xc9, 0x72, 0x9e, 0xa9, 0xb3, 0x6d, 0xa4,
	0x0c, 0x44, 0x5a, 0xa1, 0xe4, 0xb7, 0x54, 0x21, 0x50, 0x90, 0xe8, 0x73, 0x44, 0x75, 0x79, 0x50,
	0x50, 0x61, 0xc6, 0xa3, 0x45, 0xb1, 0x66, 0x62, 0xbb, 0x16, 0x25, 0x20, 0x6d, 0xb2, 0x30, 0x49,
	0xb9, 0x2e, 0x88, 0x12, 0xa4, 0xff, 0x3c, 0xc9, 0xd9, 0xf2, 0x19, 0x52, 0xaa, 0x00, 0x06, 0x22,
	0x07, 0x55, 0x64, 0x8f, 0x59, 0x96, 0xf3, 0x54, 0x6f, 0x46, 0x29, 0xcb, 0x31, 0x0b, 0x8b, 0x14,
	0x5b, 0x01, 0x68, 0xb8, 0x15, 0xd5, 0x08, 0x67, 0x6c, 0xb6, 0xe4, 0x23, 0xec, 0xa2, 0x87, 0x61,
	0xd6, 0x30, 0xa9, 0x23, 0x32, 0xca, 0xd7, 0x49, 0x9a, 0xe3, 0x96, 0xab, 0x2d, 0xa9, 0x61, 0xe4,
	0x03, 0xe8, 0xb0, 0x50, 0x8e, 0x58, 0xe6, 0xf7, 0x71, 0xb0, 0xf4, 0xfc, 0x7d, 0x85, 0x20, 0xdd,
	0x92, 0xc1, 0xaf, 0x16, 0xb4, 0x15, 0x46, 0x8e, 0xc1, 0x55, 0xa8, 0x6e, 0xc0, 0xe0, 0x64, 0x60,
	0xda, 0x3c, 0x9c, 0xd3, 0x92, 0x7f, 0x43, 0x4b, 0x08, 0xb4, 0x9e, 0xa7, 0xc9, 0x4a, 0x37, 0x03,
	0x9f, 0x25, 0x26, 0x1b, 0xae, 0x87, 0x15, 0x9f, 0x77, 0xcf, 0x68, 0xf0, 0x8b, 0x05, 0xde, 0x28,
	0x59, 0xcd, 0x44, 0xcc, 0x30, 0x9e, 0xbb, 0xd0, 0x0f, 0x2b, 0xb1, 0x0c, 0xea, 0x40, 0x05, 0x35,
	0x32, 0x29, 0x5a, 0xd7, 0x2c, 0x03, 0x69, 0xee, 0x08, 0xc4, 0xde, 0x15, 0x48, 0xcb, 0x0c, 0xe4,
	0x4f, 0x0b, 0x6c, 0xca, 0x37, 0xe4, 0x36, 0x78, 0x73, 0x35, 0xcc, 0x19, 0xe5, 0x1b, 0x74, 0xef,
	0x9d, 0xec, 0x2b, 0xf7, 0xe3, 0x8a, 0x98, 0x34, 0xa8, 0xa9, 0x47, 0xee, 0x40, 0xef, 0x9c, 0xc5,
	0xf9, 0x44, 0x4e, 0x96, 0xb4, 0x53, 0xfb, 0x4f, 0x94, 0xdd, 0xf7, 0x06, 0x33, 0x69, 0xd0, 0x9a,
	0x26, 0x3a, 0x4c, 0x74, 0x87, 0xf8, 0x06, 0x23, 0xad, 0x1c, 0x56, 0x04, 0x3a, 0xac, 0x44, 0xf2,
	0x21, 0x74, 0xd6, 0x2c, 0x43, 0x5f, 0x2d, 0x34, 0xe9, 0xeb, 0x97, 0x88, 0x02, 0x27, 0x0d, 0xba,
	0xe5, 0x4f, 0x1d, 0xb0, 0x53, 0xbe, 0x09, 0x36, 0x60, 0xd3, 0x6c, 0x4d, 0x3e, 0x02, 0x97, 0xa7,
	0x69, 0x92, 0xd2, 0x6c, 0xad, 0xb3, 0xd3, 0x1d, 0xbf, 0xaf, 0xd1, 0x49, 0x83, 0x96, 0x1a, 0xb5,
	0x72, 0x64, 0x6b, 0x9d, 0xd6, 0xe5, 0x72, 0xa0, 0x8d, 0xa9, 0x87, 0x2e, 0xb3, 0x75, 0xf0, 0x77,
	0x0b, 0x9c, 0xfb, 0xaf, 0x78, 0x9c, 0x93, 0x7b, 0xd0, 0xdf, 0xf2, 0x08, 0x68, 0xd7, 0x07, 0xf5,
	0x93, 0x90, 0x9a, 0x34, 0x68, 0x5d, 0x97, 0x7c, 0x09, 0x83, 0x88, 0xad, 0xf8, 0xb3, 0x9c, 0xa5,
	0xb9, 0xb2, 0x56, 0x71, 0x5c, 0x53, 0xd6, 0x67, 0x35, 0x6e, 0xd2, 0xa0, 0x97, 0xb4, 0xa5, 0xfd,
	0x9c, 0xb3, 0xe5, 0xa8, 0xf2, 0x6e, 0x9b, 0xf6, 0xe3, 0x1a, 0x27, 0xed, 0xeb, 0xda, 0xb2, 0x08,
	0x29, 0xcf, 0x8a, 0x15, 0x57, 0xc6, 0x2d, 0xb3, 0x08, 0xb4, 0x22, 0x64, 0x11, 0x0c, 0x3d, 0xcc,
	0x39, 0x65, 0xe7, 0xf2, 0x20, 0x65, 0xe8, 0xd4, 0x72, 0x36, 0x29, 0xcc, 0xd9, 0x04, 0x64, 0xcc,
	0x31, 0x3f, 0x57, 0xfd, 0x56, 0xd6, 0x6d, 0x33, 0xe6, 0x27, 0x35, 0x4e, 0xc6, 0x5c, 0xd7, 0x26,
	0x67, 0xb0, 0x9f, 0xf2, 0x55, 0xf2, 0x8a, 0x9b, 0x47, 0x74, 0xf0, 0x88, 0xff, 0x6f, 0x23, 0xbf,
	0x44, 0x4f, 0x1a, 0xf4, 0xaa, 0x0d, 0x79, 0x0c, 0x07, 0x73, 0x91, 0xad, 0x59, 0x1e, 0x2e, 0xcc,
	0xa3, 0x5c, 0x3c, 0xea, 0x9d, 0xb2, 0x7f, 0x97, 0x15, 0x26, 0x0d, 0xba, 0xcb, 0x8e, 0x3c, 0x02,
	0x12, 0x2e, 0x58, 0x1c, 0xf1, 0x53, 0x96, 0x54, 0x95, 0xe9, 0xe2, 0x69, 0xbe, 0xde, 0xf2, 0x2b,
	0xfc, 0xa4, 0x41, 0x77, 0x58, 0x9d, 0x76, 0xc0, 0xe1, 0xf2, 0x21, 0xb8, 0x09, 0x3d, 0x73, 0xc7,
	0xaa, 0x15, 0xb7, 0xcc, 0x15, 0xbf, 0x01, 0x9e, 0xb1, 0xc1, 0xe5, 0xbb, 0xc1, 0xaa, 0xde, 0x0d,
	0xc1, 0xfb, 0xe0, 0x19, 0x3b, 0x57, 0xbd, 0xf1, 0x2c, 0xe3, 0x8d, 0x17, 0x74, 0xa1, 0xa3, 0xb7,
	0x2c, 0x00, 0x70, 0xb7, 0x6b, 0x13, 0xf4, 0x8d, 0xe3, 0xb3, 0x75, 0x10, 0xc1, 0xa0, 0x3e, 0x98,
	0x6f, 0x73, 0x81, 0x28, 0x03, 0x6f, 0x9a, 0x1f, 0xf2, 0xeb, 0xd0, 0xc5, 0xe1, 0x30, 0x3e, 0x7a,
	0x15, 0x10, 0xdc, 0x85, 0x7e, 0x6d, 0x7f, 0x76, 0x47, 0x5d, 0xa6, 0xdb, 0x34, 0xd2, 0xfd, 0x1c,
	0x06, 0xf5, 0xe1, 0x37, 0xef, 0x26, 0xd6, 0x7f, 0xdc, 0x4d, 0x02, 0x0e, 0x9e, 0x31, 0xfd, 0x6f,
	0x70, 0x7b, 0x58, 0xbe, 0x40, 0xbe, 0xe1, 0xcf, 0x73, 0xed, 0xdd, 0x84, 0xe4, 0x37, 0x55, 0x64,
	0x4f, 0xf8, 0x39, 0x4d, 0x8a, 0x78, 0xbe, 0xbd, 0x00, 0x57, 0x48, 0xf0, 0x18, 0xfa, 0xb5, 0x5d,
	0x79, 0xfb, 0xfc, 0x24, 0x26, 0x2f, 0x4a, 0xfa, 0x50, 0x7c, 0x0e, 0xee, 0xc0, 0xa0, 0xbe, 0x3c,
	0xe6, 0x67, 0xd3, 0xfa, 0xb7, 0xcf, 0xe6, 0x01, 0xec, 0x5f, 0xd9, 0x99, 0xe0, 0x1e, 0x1c, 0xec,
	0x98, 0x7e, 0x79, 0x13, 0x54, 0x66, 0xfa, 0x45, 0x57, 0x3f, 0x52, 0x73, 0xc1, 0x35, 0x20, 0x57,
	0x87, 0xfd, 0xf8, 0x0b, 0x70, 0x70, 0x28, 0x88, 0x07, 0x1d, 0x11, 0x8b, 0x5c, 0xc4, 0xd1, 0xb0,
	0x41, 0x7a, 0xe0, 0xe2, 0x9f, 0x09, 0x29, 0x59, 0x64, 0x0f, 0xbc, 0x90, 0xc5, 0x53, 0x5d, 0xc7,
	0x61, 0x93, 0xb8, 0xd0, 0x4a, 0x5e, 0xf1, 0x74, 0x68, 0x1f, 0xff, 0x65, 0x81, 0xbb, 0xfd, 0x7a,
	0x4b, 0x58, 0x7e, 0x06, 0x86, 0x0d, 0xd2, 0x01, 0x3b, 0x5c, 0x88, 0xa1, 0x85, 0x10, 0x8f, 0x23,
	0x65, 0x13, 0xb1, 0x38, 0x1a, 0xda, 0xd2, 0x13, 0x8b, 0xa7, 0x28, 0xb4, 0xc8, 0x00, 0x20, 0x2a,
	0x92, 0x65, 0xa1, 0x64, 0x47, 0xaa, 0xa1, 0xd7, 0xb6, 0x8c, 0xe1, 0x35, 0x4b, 0x14, 0xde, 0x91,
	0xd2, 0x0b, 0xa1, 0xb5, 0x5c, 0x19, 0xd1, 0xac, 0x98, 0x96, 0x74, 0x57, 0x03, 0xa5, 0x06, 0xc8,
	0x73, 0x59, 0x3c, 0xbd, 0x10, 0x4a, 0xf6, 0xc8, 0x10, 0x7a, 0xf2, 0x12, 0x5e, 0x22, 0x3d, 0xb2,
	0x0f, 0xfd, 0x59, 0x31, 0x35, 0x94, 0xfa, 0xe4, 0x00, 0xf6, 0x66, 0xc5, 0xb4, 0xa6, 0x37, 0x38,
	0xfe, 0xcd, 0x82, 0x7e, 0xed, 0x2e, 0x40, 0x00, 0xda, 0xe1, 0x54, 0x67, 0xda, 0x05, 0x27, 0x9c,
	0xaa, 0x5c, 0x15, 0xac, 0xb2, 0xc5, 0x67, 0x9d, 0x6f, 0x1f, 0xba, 0xe1, 0xb4, 0x96, 0x71, 0x58,
	0x85, 0xee, 0x28, 0xb9, 0x8c, 0xbc, 0x2d, 0x23, 0x0d, 0xcd, 0xb0, 0x3a, 0x84, 0xc0, 0x20, 0xac,
	0x47, 0xe5, 0xce, 0xda, 0xf8, 0x9f, 0xf0, 0xb3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x2c,
	0x65, 0xba, 0x26, 0x0e, 0x00, 0x00,
}
