// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop/shop.proto

package shop

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 单件物品
type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 单件商品
type Good struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImgUrl               string   `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	T                    int32    `protobuf:"varint,5,opt,name=t,proto3" json:"t,omitempty"`
	Total                int32    `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Sold                 int32    `protobuf:"varint,7,opt,name=sold,proto3" json:"sold,omitempty"`
	Price                int32    `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Discount             int32    `protobuf:"varint,9,opt,name=discount,proto3" json:"discount,omitempty"`
	State                int32    `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`
	CurrencyType         int32    `protobuf:"varint,11,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	Items                []*Item  `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	Tag                  []string `protobuf:"bytes,13,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Good) Reset()         { *m = Good{} }
func (m *Good) String() string { return proto.CompactTextString(m) }
func (*Good) ProtoMessage()    {}
func (*Good) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{1}
}

func (m *Good) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Good.Unmarshal(m, b)
}
func (m *Good) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Good.Marshal(b, m, deterministic)
}
func (m *Good) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Good.Merge(m, src)
}
func (m *Good) XXX_Size() int {
	return xxx_messageInfo_Good.Size(m)
}
func (m *Good) XXX_DiscardUnknown() {
	xxx_messageInfo_Good.DiscardUnknown(m)
}

var xxx_messageInfo_Good proto.InternalMessageInfo

func (m *Good) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Good) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Good) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *Good) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Good) GetT() int32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *Good) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Good) GetSold() int32 {
	if m != nil {
		return m.Sold
	}
	return 0
}

func (m *Good) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Good) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Good) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Good) GetCurrencyType() int32 {
	if m != nil {
		return m.CurrencyType
	}
	return 0
}

func (m *Good) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Good) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GetGoodsListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	T                    int32    `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsListRequest) Reset()         { *m = GetGoodsListRequest{} }
func (m *GetGoodsListRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoodsListRequest) ProtoMessage()    {}
func (*GetGoodsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{2}
}

func (m *GetGoodsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsListRequest.Unmarshal(m, b)
}
func (m *GetGoodsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsListRequest.Marshal(b, m, deterministic)
}
func (m *GetGoodsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsListRequest.Merge(m, src)
}
func (m *GetGoodsListRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoodsListRequest.Size(m)
}
func (m *GetGoodsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsListRequest proto.InternalMessageInfo

func (m *GetGoodsListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetGoodsListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetGoodsListRequest) GetT() int32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *GetGoodsListRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetGoodsListResponse struct {
	Goods                []*GetGoodsListResponseGood `protobuf:"bytes,1,rep,name=Goods,proto3" json:"Goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetGoodsListResponse) Reset()         { *m = GetGoodsListResponse{} }
func (m *GetGoodsListResponse) String() string { return proto.CompactTextString(m) }
func (*GetGoodsListResponse) ProtoMessage()    {}
func (*GetGoodsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{3}
}

func (m *GetGoodsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsListResponse.Unmarshal(m, b)
}
func (m *GetGoodsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsListResponse.Marshal(b, m, deterministic)
}
func (m *GetGoodsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsListResponse.Merge(m, src)
}
func (m *GetGoodsListResponse) XXX_Size() int {
	return xxx_messageInfo_GetGoodsListResponse.Size(m)
}
func (m *GetGoodsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsListResponse proto.InternalMessageInfo

func (m *GetGoodsListResponse) GetGoods() []*GetGoodsListResponseGood {
	if m != nil {
		return m.Goods
	}
	return nil
}

type GetGoodsListResponseGood struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImgUrl               string   `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	T                    int32    `protobuf:"varint,5,opt,name=t,proto3" json:"t,omitempty"`
	Total                int32    `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Sold                 int32    `protobuf:"varint,7,opt,name=sold,proto3" json:"sold,omitempty"`
	Price                int32    `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Discount             int32    `protobuf:"varint,9,opt,name=discount,proto3" json:"discount,omitempty"`
	State                int32    `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`
	CurrencyType         int32    `protobuf:"varint,11,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	Items                []*Item  `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	Tag                  []string `protobuf:"bytes,13,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsListResponseGood) Reset()         { *m = GetGoodsListResponseGood{} }
func (m *GetGoodsListResponseGood) String() string { return proto.CompactTextString(m) }
func (*GetGoodsListResponseGood) ProtoMessage()    {}
func (*GetGoodsListResponseGood) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{3, 0}
}

func (m *GetGoodsListResponseGood) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsListResponseGood.Unmarshal(m, b)
}
func (m *GetGoodsListResponseGood) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsListResponseGood.Marshal(b, m, deterministic)
}
func (m *GetGoodsListResponseGood) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsListResponseGood.Merge(m, src)
}
func (m *GetGoodsListResponseGood) XXX_Size() int {
	return xxx_messageInfo_GetGoodsListResponseGood.Size(m)
}
func (m *GetGoodsListResponseGood) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsListResponseGood.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsListResponseGood proto.InternalMessageInfo

func (m *GetGoodsListResponseGood) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGoodsListResponseGood) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *GetGoodsListResponseGood) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetGoodsListResponseGood) GetT() int32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetSold() int32 {
	if m != nil {
		return m.Sold
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetCurrencyType() int32 {
	if m != nil {
		return m.CurrencyType
	}
	return 0
}

func (m *GetGoodsListResponseGood) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetGoodsListResponseGood) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type AddOneGoodRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImgUrl               string   `protobuf:"bytes,2,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	T                    int32    `protobuf:"varint,4,opt,name=t,proto3" json:"t,omitempty"`
	Total                int32    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Sold                 int32    `protobuf:"varint,6,opt,name=sold,proto3" json:"sold,omitempty"`
	Price                int32    `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Discount             int32    `protobuf:"varint,8,opt,name=discount,proto3" json:"discount,omitempty"`
	State                int32    `protobuf:"varint,9,opt,name=state,proto3" json:"state,omitempty"`
	CurrencyType         int32    `protobuf:"varint,10,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	Items                []*Item  `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	Tag                  []string `protobuf:"bytes,12,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOneGoodRequest) Reset()         { *m = AddOneGoodRequest{} }
func (m *AddOneGoodRequest) String() string { return proto.CompactTextString(m) }
func (*AddOneGoodRequest) ProtoMessage()    {}
func (*AddOneGoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{4}
}

func (m *AddOneGoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOneGoodRequest.Unmarshal(m, b)
}
func (m *AddOneGoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOneGoodRequest.Marshal(b, m, deterministic)
}
func (m *AddOneGoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOneGoodRequest.Merge(m, src)
}
func (m *AddOneGoodRequest) XXX_Size() int {
	return xxx_messageInfo_AddOneGoodRequest.Size(m)
}
func (m *AddOneGoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOneGoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOneGoodRequest proto.InternalMessageInfo

func (m *AddOneGoodRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddOneGoodRequest) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *AddOneGoodRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddOneGoodRequest) GetT() int32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *AddOneGoodRequest) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AddOneGoodRequest) GetSold() int32 {
	if m != nil {
		return m.Sold
	}
	return 0
}

func (m *AddOneGoodRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddOneGoodRequest) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *AddOneGoodRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *AddOneGoodRequest) GetCurrencyType() int32 {
	if m != nil {
		return m.CurrencyType
	}
	return 0
}

func (m *AddOneGoodRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *AddOneGoodRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type AddOneGoodResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOneGoodResponse) Reset()         { *m = AddOneGoodResponse{} }
func (m *AddOneGoodResponse) String() string { return proto.CompactTextString(m) }
func (*AddOneGoodResponse) ProtoMessage()    {}
func (*AddOneGoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{5}
}

func (m *AddOneGoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOneGoodResponse.Unmarshal(m, b)
}
func (m *AddOneGoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOneGoodResponse.Marshal(b, m, deterministic)
}
func (m *AddOneGoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOneGoodResponse.Merge(m, src)
}
func (m *AddOneGoodResponse) XXX_Size() int {
	return xxx_messageInfo_AddOneGoodResponse.Size(m)
}
func (m *AddOneGoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOneGoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOneGoodResponse proto.InternalMessageInfo

func (m *AddOneGoodResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateOneGoodRequest struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Update               map[string]string `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Items                []*Item           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateOneGoodRequest) Reset()         { *m = UpdateOneGoodRequest{} }
func (m *UpdateOneGoodRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOneGoodRequest) ProtoMessage()    {}
func (*UpdateOneGoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{6}
}

func (m *UpdateOneGoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOneGoodRequest.Unmarshal(m, b)
}
func (m *UpdateOneGoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOneGoodRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOneGoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOneGoodRequest.Merge(m, src)
}
func (m *UpdateOneGoodRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOneGoodRequest.Size(m)
}
func (m *UpdateOneGoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOneGoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOneGoodRequest proto.InternalMessageInfo

func (m *UpdateOneGoodRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateOneGoodRequest) GetUpdate() map[string]string {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateOneGoodRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateOneGoodResponse struct {
	Good                 *Good    `protobuf:"bytes,1,opt,name=good,proto3" json:"good,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOneGoodResponse) Reset()         { *m = UpdateOneGoodResponse{} }
func (m *UpdateOneGoodResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOneGoodResponse) ProtoMessage()    {}
func (*UpdateOneGoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{7}
}

func (m *UpdateOneGoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOneGoodResponse.Unmarshal(m, b)
}
func (m *UpdateOneGoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOneGoodResponse.Marshal(b, m, deterministic)
}
func (m *UpdateOneGoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOneGoodResponse.Merge(m, src)
}
func (m *UpdateOneGoodResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOneGoodResponse.Size(m)
}
func (m *UpdateOneGoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOneGoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOneGoodResponse proto.InternalMessageInfo

func (m *UpdateOneGoodResponse) GetGood() *Good {
	if m != nil {
		return m.Good
	}
	return nil
}

func (m *UpdateOneGoodResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type BuyOneGoodRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyOneGoodRequest) Reset()         { *m = BuyOneGoodRequest{} }
func (m *BuyOneGoodRequest) String() string { return proto.CompactTextString(m) }
func (*BuyOneGoodRequest) ProtoMessage()    {}
func (*BuyOneGoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{8}
}

func (m *BuyOneGoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyOneGoodRequest.Unmarshal(m, b)
}
func (m *BuyOneGoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyOneGoodRequest.Marshal(b, m, deterministic)
}
func (m *BuyOneGoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyOneGoodRequest.Merge(m, src)
}
func (m *BuyOneGoodRequest) XXX_Size() int {
	return xxx_messageInfo_BuyOneGoodRequest.Size(m)
}
func (m *BuyOneGoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyOneGoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyOneGoodRequest proto.InternalMessageInfo

func (m *BuyOneGoodRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuyOneGoodRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *BuyOneGoodRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type BuyOneGoodResponse struct {
	Items                []*Item          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UserUpdate           map[string]int32 `protobuf:"bytes,2,rep,name=userUpdate,proto3" json:"userUpdate,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	GoodUpdate           *Good            `protobuf:"bytes,3,opt,name=goodUpdate,proto3" json:"goodUpdate,omitempty"`
	Success              bool             `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string           `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BuyOneGoodResponse) Reset()         { *m = BuyOneGoodResponse{} }
func (m *BuyOneGoodResponse) String() string { return proto.CompactTextString(m) }
func (*BuyOneGoodResponse) ProtoMessage()    {}
func (*BuyOneGoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{9}
}

func (m *BuyOneGoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyOneGoodResponse.Unmarshal(m, b)
}
func (m *BuyOneGoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyOneGoodResponse.Marshal(b, m, deterministic)
}
func (m *BuyOneGoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyOneGoodResponse.Merge(m, src)
}
func (m *BuyOneGoodResponse) XXX_Size() int {
	return xxx_messageInfo_BuyOneGoodResponse.Size(m)
}
func (m *BuyOneGoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyOneGoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyOneGoodResponse proto.InternalMessageInfo

func (m *BuyOneGoodResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *BuyOneGoodResponse) GetUserUpdate() map[string]int32 {
	if m != nil {
		return m.UserUpdate
	}
	return nil
}

func (m *BuyOneGoodResponse) GetGoodUpdate() *Good {
	if m != nil {
		return m.GoodUpdate
	}
	return nil
}

func (m *BuyOneGoodResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BuyOneGoodResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetOneGoodRequest struct {
	GoodId               int32    `protobuf:"varint,1,opt,name=goodId,proto3" json:"goodId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneGoodRequest) Reset()         { *m = GetOneGoodRequest{} }
func (m *GetOneGoodRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneGoodRequest) ProtoMessage()    {}
func (*GetOneGoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{10}
}

func (m *GetOneGoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneGoodRequest.Unmarshal(m, b)
}
func (m *GetOneGoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneGoodRequest.Marshal(b, m, deterministic)
}
func (m *GetOneGoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneGoodRequest.Merge(m, src)
}
func (m *GetOneGoodRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneGoodRequest.Size(m)
}
func (m *GetOneGoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneGoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneGoodRequest proto.InternalMessageInfo

func (m *GetOneGoodRequest) GetGoodId() int32 {
	if m != nil {
		return m.GoodId
	}
	return 0
}

type GetOneGoodResponse struct {
	Good                 *Good    `protobuf:"bytes,1,opt,name=good,proto3" json:"good,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneGoodResponse) Reset()         { *m = GetOneGoodResponse{} }
func (m *GetOneGoodResponse) String() string { return proto.CompactTextString(m) }
func (*GetOneGoodResponse) ProtoMessage()    {}
func (*GetOneGoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{11}
}

func (m *GetOneGoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneGoodResponse.Unmarshal(m, b)
}
func (m *GetOneGoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneGoodResponse.Marshal(b, m, deterministic)
}
func (m *GetOneGoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneGoodResponse.Merge(m, src)
}
func (m *GetOneGoodResponse) XXX_Size() int {
	return xxx_messageInfo_GetOneGoodResponse.Size(m)
}
func (m *GetOneGoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneGoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneGoodResponse proto.InternalMessageInfo

func (m *GetOneGoodResponse) GetGood() *Good {
	if m != nil {
		return m.Good
	}
	return nil
}

type DelOneGoodRequest struct {
	GoodId               int32    `protobuf:"varint,1,opt,name=goodId,proto3" json:"goodId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOneGoodRequest) Reset()         { *m = DelOneGoodRequest{} }
func (m *DelOneGoodRequest) String() string { return proto.CompactTextString(m) }
func (*DelOneGoodRequest) ProtoMessage()    {}
func (*DelOneGoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{12}
}

func (m *DelOneGoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOneGoodRequest.Unmarshal(m, b)
}
func (m *DelOneGoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOneGoodRequest.Marshal(b, m, deterministic)
}
func (m *DelOneGoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOneGoodRequest.Merge(m, src)
}
func (m *DelOneGoodRequest) XXX_Size() int {
	return xxx_messageInfo_DelOneGoodRequest.Size(m)
}
func (m *DelOneGoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOneGoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelOneGoodRequest proto.InternalMessageInfo

func (m *DelOneGoodRequest) GetGoodId() int32 {
	if m != nil {
		return m.GoodId
	}
	return 0
}

type DelOneGoodResponse struct {
	Suncess              bool     `protobuf:"varint,1,opt,name=suncess,proto3" json:"suncess,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOneGoodResponse) Reset()         { *m = DelOneGoodResponse{} }
func (m *DelOneGoodResponse) String() string { return proto.CompactTextString(m) }
func (*DelOneGoodResponse) ProtoMessage()    {}
func (*DelOneGoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe66af8c4005172, []int{13}
}

func (m *DelOneGoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOneGoodResponse.Unmarshal(m, b)
}
func (m *DelOneGoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOneGoodResponse.Marshal(b, m, deterministic)
}
func (m *DelOneGoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOneGoodResponse.Merge(m, src)
}
func (m *DelOneGoodResponse) XXX_Size() int {
	return xxx_messageInfo_DelOneGoodResponse.Size(m)
}
func (m *DelOneGoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOneGoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelOneGoodResponse proto.InternalMessageInfo

func (m *DelOneGoodResponse) GetSuncess() bool {
	if m != nil {
		return m.Suncess
	}
	return false
}

func (m *DelOneGoodResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Good)(nil), "Good")
	proto.RegisterType((*GetGoodsListRequest)(nil), "GetGoodsListRequest")
	proto.RegisterType((*GetGoodsListResponse)(nil), "GetGoodsListResponse")
	proto.RegisterType((*GetGoodsListResponseGood)(nil), "GetGoodsListResponse.good")
	proto.RegisterType((*AddOneGoodRequest)(nil), "AddOneGoodRequest")
	proto.RegisterType((*AddOneGoodResponse)(nil), "AddOneGoodResponse")
	proto.RegisterType((*UpdateOneGoodRequest)(nil), "UpdateOneGoodRequest")
	proto.RegisterMapType((map[string]string)(nil), "UpdateOneGoodRequest.UpdateEntry")
	proto.RegisterType((*UpdateOneGoodResponse)(nil), "UpdateOneGoodResponse")
	proto.RegisterType((*BuyOneGoodRequest)(nil), "BuyOneGoodRequest")
	proto.RegisterType((*BuyOneGoodResponse)(nil), "BuyOneGoodResponse")
	proto.RegisterMapType((map[string]int32)(nil), "BuyOneGoodResponse.UserUpdateEntry")
	proto.RegisterType((*GetOneGoodRequest)(nil), "GetOneGoodRequest")
	proto.RegisterType((*GetOneGoodResponse)(nil), "GetOneGoodResponse")
	proto.RegisterType((*DelOneGoodRequest)(nil), "DelOneGoodRequest")
	proto.RegisterType((*DelOneGoodResponse)(nil), "DelOneGoodResponse")
}

func init() { proto.RegisterFile("shop/shop.proto", fileDescriptor_cbe66af8c4005172) }

var fileDescriptor_cbe66af8c4005172 = []byte{
	// 786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x9b, 0xa4, 0xe9, 0xda, 0x6b, 0xc7, 0xb6, 0x6b, 0x57, 0x99, 0xf0, 0x52, 0x82, 0x90,
	0x26, 0x81, 0x3c, 0x34, 0x1e, 0x60, 0x93, 0x26, 0x6d, 0x30, 0x34, 0x4d, 0x9a, 0x84, 0xc8, 0xe8,
	0x07, 0x28, 0x8d, 0xd5, 0x45, 0xb4, 0x49, 0x88, 0x9d, 0x49, 0x7d, 0xe5, 0x09, 0xbe, 0x0f, 0x12,
	0xe2, 0xab, 0xf1, 0x84, 0xec, 0xa4, 0xad, 0xdb, 0xa4, 0x1b, 0x02, 0x1e, 0x79, 0xa9, 0x7c, 0xe7,
	0x3b, 0xfb, 0xfc, 0xfb, 0xfb, 0x9c, 0xc2, 0x16, 0xbf, 0x8e, 0xe2, 0x7d, 0xf9, 0x43, 0xe3, 0x24,
	0x12, 0x91, 0xfb, 0x14, 0xaa, 0x17, 0x82, 0x4d, 0xf0, 0x1e, 0x98, 0x81, 0x4f, 0x8c, 0x9e, 0xb1,
	0x67, 0x7b, 0x66, 0xe0, 0x63, 0x07, 0xec, 0x61, 0x94, 0x86, 0x82, 0x98, 0xca, 0x95, 0x19, 0xee,
	0x77, 0x13, 0xaa, 0xe7, 0x51, 0xe4, 0x17, 0xc2, 0x11, 0xaa, 0xe1, 0x60, 0xc2, 0x54, 0x74, 0xc3,
	0x53, 0x63, 0xec, 0x42, 0x2d, 0x98, 0x8c, 0xfa, 0xc9, 0x98, 0x58, 0xca, 0x9b, 0x5b, 0xd8, 0x83,
	0xa6, 0xcf, 0xf8, 0x30, 0x09, 0x62, 0x11, 0x44, 0x21, 0xa9, 0xaa, 0x49, 0xdd, 0x85, 0x2d, 0x30,
	0x04, 0xb1, 0xd5, 0xe2, 0x86, 0x90, 0xa5, 0x88, 0x48, 0x0c, 0xc6, 0xa4, 0x96, 0x95, 0xa2, 0x0c,
	0xb9, 0x23, 0x8f, 0xc6, 0x3e, 0xd9, 0x50, 0x4e, 0x35, 0x96, 0x91, 0x71, 0x12, 0x0c, 0x19, 0xa9,
	0x67, 0x91, 0xca, 0x40, 0x07, 0xea, 0x7e, 0xc0, 0xb3, 0xd3, 0x34, 0xd4, 0xc4, 0xdc, 0x96, 0x19,
	0x5c, 0x0c, 0x04, 0x23, 0x90, 0x65, 0x28, 0x03, 0x5d, 0x68, 0x0d, 0xd3, 0x24, 0x61, 0xe1, 0x70,
	0xfa, 0x7e, 0x1a, 0x33, 0xd2, 0x54, 0x93, 0x4b, 0x3e, 0x7c, 0x00, 0x76, 0x20, 0xd8, 0x84, 0x93,
	0x56, 0xcf, 0xda, 0x6b, 0x1e, 0xd8, 0x54, 0x62, 0xf4, 0x32, 0x1f, 0x6e, 0x83, 0x25, 0x06, 0x23,
	0xb2, 0xd9, 0xb3, 0xf6, 0x1a, 0x9e, 0x1c, 0xba, 0x0c, 0xda, 0xe7, 0x4c, 0x48, 0x76, 0xfc, 0x32,
	0xe0, 0xc2, 0x63, 0x9f, 0x52, 0xc6, 0x85, 0x3c, 0x45, 0x3c, 0x18, 0xb1, 0x9c, 0xa4, 0x1a, 0xcb,
	0x9a, 0xc6, 0xc1, 0x24, 0x98, 0xa3, 0x57, 0x46, 0xc6, 0xc4, 0x9a, 0x31, 0xe9, 0x42, 0x2d, 0xe5,
	0x2c, 0xb9, 0xf0, 0x15, 0x3e, 0xdb, 0xcb, 0x2d, 0xf7, 0xb3, 0x05, 0x9d, 0xe5, 0x7d, 0x78, 0x1c,
	0x85, 0x9c, 0xe1, 0x33, 0xb0, 0x95, 0x93, 0x18, 0xaa, 0x5c, 0x87, 0x96, 0x45, 0xd1, 0x51, 0x14,
	0xf9, 0x5e, 0x16, 0xe8, 0x48, 0xad, 0x47, 0xff, 0xb5, 0xfe, 0x03, 0xad, 0xbf, 0x99, 0xb0, 0x73,
	0xea, 0xfb, 0x6f, 0x43, 0x26, 0x49, 0x6a, 0x52, 0x2b, 0x6c, 0x46, 0x29, 0x36, 0xf3, 0x36, 0x6c,
	0xd6, 0x1a, 0x6c, 0xd5, 0x02, 0x36, 0xbb, 0x0c, 0x5b, 0xad, 0x0c, 0xdb, 0xc6, 0x3a, 0x6c, 0xf5,
	0x75, 0xd8, 0x1a, 0xb7, 0x61, 0x83, 0xdb, 0xb0, 0x35, 0xd7, 0x63, 0x6b, 0x2d, 0xb0, 0x51, 0x40,
	0x9d, 0x5a, 0x7e, 0x71, 0x09, 0x6c, 0xf0, 0x74, 0x38, 0x64, 0x9c, 0x2b, 0x72, 0x75, 0x6f, 0x66,
	0xba, 0x3f, 0x0c, 0xe8, 0xf4, 0x63, 0x7f, 0x20, 0xd8, 0x0a, 0xe9, 0xd5, 0x0b, 0x7b, 0x08, 0xb5,
	0x54, 0xc5, 0x11, 0x53, 0x15, 0xf2, 0x90, 0x96, 0xa5, 0xe5, 0xce, 0x37, 0xa1, 0x48, 0xa6, 0x5e,
	0x9e, 0xb0, 0x38, 0x82, 0x55, 0x3c, 0x82, 0x73, 0x08, 0x4d, 0x2d, 0x47, 0x9e, 0xe8, 0x23, 0x9b,
	0xe6, 0xfa, 0xca, 0xa1, 0x44, 0x77, 0x33, 0x18, 0xa7, 0xb3, 0x56, 0xc9, 0x8c, 0x23, 0xf3, 0xa5,
	0xe1, 0x5e, 0xc2, 0xee, 0x4a, 0x0d, 0xf9, 0x71, 0xef, 0x67, 0x4d, 0xa7, 0x56, 0x91, 0xfb, 0xa9,
	0xc9, 0xac, 0x0f, 0x35, 0x12, 0xe6, 0x32, 0x89, 0x77, 0xb0, 0xf3, 0x2a, 0x9d, 0xde, 0x41, 0xa1,
	0xf4, 0x45, 0xd7, 0x1e, 0x12, 0x6b, 0xe9, 0x21, 0xf9, 0x62, 0x02, 0xea, 0x6b, 0xe6, 0xe5, 0xcd,
	0x79, 0x18, 0x25, 0x92, 0xbe, 0x06, 0x90, 0xd9, 0x7d, 0x9d, 0xf5, 0x23, 0x5a, 0x5c, 0x85, 0xf6,
	0xe7, 0x51, 0x19, 0x6d, 0x2d, 0x0d, 0x1f, 0x03, 0xc8, 0xd3, 0xe6, 0x8b, 0x58, 0x3a, 0x06, 0x6d,
	0x42, 0x87, 0x51, 0x5d, 0x82, 0x21, 0x65, 0x98, 0xf0, 0x91, 0xea, 0x84, 0x86, 0x27, 0x87, 0xce,
	0x31, 0x6c, 0xad, 0xec, 0x78, 0x97, 0x56, 0xb6, 0xae, 0xd5, 0x13, 0xd8, 0x39, 0x67, 0x62, 0x85,
	0x6e, 0x17, 0x6a, 0xb2, 0x9a, 0x8b, 0x19, 0xe1, 0xdc, 0x72, 0xf7, 0x01, 0xf5, 0xe0, 0x3b, 0x55,
	0x95, 0xab, 0x9f, 0xb1, 0xf1, 0x6f, 0xae, 0x7e, 0x02, 0xa8, 0x07, 0xeb, 0x2d, 0x12, 0x2e, 0xb7,
	0x48, 0xa8, 0xb3, 0x30, 0xe7, 0x2c, 0x0e, 0xbe, 0x1a, 0xb0, 0x75, 0x75, 0x1d, 0xc5, 0x12, 0xc8,
	0x15, 0x4b, 0x6e, 0x64, 0xf7, 0x1f, 0x43, 0x4b, 0xff, 0x1a, 0x60, 0x87, 0x96, 0x7c, 0xaa, 0x9c,
	0xdd, 0xd2, 0x4f, 0x86, 0x5b, 0xc1, 0x17, 0x00, 0x0b, 0x8d, 0x11, 0x69, 0xe1, 0x2a, 0x3a, 0xed,
	0x92, 0x4b, 0xe0, 0x56, 0x0e, 0x7e, 0x9a, 0xb0, 0x2d, 0x6b, 0x39, 0xf5, 0x27, 0x41, 0xf8, 0xef,
	0x8a, 0x59, 0x3c, 0x22, 0x88, 0xb4, 0xf0, 0x0e, 0x3b, 0x6d, 0x5a, 0x7c, 0x65, 0xb2, 0xc4, 0x85,
	0x70, 0x88, 0xb4, 0x20, 0xb9, 0xd3, 0xa6, 0x45, 0x65, 0xdd, 0x0a, 0x9e, 0xc0, 0xe6, 0x52, 0x2b,
	0xe3, 0x6e, 0xe9, 0xf3, 0xe2, 0x74, 0x69, 0x69, 0xc7, 0xff, 0x05, 0x40, 0x3c, 0x82, 0xcd, 0x33,
	0x36, 0x66, 0x8b, 0xad, 0x91, 0x16, 0xee, 0x92, 0xd3, 0xa6, 0xc5, 0x2b, 0xe3, 0x56, 0x3e, 0xd4,
	0xd4, 0xff, 0xbf, 0xe7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x50, 0x00, 0x6f, 0x15, 0x12, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShopUserServiceClient is the client API for ShopUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopUserServiceClient interface {
	// 获取商城货物列表
	GetGoodsList(ctx context.Context, in *GetGoodsListRequest, opts ...grpc.CallOption) (*GetGoodsListResponse, error)
	// 购买单个物品(可以调节数量)
	BuyOneGood(ctx context.Context, in *BuyOneGoodRequest, opts ...grpc.CallOption) (*BuyOneGoodResponse, error)
}

type shopUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewShopUserServiceClient(cc *grpc.ClientConn) ShopUserServiceClient {
	return &shopUserServiceClient{cc}
}

func (c *shopUserServiceClient) GetGoodsList(ctx context.Context, in *GetGoodsListRequest, opts ...grpc.CallOption) (*GetGoodsListResponse, error) {
	out := new(GetGoodsListResponse)
	err := c.cc.Invoke(ctx, "/ShopUserService/GetGoodsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopUserServiceClient) BuyOneGood(ctx context.Context, in *BuyOneGoodRequest, opts ...grpc.CallOption) (*BuyOneGoodResponse, error) {
	out := new(BuyOneGoodResponse)
	err := c.cc.Invoke(ctx, "/ShopUserService/BuyOneGood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopUserServiceServer is the server API for ShopUserService service.
type ShopUserServiceServer interface {
	// 获取商城货物列表
	GetGoodsList(context.Context, *GetGoodsListRequest) (*GetGoodsListResponse, error)
	// 购买单个物品(可以调节数量)
	BuyOneGood(context.Context, *BuyOneGoodRequest) (*BuyOneGoodResponse, error)
}

func RegisterShopUserServiceServer(s *grpc.Server, srv ShopUserServiceServer) {
	s.RegisterService(&_ShopUserService_serviceDesc, srv)
}

func _ShopUserService_GetGoodsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopUserServiceServer).GetGoodsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopUserService/GetGoodsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopUserServiceServer).GetGoodsList(ctx, req.(*GetGoodsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopUserService_BuyOneGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyOneGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopUserServiceServer).BuyOneGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopUserService/BuyOneGood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopUserServiceServer).BuyOneGood(ctx, req.(*BuyOneGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShopUserService",
	HandlerType: (*ShopUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoodsList",
			Handler:    _ShopUserService_GetGoodsList_Handler,
		},
		{
			MethodName: "BuyOneGood",
			Handler:    _ShopUserService_BuyOneGood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/shop.proto",
}

// ShopAdminServiceClient is the client API for ShopAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopAdminServiceClient interface {
	// 获取商城货物列表
	GetGoodsList(ctx context.Context, in *GetGoodsListRequest, opts ...grpc.CallOption) (*GetGoodsListResponse, error)
	// 新增一个货物到商城
	AddOneGood(ctx context.Context, in *AddOneGoodRequest, opts ...grpc.CallOption) (*AddOneGoodResponse, error)
	// 得到一个物品的详细信息
	GetOneGood(ctx context.Context, in *GetOneGoodRequest, opts ...grpc.CallOption) (*GetOneGoodResponse, error)
	// 更新一个
	UpdateOneGood(ctx context.Context, in *UpdateOneGoodRequest, opts ...grpc.CallOption) (*UpdateOneGoodResponse, error)
	// 购买单个物品(可以调节数量)
	BuyOneGood(ctx context.Context, in *BuyOneGoodRequest, opts ...grpc.CallOption) (*BuyOneGoodResponse, error)
	// 删除一个物品
	DeleteOneGood(ctx context.Context, in *DelOneGoodRequest, opts ...grpc.CallOption) (*DelOneGoodResponse, error)
}

type shopAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewShopAdminServiceClient(cc *grpc.ClientConn) ShopAdminServiceClient {
	return &shopAdminServiceClient{cc}
}

func (c *shopAdminServiceClient) GetGoodsList(ctx context.Context, in *GetGoodsListRequest, opts ...grpc.CallOption) (*GetGoodsListResponse, error) {
	out := new(GetGoodsListResponse)
	err := c.cc.Invoke(ctx, "/ShopAdminService/GetGoodsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopAdminServiceClient) AddOneGood(ctx context.Context, in *AddOneGoodRequest, opts ...grpc.CallOption) (*AddOneGoodResponse, error) {
	out := new(AddOneGoodResponse)
	err := c.cc.Invoke(ctx, "/ShopAdminService/AddOneGood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopAdminServiceClient) GetOneGood(ctx context.Context, in *GetOneGoodRequest, opts ...grpc.CallOption) (*GetOneGoodResponse, error) {
	out := new(GetOneGoodResponse)
	err := c.cc.Invoke(ctx, "/ShopAdminService/GetOneGood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopAdminServiceClient) UpdateOneGood(ctx context.Context, in *UpdateOneGoodRequest, opts ...grpc.CallOption) (*UpdateOneGoodResponse, error) {
	out := new(UpdateOneGoodResponse)
	err := c.cc.Invoke(ctx, "/ShopAdminService/UpdateOneGood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopAdminServiceClient) BuyOneGood(ctx context.Context, in *BuyOneGoodRequest, opts ...grpc.CallOption) (*BuyOneGoodResponse, error) {
	out := new(BuyOneGoodResponse)
	err := c.cc.Invoke(ctx, "/ShopAdminService/BuyOneGood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopAdminServiceClient) DeleteOneGood(ctx context.Context, in *DelOneGoodRequest, opts ...grpc.CallOption) (*DelOneGoodResponse, error) {
	out := new(DelOneGoodResponse)
	err := c.cc.Invoke(ctx, "/ShopAdminService/DeleteOneGood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopAdminServiceServer is the server API for ShopAdminService service.
type ShopAdminServiceServer interface {
	// 获取商城货物列表
	GetGoodsList(context.Context, *GetGoodsListRequest) (*GetGoodsListResponse, error)
	// 新增一个货物到商城
	AddOneGood(context.Context, *AddOneGoodRequest) (*AddOneGoodResponse, error)
	// 得到一个物品的详细信息
	GetOneGood(context.Context, *GetOneGoodRequest) (*GetOneGoodResponse, error)
	// 更新一个
	UpdateOneGood(context.Context, *UpdateOneGoodRequest) (*UpdateOneGoodResponse, error)
	// 购买单个物品(可以调节数量)
	BuyOneGood(context.Context, *BuyOneGoodRequest) (*BuyOneGoodResponse, error)
	// 删除一个物品
	DeleteOneGood(context.Context, *DelOneGoodRequest) (*DelOneGoodResponse, error)
}

func RegisterShopAdminServiceServer(s *grpc.Server, srv ShopAdminServiceServer) {
	s.RegisterService(&_ShopAdminService_serviceDesc, srv)
}

func _ShopAdminService_GetGoodsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopAdminServiceServer).GetGoodsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopAdminService/GetGoodsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopAdminServiceServer).GetGoodsList(ctx, req.(*GetGoodsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopAdminService_AddOneGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOneGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopAdminServiceServer).AddOneGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopAdminService/AddOneGood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopAdminServiceServer).AddOneGood(ctx, req.(*AddOneGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopAdminService_GetOneGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopAdminServiceServer).GetOneGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopAdminService/GetOneGood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopAdminServiceServer).GetOneGood(ctx, req.(*GetOneGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopAdminService_UpdateOneGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOneGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopAdminServiceServer).UpdateOneGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopAdminService/UpdateOneGood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopAdminServiceServer).UpdateOneGood(ctx, req.(*UpdateOneGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopAdminService_BuyOneGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyOneGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopAdminServiceServer).BuyOneGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopAdminService/BuyOneGood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopAdminServiceServer).BuyOneGood(ctx, req.(*BuyOneGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopAdminService_DeleteOneGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOneGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopAdminServiceServer).DeleteOneGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopAdminService/DeleteOneGood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopAdminServiceServer).DeleteOneGood(ctx, req.(*DelOneGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShopAdminService",
	HandlerType: (*ShopAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoodsList",
			Handler:    _ShopAdminService_GetGoodsList_Handler,
		},
		{
			MethodName: "AddOneGood",
			Handler:    _ShopAdminService_AddOneGood_Handler,
		},
		{
			MethodName: "GetOneGood",
			Handler:    _ShopAdminService_GetOneGood_Handler,
		},
		{
			MethodName: "UpdateOneGood",
			Handler:    _ShopAdminService_UpdateOneGood_Handler,
		},
		{
			MethodName: "BuyOneGood",
			Handler:    _ShopAdminService_BuyOneGood_Handler,
		},
		{
			MethodName: "DeleteOneGood",
			Handler:    _ShopAdminService_DeleteOneGood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/shop.proto",
}
