// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: history/history.proto

/*
Package history is a generated protocol buffer package.

It is generated from these files:
	history/history.proto

It has these top-level messages:
	GetUserHistoryRequest
	GetUserHistoryResponse
*/
package history

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/cardsGame/qpProto/friendRoom"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for History service

type HistoryService interface {
	GetUserHistroy(ctx context.Context, in *GetUserHistoryRequest, opts ...client.CallOption) (*GetUserHistoryResponse, error)
}

type historyService struct {
	c    client.Client
	name string
}

func NewHistoryService(name string, c client.Client) HistoryService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "history"
	}
	return &historyService{
		c:    c,
		name: name,
	}
}

func (c *historyService) GetUserHistroy(ctx context.Context, in *GetUserHistoryRequest, opts ...client.CallOption) (*GetUserHistoryResponse, error) {
	req := c.c.NewRequest(c.name, "History.GetUserHistroy", in)
	out := new(GetUserHistoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for History service

type HistoryHandler interface {
	GetUserHistroy(context.Context, *GetUserHistoryRequest, *GetUserHistoryResponse) error
}

func RegisterHistoryHandler(s server.Server, hdlr HistoryHandler, opts ...server.HandlerOption) error {
	type history interface {
		GetUserHistroy(ctx context.Context, in *GetUserHistoryRequest, out *GetUserHistoryResponse) error
	}
	type History struct {
		history
	}
	h := &historyHandler{hdlr}
	return s.Handle(s.NewHandler(&History{h}, opts...))
}

type historyHandler struct {
	HistoryHandler
}

func (h *historyHandler) GetUserHistroy(ctx context.Context, in *GetUserHistoryRequest, out *GetUserHistoryResponse) error {
	return h.HistoryHandler.GetUserHistroy(ctx, in, out)
}
