// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notice.proto

package notice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoticeType int32

const (
	NoticeType_lvse  NoticeType = 0
	NoticeType_daili NoticeType = 1
)

var NoticeType_name = map[int32]string{
	0: "lvse",
	1: "daili",
}

var NoticeType_value = map[string]int32{
	"lvse":  0,
	"daili": 1,
}

func (x NoticeType) String() string {
	return proto.EnumName(NoticeType_name, int32(x))
}

func (NoticeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{0}
}

type NoticeData struct {
	Type                 NoticeType `protobuf:"varint,1,opt,name=type,proto3,enum=NoticeType" json:"type,omitempty"`
	Content              string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NoticeData) Reset()         { *m = NoticeData{} }
func (m *NoticeData) String() string { return proto.CompactTextString(m) }
func (*NoticeData) ProtoMessage()    {}
func (*NoticeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{0}
}

func (m *NoticeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeData.Unmarshal(m, b)
}
func (m *NoticeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeData.Marshal(b, m, deterministic)
}
func (m *NoticeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeData.Merge(m, src)
}
func (m *NoticeData) XXX_Size() int {
	return xxx_messageInfo_NoticeData.Size(m)
}
func (m *NoticeData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeData.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeData proto.InternalMessageInfo

func (m *NoticeData) GetType() NoticeType {
	if m != nil {
		return m.Type
	}
	return NoticeType_lvse
}

func (m *NoticeData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateNoticeRequest struct {
	Type                 NoticeType `protobuf:"varint,1,opt,name=type,proto3,enum=NoticeType" json:"type,omitempty"`
	Content              string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateNoticeRequest) Reset()         { *m = CreateNoticeRequest{} }
func (m *CreateNoticeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNoticeRequest) ProtoMessage()    {}
func (*CreateNoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{1}
}

func (m *CreateNoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNoticeRequest.Unmarshal(m, b)
}
func (m *CreateNoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNoticeRequest.Marshal(b, m, deterministic)
}
func (m *CreateNoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNoticeRequest.Merge(m, src)
}
func (m *CreateNoticeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNoticeRequest.Size(m)
}
func (m *CreateNoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNoticeRequest proto.InternalMessageInfo

func (m *CreateNoticeRequest) GetType() NoticeType {
	if m != nil {
		return m.Type
	}
	return NoticeType_lvse
}

func (m *CreateNoticeRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DeleteNoticeRequest struct {
	Type                 NoticeType `protobuf:"varint,1,opt,name=type,proto3,enum=NoticeType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteNoticeRequest) Reset()         { *m = DeleteNoticeRequest{} }
func (m *DeleteNoticeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNoticeRequest) ProtoMessage()    {}
func (*DeleteNoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{2}
}

func (m *DeleteNoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNoticeRequest.Unmarshal(m, b)
}
func (m *DeleteNoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNoticeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNoticeRequest.Merge(m, src)
}
func (m *DeleteNoticeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNoticeRequest.Size(m)
}
func (m *DeleteNoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNoticeRequest proto.InternalMessageInfo

func (m *DeleteNoticeRequest) GetType() NoticeType {
	if m != nil {
		return m.Type
	}
	return NoticeType_lvse
}

type UpdateNoticeRequest struct {
	Type                 NoticeType `protobuf:"varint,1,opt,name=type,proto3,enum=NoticeType" json:"type,omitempty"`
	Content              string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateNoticeRequest) Reset()         { *m = UpdateNoticeRequest{} }
func (m *UpdateNoticeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNoticeRequest) ProtoMessage()    {}
func (*UpdateNoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{3}
}

func (m *UpdateNoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNoticeRequest.Unmarshal(m, b)
}
func (m *UpdateNoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNoticeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNoticeRequest.Merge(m, src)
}
func (m *UpdateNoticeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNoticeRequest.Size(m)
}
func (m *UpdateNoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNoticeRequest proto.InternalMessageInfo

func (m *UpdateNoticeRequest) GetType() NoticeType {
	if m != nil {
		return m.Type
	}
	return NoticeType_lvse
}

func (m *UpdateNoticeRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetNoticeListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNoticeListRequest) Reset()         { *m = GetNoticeListRequest{} }
func (m *GetNoticeListRequest) String() string { return proto.CompactTextString(m) }
func (*GetNoticeListRequest) ProtoMessage()    {}
func (*GetNoticeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{4}
}

func (m *GetNoticeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoticeListRequest.Unmarshal(m, b)
}
func (m *GetNoticeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoticeListRequest.Marshal(b, m, deterministic)
}
func (m *GetNoticeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoticeListRequest.Merge(m, src)
}
func (m *GetNoticeListRequest) XXX_Size() int {
	return xxx_messageInfo_GetNoticeListRequest.Size(m)
}
func (m *GetNoticeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoticeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoticeListRequest proto.InternalMessageInfo

type GetNoticeListResponse struct {
	Notices              []*NoticeData `protobuf:"bytes,1,rep,name=notices,proto3" json:"notices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetNoticeListResponse) Reset()         { *m = GetNoticeListResponse{} }
func (m *GetNoticeListResponse) String() string { return proto.CompactTextString(m) }
func (*GetNoticeListResponse) ProtoMessage()    {}
func (*GetNoticeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_642492014393dbdb, []int{5}
}

func (m *GetNoticeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoticeListResponse.Unmarshal(m, b)
}
func (m *GetNoticeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoticeListResponse.Marshal(b, m, deterministic)
}
func (m *GetNoticeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoticeListResponse.Merge(m, src)
}
func (m *GetNoticeListResponse) XXX_Size() int {
	return xxx_messageInfo_GetNoticeListResponse.Size(m)
}
func (m *GetNoticeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoticeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoticeListResponse proto.InternalMessageInfo

func (m *GetNoticeListResponse) GetNotices() []*NoticeData {
	if m != nil {
		return m.Notices
	}
	return nil
}

func init() {
	proto.RegisterEnum("NoticeType", NoticeType_name, NoticeType_value)
	proto.RegisterType((*NoticeData)(nil), "NoticeData")
	proto.RegisterType((*CreateNoticeRequest)(nil), "CreateNoticeRequest")
	proto.RegisterType((*DeleteNoticeRequest)(nil), "DeleteNoticeRequest")
	proto.RegisterType((*UpdateNoticeRequest)(nil), "UpdateNoticeRequest")
	proto.RegisterType((*GetNoticeListRequest)(nil), "GetNoticeListRequest")
	proto.RegisterType((*GetNoticeListResponse)(nil), "GetNoticeListResponse")
}

func init() { proto.RegisterFile("notice.proto", fileDescriptor_642492014393dbdb) }

var fileDescriptor_642492014393dbdb = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd2, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0xe0, 0xac, 0xd6, 0xd6, 0x4e, 0xab, 0x94, 0x69, 0x5a, 0x42, 0x2f, 0xc6, 0x05, 0x21,
	0x78, 0xd8, 0x43, 0x0b, 0x1e, 0x45, 0xb0, 0xd0, 0x8b, 0x88, 0x04, 0x7d, 0x80, 0xd8, 0xce, 0x21,
	0x10, 0xb2, 0x6b, 0x77, 0x14, 0xfa, 0xc8, 0xbe, 0x85, 0x24, 0x6b, 0x24, 0x96, 0xbd, 0x88, 0x3d,
	0x4e, 0x26, 0xff, 0xcc, 0xf0, 0xb1, 0x30, 0x2c, 0x35, 0xe7, 0x6b, 0x52, 0x66, 0xab, 0x59, 0xcb,
	0x15, 0xc0, 0x63, 0x5d, 0x2f, 0x33, 0xce, 0xf0, 0x02, 0x3a, 0xbc, 0x33, 0x14, 0x89, 0x58, 0x24,
	0xe7, 0xf3, 0x81, 0x72, 0xad, 0xe7, 0x9d, 0xa1, 0xb4, 0x6e, 0x60, 0x04, 0xbd, 0xb5, 0x2e, 0x99,
	0x4a, 0x8e, 0x8e, 0x62, 0x91, 0xf4, 0xd3, 0xa6, 0x94, 0x4f, 0x30, 0xbe, 0xdf, 0x52, 0xc6, 0xe4,
	0x32, 0x29, 0xbd, 0xbd, 0x93, 0xe5, 0xff, 0x4c, 0xbc, 0x81, 0xf1, 0x92, 0x0a, 0xfa, 0xeb, 0xc4,
	0xea, 0x92, 0x17, 0xb3, 0x39, 0xe4, 0x25, 0x53, 0x08, 0x57, 0xc4, 0x2e, 0xf0, 0x90, 0x5b, 0xfe,
	0x1e, 0x29, 0x6f, 0x61, 0xb2, 0xf7, 0xdd, 0x1a, 0x5d, 0x5a, 0xc2, 0x2b, 0xe8, 0x39, 0x65, 0x1b,
	0x89, 0xf8, 0x38, 0x19, 0xfc, 0xac, 0xab, 0x94, 0xd3, 0xa6, 0x77, 0x7d, 0xd9, 0xe0, 0x57, 0x57,
	0xe0, 0x29, 0x74, 0x8a, 0x0f, 0x4b, 0xa3, 0x00, 0xfb, 0x70, 0xb2, 0xc9, 0xf2, 0x22, 0x1f, 0x89,
	0xf9, 0xa7, 0x80, 0xae, 0xfb, 0x07, 0x17, 0x30, 0x6c, 0x0b, 0x63, 0xa8, 0x3c, 0xe0, 0xb3, 0xf6,
	0x26, 0x19, 0x54, 0xa1, 0x36, 0x22, 0x86, 0xca, 0x63, 0xea, 0x09, 0xb5, 0x05, 0x31, 0x54, 0x1e,
	0xd0, 0xfd, 0xd0, 0x1d, 0x9c, 0xfd, 0xc2, 0xc0, 0x89, 0xf2, 0xa1, 0xcd, 0xa6, 0xca, 0x6b, 0x26,
	0x83, 0xd7, 0x6e, 0xfd, 0x24, 0x17, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0xec, 0x0b, 0x50,
	0xa2, 0x02, 0x00, 0x00,
}
