// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/agent.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeAvaliableRequest_Types int32

const (
	ChangeAvaliableRequest_Unknonwn  ChangeAvaliableRequest_Types = 0
	ChangeAvaliableRequest_Blocked   ChangeAvaliableRequest_Types = 1
	ChangeAvaliableRequest_Avaliable ChangeAvaliableRequest_Types = 2
)

var ChangeAvaliableRequest_Types_name = map[int32]string{
	0: "Unknonwn",
	1: "Blocked",
	2: "Avaliable",
}
var ChangeAvaliableRequest_Types_value = map[string]int32{
	"Unknonwn":  0,
	"Blocked":   1,
	"Avaliable": 2,
}

func (x ChangeAvaliableRequest_Types) String() string {
	return proto.EnumName(ChangeAvaliableRequest_Types_name, int32(x))
}
func (ChangeAvaliableRequest_Types) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{5, 0}
}

// Request of Creating an agent.
// Prerequisite: User Must be already Created in Game Server
type CreateAgentRequest struct {
	NickName             string   `protobuf:"bytes,1,opt,name=NickName,proto3" json:"NickName,omitempty"`
	WxAccount            string   `protobuf:"bytes,2,opt,name=WxAccount,proto3" json:"WxAccount,omitempty"`
	UserID               int32    `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	HeadImg              string   `protobuf:"bytes,5,opt,name=HeadImg,proto3" json:"HeadImg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentRequest) Reset()         { *m = CreateAgentRequest{} }
func (m *CreateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgentRequest) ProtoMessage()    {}
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{0}
}
func (m *CreateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentRequest.Unmarshal(m, b)
}
func (m *CreateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentRequest.Merge(dst, src)
}
func (m *CreateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgentRequest.Size(m)
}
func (m *CreateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentRequest proto.InternalMessageInfo

func (m *CreateAgentRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CreateAgentRequest) GetWxAccount() string {
	if m != nil {
		return m.WxAccount
	}
	return ""
}

func (m *CreateAgentRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateAgentRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateAgentRequest) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

// Request of getting an angent's personal info.
type GetInfoByUserIDRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoByUserIDRequest) Reset()         { *m = GetInfoByUserIDRequest{} }
func (m *GetInfoByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoByUserIDRequest) ProtoMessage()    {}
func (*GetInfoByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{1}
}
func (m *GetInfoByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoByUserIDRequest.Unmarshal(m, b)
}
func (m *GetInfoByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoByUserIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetInfoByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoByUserIDRequest.Merge(dst, src)
}
func (m *GetInfoByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoByUserIDRequest.Size(m)
}
func (m *GetInfoByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoByUserIDRequest proto.InternalMessageInfo

func (m *GetInfoByUserIDRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// Request of getting an angent's personal info.
type GetInfoByIDRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoByIDRequest) Reset()         { *m = GetInfoByIDRequest{} }
func (m *GetInfoByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoByIDRequest) ProtoMessage()    {}
func (*GetInfoByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{2}
}
func (m *GetInfoByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoByIDRequest.Unmarshal(m, b)
}
func (m *GetInfoByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetInfoByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoByIDRequest.Merge(dst, src)
}
func (m *GetInfoByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoByIDRequest.Size(m)
}
func (m *GetInfoByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoByIDRequest proto.InternalMessageInfo

func (m *GetInfoByIDRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetAgentListRequest struct {
	Order                string   `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentListRequest) Reset()         { *m = GetAgentListRequest{} }
func (m *GetAgentListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentListRequest) ProtoMessage()    {}
func (*GetAgentListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{3}
}
func (m *GetAgentListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentListRequest.Unmarshal(m, b)
}
func (m *GetAgentListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentListRequest.Marshal(b, m, deterministic)
}
func (dst *GetAgentListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentListRequest.Merge(dst, src)
}
func (m *GetAgentListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentListRequest.Size(m)
}
func (m *GetAgentListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentListRequest proto.InternalMessageInfo

func (m *GetAgentListRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *GetAgentListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAgentListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetAgentListResponse struct {
	List                 []*Agent `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentListResponse) Reset()         { *m = GetAgentListResponse{} }
func (m *GetAgentListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAgentListResponse) ProtoMessage()    {}
func (*GetAgentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{4}
}
func (m *GetAgentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentListResponse.Unmarshal(m, b)
}
func (m *GetAgentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentListResponse.Marshal(b, m, deterministic)
}
func (dst *GetAgentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentListResponse.Merge(dst, src)
}
func (m *GetAgentListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAgentListResponse.Size(m)
}
func (m *GetAgentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentListResponse proto.InternalMessageInfo

func (m *GetAgentListResponse) GetList() []*Agent {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetAgentListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ChangeAvaliableRequest struct {
	AgentID              int32                        `protobuf:"varint,1,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
	Type                 ChangeAvaliableRequest_Types `protobuf:"varint,2,opt,name=Type,proto3,enum=agent.ChangeAvaliableRequest_Types" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ChangeAvaliableRequest) Reset()         { *m = ChangeAvaliableRequest{} }
func (m *ChangeAvaliableRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeAvaliableRequest) ProtoMessage()    {}
func (*ChangeAvaliableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{5}
}
func (m *ChangeAvaliableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAvaliableRequest.Unmarshal(m, b)
}
func (m *ChangeAvaliableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAvaliableRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeAvaliableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAvaliableRequest.Merge(dst, src)
}
func (m *ChangeAvaliableRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeAvaliableRequest.Size(m)
}
func (m *ChangeAvaliableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAvaliableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAvaliableRequest proto.InternalMessageInfo

func (m *ChangeAvaliableRequest) GetAgentID() int32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

func (m *ChangeAvaliableRequest) GetType() ChangeAvaliableRequest_Types {
	if m != nil {
		return m.Type
	}
	return ChangeAvaliableRequest_Unknonwn
}

type ChangeAvaliableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAvaliableResponse) Reset()         { *m = ChangeAvaliableResponse{} }
func (m *ChangeAvaliableResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeAvaliableResponse) ProtoMessage()    {}
func (*ChangeAvaliableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{6}
}
func (m *ChangeAvaliableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAvaliableResponse.Unmarshal(m, b)
}
func (m *ChangeAvaliableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAvaliableResponse.Marshal(b, m, deterministic)
}
func (dst *ChangeAvaliableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAvaliableResponse.Merge(dst, src)
}
func (m *ChangeAvaliableResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeAvaliableResponse.Size(m)
}
func (m *ChangeAvaliableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAvaliableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAvaliableResponse proto.InternalMessageInfo

func (m *ChangeAvaliableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Information of single agent
type Agent struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	HeadImg              string   `protobuf:"bytes,4,opt,name=HeadImg,proto3" json:"HeadImg,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Avaliable            bool     `protobuf:"varint,6,opt,name=Avaliable,proto3" json:"Avaliable,omitempty"`
	Balance              float64  `protobuf:"fixed64,7,opt,name=Balance,proto3" json:"Balance,omitempty"`
	WxAccount            string   `protobuf:"bytes,8,opt,name=WxAccount,proto3" json:"WxAccount,omitempty"`
	Scode                string   `protobuf:"bytes,9,opt,name=Scode,proto3" json:"Scode,omitempty"`
	AgentLevel           int32    `protobuf:"varint,10,opt,name=AgentLevel,proto3" json:"AgentLevel,omitempty"`
	WithdrawPassword     string   `protobuf:"bytes,11,opt,name=WithdrawPassword,proto3" json:"WithdrawPassword,omitempty"`
	PayPassword          string   `protobuf:"bytes,12,opt,name=PayPassword,proto3" json:"PayPassword,omitempty"`
	UserID               int32    `protobuf:"varint,13,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Father               *Agent   `protobuf:"bytes,14,opt,name=Father,proto3" json:"Father,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,16,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DelatedAt            string   `protobuf:"bytes,17,opt,name=DelatedAt,proto3" json:"DelatedAt,omitempty"`
	Link                 *Link    `protobuf:"bytes,18,opt,name=Link,proto3" json:"Link,omitempty"`
	TotalSon             int32    `protobuf:"varint,19,opt,name=TotalSon,proto3" json:"TotalSon,omitempty"`
	TotalIncome          float64  `protobuf:"fixed64,20,opt,name=TotalIncome,proto3" json:"TotalIncome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{7}
}
func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (dst *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(dst, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Agent) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *Agent) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Agent) GetAvaliable() bool {
	if m != nil {
		return m.Avaliable
	}
	return false
}

func (m *Agent) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Agent) GetWxAccount() string {
	if m != nil {
		return m.WxAccount
	}
	return ""
}

func (m *Agent) GetScode() string {
	if m != nil {
		return m.Scode
	}
	return ""
}

func (m *Agent) GetAgentLevel() int32 {
	if m != nil {
		return m.AgentLevel
	}
	return 0
}

func (m *Agent) GetWithdrawPassword() string {
	if m != nil {
		return m.WithdrawPassword
	}
	return ""
}

func (m *Agent) GetPayPassword() string {
	if m != nil {
		return m.PayPassword
	}
	return ""
}

func (m *Agent) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Agent) GetFather() *Agent {
	if m != nil {
		return m.Father
	}
	return nil
}

func (m *Agent) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Agent) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Agent) GetDelatedAt() string {
	if m != nil {
		return m.DelatedAt
	}
	return ""
}

func (m *Agent) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *Agent) GetTotalSon() int32 {
	if m != nil {
		return m.TotalSon
	}
	return 0
}

func (m *Agent) GetTotalIncome() float64 {
	if m != nil {
		return m.TotalIncome
	}
	return 0
}

type Link struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FatherID             int32    `protobuf:"varint,2,opt,name=FatherID,proto3" json:"FatherID,omitempty"`
	GrandFatherID        int32    `protobuf:"varint,3,opt,name=GrandFatherID,proto3" json:"GrandFatherID,omitempty"`
	FatherBindAt         string   `protobuf:"bytes,4,opt,name=FatherBindAt,proto3" json:"FatherBindAt,omitempty"`
	GrandFatherBindAt    string   `protobuf:"bytes,5,opt,name=GrandFatherBindAt,proto3" json:"GrandFatherBindAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeleatedAt           string   `protobuf:"bytes,8,opt,name=DeleatedAt,proto3" json:"DeleatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_312d7b8de97dc412, []int{8}
}
func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (dst *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(dst, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Link) GetFatherID() int32 {
	if m != nil {
		return m.FatherID
	}
	return 0
}

func (m *Link) GetGrandFatherID() int32 {
	if m != nil {
		return m.GrandFatherID
	}
	return 0
}

func (m *Link) GetFatherBindAt() string {
	if m != nil {
		return m.FatherBindAt
	}
	return ""
}

func (m *Link) GetGrandFatherBindAt() string {
	if m != nil {
		return m.GrandFatherBindAt
	}
	return ""
}

func (m *Link) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Link) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Link) GetDeleatedAt() string {
	if m != nil {
		return m.DeleatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAgentRequest)(nil), "agent.CreateAgentRequest")
	proto.RegisterType((*GetInfoByUserIDRequest)(nil), "agent.GetInfoByUserIDRequest")
	proto.RegisterType((*GetInfoByIDRequest)(nil), "agent.GetInfoByIDRequest")
	proto.RegisterType((*GetAgentListRequest)(nil), "agent.GetAgentListRequest")
	proto.RegisterType((*GetAgentListResponse)(nil), "agent.GetAgentListResponse")
	proto.RegisterType((*ChangeAvaliableRequest)(nil), "agent.ChangeAvaliableRequest")
	proto.RegisterType((*ChangeAvaliableResponse)(nil), "agent.ChangeAvaliableResponse")
	proto.RegisterType((*Agent)(nil), "agent.Agent")
	proto.RegisterType((*Link)(nil), "agent.Link")
	proto.RegisterEnum("agent.ChangeAvaliableRequest_Types", ChangeAvaliableRequest_Types_name, ChangeAvaliableRequest_Types_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Create an agent and return the created one.
	Create(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Get an agent's info in Agent Server
	GetInfoByUserID(ctx context.Context, in *GetInfoByUserIDRequest, opts ...grpc.CallOption) (*Agent, error)
	// Get an agent's info in Agent Server by agent id
	GetInfoByID(ctx context.Context, in *GetInfoByIDRequest, opts ...grpc.CallOption) (*Agent, error)
	// Get an agents list in Agent Server
	GetAgentList(ctx context.Context, in *GetAgentListRequest, opts ...grpc.CallOption) (*GetAgentListResponse, error)
	// ChangeAvaliable
	ChangeAvaliable(ctx context.Context, in *ChangeAvaliableRequest, opts ...grpc.CallOption) (*ChangeAvaliableResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Create(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/agent.AgentService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetInfoByUserID(ctx context.Context, in *GetInfoByUserIDRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetInfoByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetInfoByID(ctx context.Context, in *GetInfoByIDRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetInfoByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentList(ctx context.Context, in *GetAgentListRequest, opts ...grpc.CallOption) (*GetAgentListResponse, error) {
	out := new(GetAgentListResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetAgentList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ChangeAvaliable(ctx context.Context, in *ChangeAvaliableRequest, opts ...grpc.CallOption) (*ChangeAvaliableResponse, error) {
	out := new(ChangeAvaliableResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ChangeAvaliable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	// Create an agent and return the created one.
	Create(context.Context, *CreateAgentRequest) (*Agent, error)
	// Get an agent's info in Agent Server
	GetInfoByUserID(context.Context, *GetInfoByUserIDRequest) (*Agent, error)
	// Get an agent's info in Agent Server by agent id
	GetInfoByID(context.Context, *GetInfoByIDRequest) (*Agent, error)
	// Get an agents list in Agent Server
	GetAgentList(context.Context, *GetAgentListRequest) (*GetAgentListResponse, error)
	// ChangeAvaliable
	ChangeAvaliable(context.Context, *ChangeAvaliableRequest) (*ChangeAvaliableResponse, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Create(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetInfoByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetInfoByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/GetInfoByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetInfoByUserID(ctx, req.(*GetInfoByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetInfoByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetInfoByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/GetInfoByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetInfoByID(ctx, req.(*GetInfoByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/GetAgentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentList(ctx, req.(*GetAgentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ChangeAvaliable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAvaliableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ChangeAvaliable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/ChangeAvaliable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ChangeAvaliable(ctx, req.(*ChangeAvaliableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AgentService_Create_Handler,
		},
		{
			MethodName: "GetInfoByUserID",
			Handler:    _AgentService_GetInfoByUserID_Handler,
		},
		{
			MethodName: "GetInfoByID",
			Handler:    _AgentService_GetInfoByID_Handler,
		},
		{
			MethodName: "GetAgentList",
			Handler:    _AgentService_GetAgentList_Handler,
		},
		{
			MethodName: "ChangeAvaliable",
			Handler:    _AgentService_ChangeAvaliable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/agent.proto",
}

func init() { proto.RegisterFile("agent/agent.proto", fileDescriptor_agent_312d7b8de97dc412) }

var fileDescriptor_agent_312d7b8de97dc412 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x21, 0xce, 0xcf, 0x24, 0x40, 0x58, 0xa2, 0x74, 0x9b, 0x52, 0x6a, 0xb9, 0x1c, 0xa2,
	0xaa, 0xa2, 0x05, 0x0e, 0xed, 0xb1, 0x09, 0x51, 0x69, 0x24, 0x04, 0xc8, 0x80, 0x50, 0x8f, 0xc6,
	0x1e, 0x88, 0x15, 0x67, 0x9d, 0xda, 0x06, 0xca, 0x0b, 0xf4, 0x11, 0x7a, 0xec, 0xf3, 0xf4, 0x29,
	0xfa, 0x2c, 0xd5, 0xee, 0xda, 0x1b, 0x3b, 0x4e, 0x7b, 0x89, 0xfc, 0x7d, 0xb3, 0x33, 0xb3, 0xdf,
	0xee, 0xb7, 0x13, 0xd8, 0xb4, 0xef, 0x90, 0xc5, 0xef, 0xc4, 0xef, 0xde, 0x2c, 0x0c, 0xe2, 0x80,
	0xe8, 0x02, 0x98, 0x3f, 0x35, 0x20, 0x47, 0x21, 0xda, 0x31, 0xf6, 0x39, 0xb6, 0xf0, 0xdb, 0x3d,
	0x46, 0x31, 0xe9, 0x42, 0xed, 0xd4, 0x73, 0x26, 0xa7, 0xf6, 0x14, 0xa9, 0x66, 0x68, 0xbd, 0xba,
	0xa5, 0x30, 0xd9, 0x86, 0xfa, 0xf5, 0xf7, 0xbe, 0xe3, 0x04, 0xf7, 0x2c, 0xa6, 0x25, 0x11, 0x9c,
	0x13, 0xa4, 0x03, 0x95, 0xab, 0x08, 0xc3, 0xd1, 0x90, 0xae, 0x1a, 0x5a, 0x4f, 0xb7, 0x12, 0x44,
	0xda, 0xa0, 0x9f, 0x8f, 0x03, 0x86, 0xb4, 0x2c, 0x32, 0x24, 0x20, 0x14, 0xaa, 0x5f, 0xd0, 0x76,
	0x47, 0xd3, 0x3b, 0xaa, 0x0b, 0x3e, 0x85, 0xe6, 0x7b, 0xe8, 0x1c, 0x63, 0x3c, 0x62, 0xb7, 0xc1,
	0xe0, 0x49, 0x96, 0x48, 0xf7, 0x36, 0xef, 0xa0, 0x65, 0x3b, 0x98, 0xbb, 0x40, 0x54, 0xc6, 0x7c,
	0xf5, 0x3a, 0x94, 0xd4, 0xca, 0xd2, 0x68, 0x68, 0x7e, 0x85, 0xad, 0x63, 0x8c, 0x85, 0xd8, 0x13,
	0x2f, 0x52, 0x82, 0xdb, 0xa0, 0x9f, 0x85, 0x2e, 0x86, 0x89, 0x5a, 0x09, 0x38, 0x7b, 0xe2, 0x4d,
	0x3d, 0x29, 0x53, 0xb7, 0x24, 0xe0, 0x1b, 0x38, 0xbb, 0xbd, 0x8d, 0x30, 0x4e, 0x25, 0x4a, 0x64,
	0x9e, 0x42, 0x3b, 0x5f, 0x3a, 0x9a, 0x05, 0x2c, 0x42, 0x62, 0x40, 0x99, 0x63, 0xaa, 0x19, 0xab,
	0xbd, 0xc6, 0x41, 0x73, 0x4f, 0x5e, 0x83, 0x3c, 0x6f, 0x11, 0xe1, 0x7d, 0x8e, 0xd4, 0x71, 0xea,
	0x96, 0x04, 0xe6, 0x2f, 0x0d, 0x3a, 0x47, 0x63, 0x9b, 0xdd, 0x61, 0xff, 0xc1, 0xf6, 0x3d, 0xfb,
	0xc6, 0xc7, 0x74, 0xbb, 0x14, 0xaa, 0x22, 0x5f, 0x49, 0x4b, 0x21, 0xf9, 0x00, 0xe5, 0xcb, 0xa7,
	0x19, 0x8a, 0x4a, 0xeb, 0x07, 0xaf, 0x93, 0x66, 0xcb, 0xcb, 0xec, 0xf1, 0x95, 0x91, 0x25, 0x12,
	0xcc, 0x7d, 0xd0, 0x05, 0x24, 0x4d, 0xa8, 0x5d, 0xb1, 0x09, 0x0b, 0xd8, 0x23, 0x6b, 0xad, 0x90,
	0x06, 0x54, 0x07, 0x7e, 0xe0, 0x4c, 0xd0, 0x6d, 0x69, 0x64, 0x0d, 0xea, 0xaa, 0x46, 0xab, 0x64,
	0xee, 0xc3, 0xb3, 0x42, 0xe1, 0x44, 0x73, 0x07, 0x2a, 0x21, 0x46, 0xf7, 0x7e, 0x9c, 0x1c, 0x68,
	0x82, 0xcc, 0xdf, 0x65, 0xd0, 0xc5, 0x56, 0x17, 0x2f, 0x86, 0x10, 0x28, 0x0b, 0xbb, 0x49, 0x47,
	0x89, 0xef, 0x9c, 0x0d, 0x57, 0x17, 0x6c, 0x98, 0xb1, 0x4e, 0x39, 0x67, 0x9d, 0xb9, 0xd5, 0xf4,
	0xac, 0xd5, 0xb6, 0x33, 0x7b, 0xa7, 0x15, 0x43, 0xeb, 0xd5, 0xac, 0x39, 0xc1, 0xab, 0x0d, 0x6c,
	0xdf, 0x66, 0x0e, 0xd2, 0xaa, 0xa1, 0xf5, 0x34, 0x2b, 0x85, 0x79, 0xbb, 0xd7, 0x16, 0xed, 0xde,
	0x06, 0xfd, 0xc2, 0x09, 0x5c, 0xa4, 0x75, 0xd9, 0x4b, 0x00, 0xb2, 0x03, 0x20, 0x6d, 0x80, 0x0f,
	0xe8, 0x53, 0x10, 0x1a, 0x33, 0x0c, 0x79, 0x03, 0xad, 0x6b, 0x2f, 0x1e, 0xbb, 0xa1, 0xfd, 0x78,
	0x6e, 0x47, 0xd1, 0x63, 0x10, 0xba, 0xb4, 0x21, 0x0a, 0x14, 0x78, 0x62, 0x40, 0xe3, 0xdc, 0x7e,
	0x52, 0xcb, 0x9a, 0x62, 0x59, 0x96, 0xca, 0x3c, 0x88, 0xb5, 0xdc, 0x93, 0xdb, 0x85, 0xca, 0x67,
	0x3b, 0x1e, 0x63, 0x48, 0xd7, 0x0d, 0xad, 0xe0, 0xbc, 0x24, 0xc6, 0xf5, 0xc9, 0x01, 0xe0, 0xf6,
	0x63, 0xba, 0x21, 0xf5, 0x29, 0x82, 0x47, 0xaf, 0x66, 0x6e, 0x12, 0x6d, 0xc9, 0xa8, 0x22, 0x78,
	0x74, 0x88, 0x7e, 0x12, 0xdd, 0x94, 0x51, 0x45, 0x90, 0x57, 0xdc, 0xf7, 0x6c, 0x42, 0x89, 0xe8,
	0xde, 0x48, 0xba, 0x73, 0xca, 0x12, 0x01, 0x7e, 0xbd, 0x97, 0x41, 0x6c, 0xfb, 0x17, 0x01, 0xa3,
	0x5b, 0x62, 0xeb, 0x0a, 0x73, 0xd9, 0xe2, 0x7b, 0xc4, 0x9c, 0x60, 0x8a, 0xb4, 0x2d, 0x2e, 0x25,
	0x4b, 0x99, 0x3f, 0x4a, 0xb2, 0x7e, 0xc1, 0x49, 0x5d, 0xa8, 0x49, 0x6d, 0xa3, 0x61, 0xf2, 0xa0,
	0x14, 0x26, 0xbb, 0xb0, 0x76, 0x1c, 0xda, 0xcc, 0x55, 0x0b, 0xe4, 0x13, 0xce, 0x93, 0xc4, 0x84,
	0xa6, 0xfc, 0x1e, 0x78, 0x8c, 0x4b, 0x93, 0x06, 0xcb, 0x71, 0xe4, 0x2d, 0x6c, 0x66, 0x92, 0x92,
	0x85, 0xd2, 0x71, 0xc5, 0x40, 0xfe, 0x94, 0x2b, 0xff, 0x3d, 0xe5, 0xea, 0xe2, 0x29, 0xef, 0x00,
	0x0c, 0xd1, 0x4f, 0x93, 0xa5, 0x05, 0x33, 0xcc, 0xc1, 0x9f, 0x12, 0x34, 0xc5, 0x9d, 0x5e, 0x60,
	0xf8, 0xe0, 0x39, 0x48, 0x0e, 0xa1, 0x22, 0x6b, 0x93, 0xe7, 0xe9, 0xfb, 0x2f, 0x8c, 0xf8, 0x6e,
	0xce, 0x0d, 0xe6, 0x0a, 0xf9, 0x04, 0x1b, 0x0b, 0x03, 0x97, 0xbc, 0x4c, 0x96, 0x2c, 0x1f, 0xc4,
	0x85, 0x0a, 0x1f, 0xa1, 0x91, 0x19, 0xc0, 0xaa, 0x77, 0x71, 0x28, 0x17, 0x32, 0x47, 0xd0, 0xcc,
	0x4e, 0x4e, 0xd2, 0x9d, 0xa7, 0x2e, 0x4e, 0xea, 0xee, 0x8b, 0xa5, 0x31, 0x39, 0x76, 0xcc, 0x15,
	0x62, 0xc1, 0xc6, 0xc2, 0x4c, 0x52, 0x32, 0x96, 0x0f, 0xc1, 0xee, 0xce, 0xbf, 0xc2, 0x69, 0xcd,
	0x9b, 0x8a, 0xf8, 0xcb, 0x3c, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x35, 0x12, 0xda, 0xe3, 0x47,
	0x07, 0x00, 0x00,
}
