// Code generated by protoc-gen-go. DO NOT EDIT.
// source: circle/circle.proto

package circle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCircleMsgRequest_Tp int32

const (
	GetCircleMsgRequest_UNIVERSAL GetCircleMsgRequest_Tp = 0
	GetCircleMsgRequest_JOIN      GetCircleMsgRequest_Tp = 1
	GetCircleMsgRequest_QUIT      GetCircleMsgRequest_Tp = 2
	GetCircleMsgRequest_KICK      GetCircleMsgRequest_Tp = 3
	GetCircleMsgRequest_APPLY     GetCircleMsgRequest_Tp = 4
)

var GetCircleMsgRequest_Tp_name = map[int32]string{
	0: "UNIVERSAL",
	1: "JOIN",
	2: "QUIT",
	3: "KICK",
	4: "APPLY",
}

var GetCircleMsgRequest_Tp_value = map[string]int32{
	"UNIVERSAL": 0,
	"JOIN":      1,
	"QUIT":      2,
	"KICK":      3,
	"APPLY":     4,
}

func (x GetCircleMsgRequest_Tp) String() string {
	return proto.EnumName(GetCircleMsgRequest_Tp_name, int32(x))
}

func (GetCircleMsgRequest_Tp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{10, 0}
}

type CircleMsg_Tp int32

const (
	CircleMsg_UNIVERSAL CircleMsg_Tp = 0
	CircleMsg_JOIN      CircleMsg_Tp = 1
	CircleMsg_QUIT      CircleMsg_Tp = 2
	CircleMsg_KICK      CircleMsg_Tp = 3
	CircleMsg_APPLY     CircleMsg_Tp = 4
)

var CircleMsg_Tp_name = map[int32]string{
	0: "UNIVERSAL",
	1: "JOIN",
	2: "QUIT",
	3: "KICK",
	4: "APPLY",
}

var CircleMsg_Tp_value = map[string]int32{
	"UNIVERSAL": 0,
	"JOIN":      1,
	"QUIT":      2,
	"KICK":      3,
	"APPLY":     4,
}

func (x CircleMsg_Tp) String() string {
	return proto.EnumName(CircleMsg_Tp_name, int32(x))
}

func (CircleMsg_Tp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{20, 0}
}

type BuildCircleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Notice               string   `protobuf:"bytes,2,opt,name=Notice,proto3" json:"Notice,omitempty"`
	U                    *User    `protobuf:"bytes,3,opt,name=U,proto3" json:"U,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildCircleRequest) Reset()         { *m = BuildCircleRequest{} }
func (m *BuildCircleRequest) String() string { return proto.CompactTextString(m) }
func (*BuildCircleRequest) ProtoMessage()    {}
func (*BuildCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{0}
}

func (m *BuildCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildCircleRequest.Unmarshal(m, b)
}
func (m *BuildCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildCircleRequest.Marshal(b, m, deterministic)
}
func (m *BuildCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildCircleRequest.Merge(m, src)
}
func (m *BuildCircleRequest) XXX_Size() int {
	return xxx_messageInfo_BuildCircleRequest.Size(m)
}
func (m *BuildCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildCircleRequest proto.InternalMessageInfo

func (m *BuildCircleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildCircleRequest) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *BuildCircleRequest) GetU() *User {
	if m != nil {
		return m.U
	}
	return nil
}

type BuildCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildCircleResponse) Reset()         { *m = BuildCircleResponse{} }
func (m *BuildCircleResponse) String() string { return proto.CompactTextString(m) }
func (*BuildCircleResponse) ProtoMessage()    {}
func (*BuildCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{1}
}

func (m *BuildCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildCircleResponse.Unmarshal(m, b)
}
func (m *BuildCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildCircleResponse.Marshal(b, m, deterministic)
}
func (m *BuildCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildCircleResponse.Merge(m, src)
}
func (m *BuildCircleResponse) XXX_Size() int {
	return xxx_messageInfo_BuildCircleResponse.Size(m)
}
func (m *BuildCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildCircleResponse proto.InternalMessageInfo

func (m *BuildCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateCircleRequest struct {
	CircleId             int32             `protobuf:"varint,1,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	OwnerId              int32             `protobuf:"varint,2,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	Update               map[string]string `protobuf:"bytes,3,rep,name=update,proto3" json:"update,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateCircleRequest) Reset()         { *m = UpdateCircleRequest{} }
func (m *UpdateCircleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCircleRequest) ProtoMessage()    {}
func (*UpdateCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{2}
}

func (m *UpdateCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCircleRequest.Unmarshal(m, b)
}
func (m *UpdateCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCircleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCircleRequest.Merge(m, src)
}
func (m *UpdateCircleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCircleRequest.Size(m)
}
func (m *UpdateCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCircleRequest proto.InternalMessageInfo

func (m *UpdateCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *UpdateCircleRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *UpdateCircleRequest) GetUpdate() map[string]string {
	if m != nil {
		return m.Update
	}
	return nil
}

type UpdateCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCircleResponse) Reset()         { *m = UpdateCircleResponse{} }
func (m *UpdateCircleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCircleResponse) ProtoMessage()    {}
func (*UpdateCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{3}
}

func (m *UpdateCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCircleResponse.Unmarshal(m, b)
}
func (m *UpdateCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCircleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCircleResponse.Merge(m, src)
}
func (m *UpdateCircleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCircleResponse.Size(m)
}
func (m *UpdateCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCircleResponse proto.InternalMessageInfo

func (m *UpdateCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetCircleListRequest struct {
	OwnerId              int32    `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCircleListRequest) Reset()         { *m = GetCircleListRequest{} }
func (m *GetCircleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetCircleListRequest) ProtoMessage()    {}
func (*GetCircleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{4}
}

func (m *GetCircleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleListRequest.Unmarshal(m, b)
}
func (m *GetCircleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleListRequest.Marshal(b, m, deterministic)
}
func (m *GetCircleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleListRequest.Merge(m, src)
}
func (m *GetCircleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetCircleListRequest.Size(m)
}
func (m *GetCircleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleListRequest proto.InternalMessageInfo

func (m *GetCircleListRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type GetCircleListResponse struct {
	Circles              []*Circle `protobuf:"bytes,1,rep,name=Circles,proto3" json:"Circles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCircleListResponse) Reset()         { *m = GetCircleListResponse{} }
func (m *GetCircleListResponse) String() string { return proto.CompactTextString(m) }
func (*GetCircleListResponse) ProtoMessage()    {}
func (*GetCircleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{5}
}

func (m *GetCircleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleListResponse.Unmarshal(m, b)
}
func (m *GetCircleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleListResponse.Marshal(b, m, deterministic)
}
func (m *GetCircleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleListResponse.Merge(m, src)
}
func (m *GetCircleListResponse) XXX_Size() int {
	return xxx_messageInfo_GetCircleListResponse.Size(m)
}
func (m *GetCircleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleListResponse proto.InternalMessageInfo

func (m *GetCircleListResponse) GetCircles() []*Circle {
	if m != nil {
		return m.Circles
	}
	return nil
}

type DelCircleRequest struct {
	OwnerId              int32    `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	CircleId             int32    `protobuf:"varint,2,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCircleRequest) Reset()         { *m = DelCircleRequest{} }
func (m *DelCircleRequest) String() string { return proto.CompactTextString(m) }
func (*DelCircleRequest) ProtoMessage()    {}
func (*DelCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{6}
}

func (m *DelCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCircleRequest.Unmarshal(m, b)
}
func (m *DelCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCircleRequest.Marshal(b, m, deterministic)
}
func (m *DelCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCircleRequest.Merge(m, src)
}
func (m *DelCircleRequest) XXX_Size() int {
	return xxx_messageInfo_DelCircleRequest.Size(m)
}
func (m *DelCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelCircleRequest proto.InternalMessageInfo

func (m *DelCircleRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DelCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type DelCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCircleResponse) Reset()         { *m = DelCircleResponse{} }
func (m *DelCircleResponse) String() string { return proto.CompactTextString(m) }
func (*DelCircleResponse) ProtoMessage()    {}
func (*DelCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{7}
}

func (m *DelCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCircleResponse.Unmarshal(m, b)
}
func (m *DelCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCircleResponse.Marshal(b, m, deterministic)
}
func (m *DelCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCircleResponse.Merge(m, src)
}
func (m *DelCircleResponse) XXX_Size() int {
	return xxx_messageInfo_DelCircleResponse.Size(m)
}
func (m *DelCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelCircleResponse proto.InternalMessageInfo

func (m *DelCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ApplyJoinCircleRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	UId                  int32    `protobuf:"varint,2,opt,name=UId,proto3" json:"UId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyJoinCircleRequest) Reset()         { *m = ApplyJoinCircleRequest{} }
func (m *ApplyJoinCircleRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyJoinCircleRequest) ProtoMessage()    {}
func (*ApplyJoinCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{8}
}

func (m *ApplyJoinCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyJoinCircleRequest.Unmarshal(m, b)
}
func (m *ApplyJoinCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyJoinCircleRequest.Marshal(b, m, deterministic)
}
func (m *ApplyJoinCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyJoinCircleRequest.Merge(m, src)
}
func (m *ApplyJoinCircleRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyJoinCircleRequest.Size(m)
}
func (m *ApplyJoinCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyJoinCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyJoinCircleRequest proto.InternalMessageInfo

func (m *ApplyJoinCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *ApplyJoinCircleRequest) GetUId() int32 {
	if m != nil {
		return m.UId
	}
	return 0
}

type ApplyJoinCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyJoinCircleResponse) Reset()         { *m = ApplyJoinCircleResponse{} }
func (m *ApplyJoinCircleResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyJoinCircleResponse) ProtoMessage()    {}
func (*ApplyJoinCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{9}
}

func (m *ApplyJoinCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyJoinCircleResponse.Unmarshal(m, b)
}
func (m *ApplyJoinCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyJoinCircleResponse.Marshal(b, m, deterministic)
}
func (m *ApplyJoinCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyJoinCircleResponse.Merge(m, src)
}
func (m *ApplyJoinCircleResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyJoinCircleResponse.Size(m)
}
func (m *ApplyJoinCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyJoinCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyJoinCircleResponse proto.InternalMessageInfo

func (m *ApplyJoinCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ApplyJoinCircleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetCircleMsgRequest struct {
	OwnerId              int32                  `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	CircleId             int32                  `protobuf:"varint,2,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	T                    GetCircleMsgRequest_Tp `protobuf:"varint,3,opt,name=T,proto3,enum=GetCircleMsgRequest_Tp" json:"T,omitempty"`
	Page                 int32                  `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32                  `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetCircleMsgRequest) Reset()         { *m = GetCircleMsgRequest{} }
func (m *GetCircleMsgRequest) String() string { return proto.CompactTextString(m) }
func (*GetCircleMsgRequest) ProtoMessage()    {}
func (*GetCircleMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{10}
}

func (m *GetCircleMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleMsgRequest.Unmarshal(m, b)
}
func (m *GetCircleMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleMsgRequest.Marshal(b, m, deterministic)
}
func (m *GetCircleMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleMsgRequest.Merge(m, src)
}
func (m *GetCircleMsgRequest) XXX_Size() int {
	return xxx_messageInfo_GetCircleMsgRequest.Size(m)
}
func (m *GetCircleMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleMsgRequest proto.InternalMessageInfo

func (m *GetCircleMsgRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetCircleMsgRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GetCircleMsgRequest) GetT() GetCircleMsgRequest_Tp {
	if m != nil {
		return m.T
	}
	return GetCircleMsgRequest_UNIVERSAL
}

func (m *GetCircleMsgRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCircleMsgRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetCircleMsgResponse struct {
	ApplyMsgs            []*CircleMsg `protobuf:"bytes,1,rep,name=ApplyMsgs,proto3" json:"ApplyMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCircleMsgResponse) Reset()         { *m = GetCircleMsgResponse{} }
func (m *GetCircleMsgResponse) String() string { return proto.CompactTextString(m) }
func (*GetCircleMsgResponse) ProtoMessage()    {}
func (*GetCircleMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{11}
}

func (m *GetCircleMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleMsgResponse.Unmarshal(m, b)
}
func (m *GetCircleMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleMsgResponse.Marshal(b, m, deterministic)
}
func (m *GetCircleMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleMsgResponse.Merge(m, src)
}
func (m *GetCircleMsgResponse) XXX_Size() int {
	return xxx_messageInfo_GetCircleMsgResponse.Size(m)
}
func (m *GetCircleMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleMsgResponse proto.InternalMessageInfo

func (m *GetCircleMsgResponse) GetApplyMsgs() []*CircleMsg {
	if m != nil {
		return m.ApplyMsgs
	}
	return nil
}

type DealApplyRequest struct {
	U                    *User    `protobuf:"bytes,1,opt,name=U,proto3" json:"U,omitempty"`
	CircleId             int32    `protobuf:"varint,2,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,3,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	MsgId                int32    `protobuf:"varint,4,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	UserId               int32    `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Agree                bool     `protobuf:"varint,6,opt,name=Agree,proto3" json:"Agree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealApplyRequest) Reset()         { *m = DealApplyRequest{} }
func (m *DealApplyRequest) String() string { return proto.CompactTextString(m) }
func (*DealApplyRequest) ProtoMessage()    {}
func (*DealApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{12}
}

func (m *DealApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealApplyRequest.Unmarshal(m, b)
}
func (m *DealApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealApplyRequest.Marshal(b, m, deterministic)
}
func (m *DealApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealApplyRequest.Merge(m, src)
}
func (m *DealApplyRequest) XXX_Size() int {
	return xxx_messageInfo_DealApplyRequest.Size(m)
}
func (m *DealApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealApplyRequest proto.InternalMessageInfo

func (m *DealApplyRequest) GetU() *User {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *DealApplyRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *DealApplyRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DealApplyRequest) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *DealApplyRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DealApplyRequest) GetAgree() bool {
	if m != nil {
		return m.Agree
	}
	return false
}

type DealApplyResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User                 *CircleUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DealApplyResponse) Reset()         { *m = DealApplyResponse{} }
func (m *DealApplyResponse) String() string { return proto.CompactTextString(m) }
func (*DealApplyResponse) ProtoMessage()    {}
func (*DealApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{13}
}

func (m *DealApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealApplyResponse.Unmarshal(m, b)
}
func (m *DealApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealApplyResponse.Marshal(b, m, deterministic)
}
func (m *DealApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealApplyResponse.Merge(m, src)
}
func (m *DealApplyResponse) XXX_Size() int {
	return xxx_messageInfo_DealApplyResponse.Size(m)
}
func (m *DealApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DealApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DealApplyResponse proto.InternalMessageInfo

func (m *DealApplyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DealApplyResponse) GetUser() *CircleUser {
	if m != nil {
		return m.User
	}
	return nil
}

type DealMessageRequest struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	CircleId             int32    `protobuf:"varint,3,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealMessageRequest) Reset()         { *m = DealMessageRequest{} }
func (m *DealMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DealMessageRequest) ProtoMessage()    {}
func (*DealMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{14}
}

func (m *DealMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealMessageRequest.Unmarshal(m, b)
}
func (m *DealMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealMessageRequest.Marshal(b, m, deterministic)
}
func (m *DealMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealMessageRequest.Merge(m, src)
}
func (m *DealMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DealMessageRequest.Size(m)
}
func (m *DealMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealMessageRequest proto.InternalMessageInfo

func (m *DealMessageRequest) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *DealMessageRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DealMessageRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type DealMessageResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealMessageResponse) Reset()         { *m = DealMessageResponse{} }
func (m *DealMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DealMessageResponse) ProtoMessage()    {}
func (*DealMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{15}
}

func (m *DealMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealMessageResponse.Unmarshal(m, b)
}
func (m *DealMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealMessageResponse.Marshal(b, m, deterministic)
}
func (m *DealMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealMessageResponse.Merge(m, src)
}
func (m *DealMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DealMessageResponse.Size(m)
}
func (m *DealMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DealMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DealMessageResponse proto.InternalMessageInfo

func (m *DealMessageResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetApplyListRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplyListRequest) Reset()         { *m = GetApplyListRequest{} }
func (m *GetApplyListRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplyListRequest) ProtoMessage()    {}
func (*GetApplyListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{16}
}

func (m *GetApplyListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyListRequest.Unmarshal(m, b)
}
func (m *GetApplyListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyListRequest.Marshal(b, m, deterministic)
}
func (m *GetApplyListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyListRequest.Merge(m, src)
}
func (m *GetApplyListRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplyListRequest.Size(m)
}
func (m *GetApplyListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyListRequest proto.InternalMessageInfo

func (m *GetApplyListRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GetApplyListRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetApplyListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetApplyListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetApplyListResponse struct {
	ApplyMsgs            []*CircleMsg `protobuf:"bytes,1,rep,name=ApplyMsgs,proto3" json:"ApplyMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetApplyListResponse) Reset()         { *m = GetApplyListResponse{} }
func (m *GetApplyListResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplyListResponse) ProtoMessage()    {}
func (*GetApplyListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{17}
}

func (m *GetApplyListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyListResponse.Unmarshal(m, b)
}
func (m *GetApplyListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyListResponse.Marshal(b, m, deterministic)
}
func (m *GetApplyListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyListResponse.Merge(m, src)
}
func (m *GetApplyListResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplyListResponse.Size(m)
}
func (m *GetApplyListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyListResponse proto.InternalMessageInfo

func (m *GetApplyListResponse) GetApplyMsgs() []*CircleMsg {
	if m != nil {
		return m.ApplyMsgs
	}
	return nil
}

type CircleUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ImgUrl               string   `protobuf:"bytes,3,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	JoinAt               string   `protobuf:"bytes,5,opt,name=JoinAt,proto3" json:"JoinAt,omitempty"`
	CircleId             int32    `protobuf:"varint,6,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleUser) Reset()         { *m = CircleUser{} }
func (m *CircleUser) String() string { return proto.CompactTextString(m) }
func (*CircleUser) ProtoMessage()    {}
func (*CircleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{18}
}

func (m *CircleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleUser.Unmarshal(m, b)
}
func (m *CircleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleUser.Marshal(b, m, deterministic)
}
func (m *CircleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleUser.Merge(m, src)
}
func (m *CircleUser) XXX_Size() int {
	return xxx_messageInfo_CircleUser.Size(m)
}
func (m *CircleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleUser.DiscardUnknown(m)
}

var xxx_messageInfo_CircleUser proto.InternalMessageInfo

func (m *CircleUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CircleUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CircleUser) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *CircleUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CircleUser) GetJoinAt() string {
	if m != nil {
		return m.JoinAt
	}
	return ""
}

func (m *CircleUser) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ImgUrl               string   `protobuf:"bytes,2,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{19}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CircleMsg struct {
	Id                   int32        `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Content              string       `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	T                    CircleMsg_Tp `protobuf:"varint,3,opt,name=T,proto3,enum=CircleMsg_Tp" json:"T,omitempty"`
	UpdateAt             string       `protobuf:"bytes,4,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	CreateAt             string       `protobuf:"bytes,5,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UserId               int32        `protobuf:"varint,6,opt,name=UserId,proto3" json:"UserId,omitempty"`
	U                    *User        `protobuf:"bytes,7,opt,name=U,proto3" json:"U,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CircleMsg) Reset()         { *m = CircleMsg{} }
func (m *CircleMsg) String() string { return proto.CompactTextString(m) }
func (*CircleMsg) ProtoMessage()    {}
func (*CircleMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{20}
}

func (m *CircleMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleMsg.Unmarshal(m, b)
}
func (m *CircleMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleMsg.Marshal(b, m, deterministic)
}
func (m *CircleMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleMsg.Merge(m, src)
}
func (m *CircleMsg) XXX_Size() int {
	return xxx_messageInfo_CircleMsg.Size(m)
}
func (m *CircleMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CircleMsg proto.InternalMessageInfo

func (m *CircleMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CircleMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CircleMsg) GetT() CircleMsg_Tp {
	if m != nil {
		return m.T
	}
	return CircleMsg_UNIVERSAL
}

func (m *CircleMsg) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *CircleMsg) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *CircleMsg) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CircleMsg) GetU() *User {
	if m != nil {
		return m.U
	}
	return nil
}

type Circle struct {
	OwnerId              int32    `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	CreateAt             string   `protobuf:"bytes,2,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt             string   `protobuf:"bytes,3,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	Notice               string   `protobuf:"bytes,4,opt,name=Notice,proto3" json:"Notice,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	CircleId             int32    `protobuf:"varint,6,opt,name=CircleId,proto3" json:"CircleId,omitempty"`
	MemberCount          int32    `protobuf:"varint,7,opt,name=MemberCount,proto3" json:"MemberCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circle) Reset()         { *m = Circle{} }
func (m *Circle) String() string { return proto.CompactTextString(m) }
func (*Circle) ProtoMessage()    {}
func (*Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{21}
}

func (m *Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circle.Unmarshal(m, b)
}
func (m *Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circle.Marshal(b, m, deterministic)
}
func (m *Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circle.Merge(m, src)
}
func (m *Circle) XXX_Size() int {
	return xxx_messageInfo_Circle.Size(m)
}
func (m *Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Circle proto.InternalMessageInfo

func (m *Circle) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Circle) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Circle) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *Circle) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *Circle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Circle) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *Circle) GetMemberCount() int32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("GetCircleMsgRequest_Tp", GetCircleMsgRequest_Tp_name, GetCircleMsgRequest_Tp_value)
	proto.RegisterEnum("CircleMsg_Tp", CircleMsg_Tp_name, CircleMsg_Tp_value)
	proto.RegisterType((*BuildCircleRequest)(nil), "BuildCircleRequest")
	proto.RegisterType((*BuildCircleResponse)(nil), "BuildCircleResponse")
	proto.RegisterType((*UpdateCircleRequest)(nil), "UpdateCircleRequest")
	proto.RegisterMapType((map[string]string)(nil), "UpdateCircleRequest.UpdateEntry")
	proto.RegisterType((*UpdateCircleResponse)(nil), "UpdateCircleResponse")
	proto.RegisterType((*GetCircleListRequest)(nil), "GetCircleListRequest")
	proto.RegisterType((*GetCircleListResponse)(nil), "GetCircleListResponse")
	proto.RegisterType((*DelCircleRequest)(nil), "DelCircleRequest")
	proto.RegisterType((*DelCircleResponse)(nil), "DelCircleResponse")
	proto.RegisterType((*ApplyJoinCircleRequest)(nil), "ApplyJoinCircleRequest")
	proto.RegisterType((*ApplyJoinCircleResponse)(nil), "ApplyJoinCircleResponse")
	proto.RegisterType((*GetCircleMsgRequest)(nil), "GetCircleMsgRequest")
	proto.RegisterType((*GetCircleMsgResponse)(nil), "GetCircleMsgResponse")
	proto.RegisterType((*DealApplyRequest)(nil), "DealApplyRequest")
	proto.RegisterType((*DealApplyResponse)(nil), "DealApplyResponse")
	proto.RegisterType((*DealMessageRequest)(nil), "DealMessageRequest")
	proto.RegisterType((*DealMessageResponse)(nil), "DealMessageResponse")
	proto.RegisterType((*GetApplyListRequest)(nil), "GetApplyListRequest")
	proto.RegisterType((*GetApplyListResponse)(nil), "GetApplyListResponse")
	proto.RegisterType((*CircleUser)(nil), "CircleUser")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CircleMsg)(nil), "CircleMsg")
	proto.RegisterType((*Circle)(nil), "Circle")
}

func init() { proto.RegisterFile("circle/circle.proto", fileDescriptor_bb5c720f4490ca94) }

var fileDescriptor_bb5c720f4490ca94 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0xf6, 0x48, 0xfe, 0x89, 0xdb, 0x64, 0x51, 0x46, 0x4e, 0xa2, 0x12, 0x07, 0xcc, 0x54, 0x51,
	0x95, 0x0b, 0x93, 0x2d, 0xc3, 0x61, 0x49, 0x41, 0xd5, 0x7a, 0xc3, 0x2e, 0x68, 0x37, 0xf6, 0x06,
	0xad, 0x45, 0x15, 0x37, 0xbc, 0xf6, 0x94, 0xcb, 0x85, 0x63, 0x1b, 0x49, 0x5e, 0x2a, 0xef, 0xc1,
	0x0b, 0xf0, 0x26, 0x1c, 0x78, 0x0a, 0x4e, 0xbc, 0x04, 0x37, 0x0e, 0xd4, 0xfc, 0x48, 0x9a, 0x91,
	0x95, 0x35, 0x90, 0x3d, 0x59, 0x3d, 0x92, 0xbb, 0xbf, 0xfe, 0xba, 0xe7, 0xeb, 0x06, 0x77, 0xba,
	0x88, 0xa7, 0x4b, 0x76, 0x2e, 0x7f, 0xe8, 0x26, 0x5e, 0xa7, 0x6b, 0x12, 0x01, 0x7e, 0xb2, 0x5d,
	0x2c, 0x67, 0x97, 0xe2, 0x30, 0x64, 0x3f, 0x6d, 0x59, 0x92, 0x62, 0x0c, 0xf5, 0xd1, 0xe4, 0x86,
	0x79, 0xa8, 0x87, 0xce, 0xda, 0xa1, 0x78, 0xc6, 0x27, 0xd0, 0x1c, 0xad, 0xd3, 0xc5, 0x94, 0x79,
	0x96, 0x38, 0x55, 0x16, 0x76, 0x01, 0x45, 0x9e, 0xdd, 0x43, 0x67, 0x9d, 0x7e, 0x83, 0x46, 0x09,
	0x8b, 0x43, 0x14, 0x91, 0x73, 0x70, 0x0d, 0xb7, 0xc9, 0x66, 0xbd, 0x4a, 0x18, 0xf6, 0xa0, 0x95,
	0x6c, 0xa7, 0x53, 0x96, 0x24, 0xc2, 0xf5, 0x41, 0x98, 0x99, 0xe4, 0x37, 0x04, 0x6e, 0xb4, 0x99,
	0x4d, 0x52, 0x66, 0x22, 0xf1, 0xe1, 0x40, 0x1e, 0x04, 0x33, 0xf1, 0x97, 0x46, 0x98, 0xdb, 0xdc,
	0xdb, 0xcb, 0x9f, 0x57, 0x2c, 0x0e, 0x66, 0x02, 0x52, 0x23, 0xcc, 0x4c, 0xfc, 0x08, 0x9a, 0x5b,
	0xe1, 0xcc, 0xb3, 0x7b, 0xf6, 0x59, 0xa7, 0xdf, 0xa3, 0x15, 0xbe, 0xd5, 0xd9, 0xd3, 0x55, 0x1a,
	0xdf, 0x86, 0xea, 0x7b, 0xff, 0x73, 0xe8, 0x68, 0xc7, 0xd8, 0x01, 0xfb, 0x47, 0x76, 0xab, 0x78,
	0xe0, 0x8f, 0xb8, 0x0b, 0x8d, 0x37, 0x93, 0xe5, 0x36, 0x63, 0x41, 0x1a, 0x17, 0xd6, 0x23, 0x44,
	0x1e, 0x42, 0xd7, 0x8c, 0xb2, 0x37, 0xe9, 0x87, 0xd0, 0xfd, 0x9a, 0xa5, 0xf2, 0xf3, 0xab, 0x45,
	0x92, 0x66, 0x49, 0x6b, 0x89, 0x21, 0x23, 0x31, 0x72, 0x01, 0xc7, 0xa5, 0x7f, 0xa8, 0x20, 0x1f,
	0x41, 0x4b, 0x9e, 0xf2, 0x20, 0x3c, 0xe5, 0x16, 0x55, 0x30, 0xb2, 0x73, 0xf2, 0x0d, 0x38, 0x5f,
	0xb1, 0xa5, 0x49, 0xef, 0x9d, 0x91, 0x0c, 0xe2, 0x2d, 0x93, 0x78, 0xf2, 0x09, 0x1c, 0x69, 0x9e,
	0xf6, 0xa6, 0xf9, 0x0c, 0x4e, 0x06, 0x9b, 0xcd, 0xf2, 0xf6, 0xf9, 0x7a, 0xb1, 0xfa, 0xf7, 0xd5,
	0x75, 0xc0, 0x8e, 0xf2, 0xd8, 0xfc, 0x91, 0x0c, 0xe1, 0x74, 0xc7, 0xcf, 0xbe, 0xe0, 0xfc, 0xcd,
	0x90, 0x25, 0xc9, 0x64, 0x9e, 0x55, 0x2c, 0x33, 0xc9, 0x1f, 0x08, 0xdc, 0x9c, 0xcc, 0x61, 0x32,
	0xbf, 0x17, 0x27, 0xf8, 0x63, 0x40, 0x63, 0x71, 0x0d, 0x1e, 0xf4, 0x4f, 0x69, 0x85, 0x5b, 0x3a,
	0xde, 0x84, 0x68, 0xcc, 0x6f, 0xd6, 0x35, 0xc7, 0x52, 0x17, 0x7f, 0x17, 0xcf, 0xbc, 0xa5, 0xae,
	0x16, 0x37, 0x8b, 0xd4, 0x6b, 0x88, 0x43, 0x69, 0x90, 0x2f, 0xc0, 0x1a, 0x6f, 0xf0, 0x21, 0xb4,
	0xa3, 0x51, 0xf0, 0xdd, 0xd3, 0xf0, 0xd5, 0xe0, 0xca, 0xa9, 0xe1, 0x03, 0xa8, 0x3f, 0x7f, 0x19,
	0x8c, 0x1c, 0xc4, 0x9f, 0xbe, 0x8d, 0x82, 0xb1, 0x63, 0xf1, 0xa7, 0x17, 0xc1, 0xe5, 0x0b, 0xc7,
	0xc6, 0x6d, 0x68, 0x0c, 0xae, 0xaf, 0xaf, 0xbe, 0x77, 0xea, 0xe4, 0xb1, 0xd6, 0x5a, 0x02, 0x84,
	0x22, 0xea, 0x0c, 0xda, 0x82, 0xc3, 0x61, 0x32, 0xcf, 0x3a, 0x05, 0x68, 0xf1, 0x59, 0xf1, 0x92,
	0xfc, 0x8a, 0x78, 0xbf, 0x4c, 0x96, 0xe2, 0x24, 0xe3, 0x46, 0x5c, 0x76, 0x64, 0x5e, 0xf6, 0xb7,
	0xd2, 0xa2, 0x91, 0x69, 0x9b, 0x64, 0x76, 0xa1, 0x31, 0x4c, 0xe6, 0xc1, 0x4c, 0x51, 0x21, 0x0d,
	0xae, 0x32, 0xdc, 0x6d, 0x30, 0x53, 0x64, 0x28, 0x8b, 0x7f, 0x3d, 0x98, 0xc7, 0x8c, 0x79, 0x4d,
	0x51, 0x5e, 0x69, 0x90, 0x11, 0x6f, 0xc4, 0x1c, 0xe2, 0xde, 0x5e, 0xf8, 0x10, 0xea, 0xdb, 0x84,
	0xc5, 0x02, 0x64, 0xa7, 0xdf, 0x51, 0x79, 0x8b, 0x34, 0xc4, 0x0b, 0xf2, 0x03, 0x60, 0xee, 0x4f,
	0x75, 0x48, 0x96, 0x74, 0x8e, 0x14, 0xe9, 0x48, 0xef, 0x56, 0x1f, 0x9d, 0x0f, 0xbb, 0x74, 0x75,
	0xce, 0xc1, 0x35, 0x22, 0xec, 0xbd, 0x3c, 0x5b, 0xd1, 0xa4, 0x22, 0x43, 0x5d, 0x22, 0xfe, 0x9f,
	0x2e, 0x66, 0xdd, 0x67, 0x57, 0x75, 0x5f, 0x5d, 0xef, 0x3e, 0xd9, 0x3f, 0x5a, 0xd8, 0xff, 0xdc,
	0x3f, 0xbf, 0x20, 0x80, 0x82, 0x60, 0xfc, 0x00, 0xac, 0x1c, 0xaa, 0x25, 0xa1, 0x88, 0x11, 0x63,
	0x99, 0x23, 0x26, 0xb8, 0x99, 0x47, 0xf1, 0x52, 0x00, 0x6c, 0x87, 0xca, 0xd2, 0x9a, 0xa2, 0x6e,
	0x34, 0xc5, 0x09, 0x34, 0xb9, 0x16, 0x0c, 0xe4, 0xcd, 0x69, 0x87, 0xca, 0x32, 0xc8, 0x69, 0x96,
	0x0a, 0xf0, 0x04, 0xea, 0x95, 0x78, 0x8a, 0xd8, 0x96, 0x11, 0x3b, 0xc3, 0x69, 0x17, 0x38, 0xc9,
	0x5f, 0x08, 0xda, 0x79, 0xce, 0x3b, 0x9e, 0x3c, 0x68, 0x5d, 0xae, 0x57, 0x29, 0x5b, 0xa5, 0x99,
	0xe2, 0x28, 0x13, 0x7f, 0x50, 0x68, 0xc4, 0x61, 0x41, 0x9a, 0x52, 0x06, 0x1f, 0x0e, 0xe4, 0xf8,
	0x18, 0xc8, 0x52, 0xb4, 0xc3, 0xdc, 0x16, 0x09, 0xc5, 0x4c, 0xbe, 0x93, 0xa9, 0xe6, 0xb6, 0x46,
	0x4e, 0xd3, 0x20, 0x47, 0x5c, 0xd5, 0x56, 0x69, 0x2e, 0xdf, 0x4f, 0x54, 0x7e, 0x47, 0xd0, 0x94,
	0xb0, 0xf7, 0x88, 0x64, 0x86, 0xd5, 0x2a, 0x61, 0xd5, 0x73, 0xb4, 0x4b, 0x39, 0x16, 0xfb, 0x45,
	0xdd, 0xd8, 0x2f, 0xb2, 0x02, 0x34, 0xb4, 0x46, 0x79, 0x4b, 0x81, 0x71, 0x0f, 0x3a, 0x43, 0x76,
	0xf3, 0x9a, 0xc5, 0x97, 0xeb, 0xed, 0x2a, 0x15, 0x0c, 0x34, 0x42, 0xfd, 0xa8, 0xff, 0xb7, 0x0d,
	0xae, 0x62, 0x7f, 0x92, 0xa4, 0x2c, 0x7e, 0xc5, 0xe2, 0x37, 0x3c, 0xd2, 0x05, 0x74, 0xb4, 0xa5,
	0x05, 0xbb, 0x74, 0x77, 0x33, 0xf2, 0xbb, 0xb4, 0x62, 0xaf, 0x21, 0x35, 0xfc, 0x25, 0xbc, 0xa7,
	0x0f, 0x7f, 0xdc, 0xad, 0xda, 0x38, 0xfc, 0x63, 0x5a, 0xb5, 0x21, 0x90, 0x1a, 0x7e, 0x0c, 0x87,
	0xc6, 0x5c, 0xc7, 0xc7, 0xb4, 0x6a, 0x33, 0xf0, 0x4f, 0x68, 0xe5, 0xf8, 0x27, 0x35, 0xfc, 0x19,
	0xb4, 0xf3, 0x99, 0x8c, 0x8f, 0x68, 0x79, 0xd2, 0xfb, 0x98, 0xee, 0x8c, 0x6c, 0x52, 0xc3, 0x03,
	0x70, 0x8a, 0x31, 0x21, 0x35, 0x09, 0x77, 0xab, 0xc6, 0x97, 0x7f, 0x4c, 0xab, 0xe6, 0x09, 0xa9,
	0x71, 0xd6, 0x34, 0x45, 0xc3, 0x2e, 0xdd, 0x55, 0x50, 0xbf, 0x4b, 0x2b, 0x44, 0x2f, 0x03, 0xad,
	0xf4, 0x5b, 0x80, 0x36, 0xc7, 0x8d, 0x00, 0x5d, 0x92, 0x77, 0xc9, 0xb5, 0xae, 0x4d, 0x12, 0x70,
	0x59, 0x21, 0x25, 0xe0, 0x1d, 0x01, 0x23, 0xb5, 0xfe, 0x9f, 0x08, 0x8e, 0x0a, 0x61, 0xca, 0x8a,
	0x7f, 0xff, 0x0a, 0x3c, 0x83, 0xf7, 0x4b, 0xeb, 0x09, 0x3e, 0xa5, 0xd5, 0x8b, 0x8f, 0xef, 0xd1,
	0x3b, 0x36, 0x99, 0x77, 0x52, 0x93, 0xd7, 0x4d, 0xb1, 0xdc, 0x7f, 0xfa, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x32, 0x48, 0xb2, 0x19, 0xf3, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CircleMasterServiceClient is the client API for CircleMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CircleMasterServiceClient interface {
	// 创建
	BuildCircle(ctx context.Context, in *BuildCircleRequest, opts ...grpc.CallOption) (*BuildCircleResponse, error)
	// 更新
	UpdateCircle(ctx context.Context, in *UpdateCircleRequest, opts ...grpc.CallOption) (*UpdateCircleResponse, error)
	// 获取列表
	GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error)
	// 删除圈子
	DelCircle(ctx context.Context, in *DelCircleRequest, opts ...grpc.CallOption) (*DelCircleResponse, error)
	// 获取圈子的消息
	GetCircleMessage(ctx context.Context, in *GetCircleMsgRequest, opts ...grpc.CallOption) (*GetCircleMsgResponse, error)
	// 处理圈子消息
	DealMessage(ctx context.Context, in *DealMessageRequest, opts ...grpc.CallOption) (*DealMessageResponse, error)
	// 处理申请
	DealApply(ctx context.Context, in *DealApplyRequest, opts ...grpc.CallOption) (*DealApplyResponse, error)
	// 获取申请
	GetApplyList(ctx context.Context, in *GetApplyListRequest, opts ...grpc.CallOption) (*GetApplyListResponse, error)
}

type circleMasterServiceClient struct {
	cc *grpc.ClientConn
}

func NewCircleMasterServiceClient(cc *grpc.ClientConn) CircleMasterServiceClient {
	return &circleMasterServiceClient{cc}
}

func (c *circleMasterServiceClient) BuildCircle(ctx context.Context, in *BuildCircleRequest, opts ...grpc.CallOption) (*BuildCircleResponse, error) {
	out := new(BuildCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/BuildCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) UpdateCircle(ctx context.Context, in *UpdateCircleRequest, opts ...grpc.CallOption) (*UpdateCircleResponse, error) {
	out := new(UpdateCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/UpdateCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error) {
	out := new(GetCircleListResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetCircleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DelCircle(ctx context.Context, in *DelCircleRequest, opts ...grpc.CallOption) (*DelCircleResponse, error) {
	out := new(DelCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DelCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetCircleMessage(ctx context.Context, in *GetCircleMsgRequest, opts ...grpc.CallOption) (*GetCircleMsgResponse, error) {
	out := new(GetCircleMsgResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetCircleMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DealMessage(ctx context.Context, in *DealMessageRequest, opts ...grpc.CallOption) (*DealMessageResponse, error) {
	out := new(DealMessageResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DealMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DealApply(ctx context.Context, in *DealApplyRequest, opts ...grpc.CallOption) (*DealApplyResponse, error) {
	out := new(DealApplyResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DealApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetApplyList(ctx context.Context, in *GetApplyListRequest, opts ...grpc.CallOption) (*GetApplyListResponse, error) {
	out := new(GetApplyListResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetApplyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CircleMasterServiceServer is the server API for CircleMasterService service.
type CircleMasterServiceServer interface {
	// 创建
	BuildCircle(context.Context, *BuildCircleRequest) (*BuildCircleResponse, error)
	// 更新
	UpdateCircle(context.Context, *UpdateCircleRequest) (*UpdateCircleResponse, error)
	// 获取列表
	GetCircleList(context.Context, *GetCircleListRequest) (*GetCircleListResponse, error)
	// 删除圈子
	DelCircle(context.Context, *DelCircleRequest) (*DelCircleResponse, error)
	// 获取圈子的消息
	GetCircleMessage(context.Context, *GetCircleMsgRequest) (*GetCircleMsgResponse, error)
	// 处理圈子消息
	DealMessage(context.Context, *DealMessageRequest) (*DealMessageResponse, error)
	// 处理申请
	DealApply(context.Context, *DealApplyRequest) (*DealApplyResponse, error)
	// 获取申请
	GetApplyList(context.Context, *GetApplyListRequest) (*GetApplyListResponse, error)
}

func RegisterCircleMasterServiceServer(s *grpc.Server, srv CircleMasterServiceServer) {
	s.RegisterService(&_CircleMasterService_serviceDesc, srv)
}

func _CircleMasterService_BuildCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).BuildCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/BuildCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).BuildCircle(ctx, req.(*BuildCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_UpdateCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).UpdateCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/UpdateCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).UpdateCircle(ctx, req.(*UpdateCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetCircleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetCircleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetCircleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetCircleList(ctx, req.(*GetCircleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DelCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DelCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DelCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DelCircle(ctx, req.(*DelCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetCircleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetCircleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetCircleMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetCircleMessage(ctx, req.(*GetCircleMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DealMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DealMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DealMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DealMessage(ctx, req.(*DealMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DealApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DealApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DealApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DealApply(ctx, req.(*DealApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetApplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetApplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetApplyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetApplyList(ctx, req.(*GetApplyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CircleMasterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CircleMasterService",
	HandlerType: (*CircleMasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildCircle",
			Handler:    _CircleMasterService_BuildCircle_Handler,
		},
		{
			MethodName: "UpdateCircle",
			Handler:    _CircleMasterService_UpdateCircle_Handler,
		},
		{
			MethodName: "GetCircleList",
			Handler:    _CircleMasterService_GetCircleList_Handler,
		},
		{
			MethodName: "DelCircle",
			Handler:    _CircleMasterService_DelCircle_Handler,
		},
		{
			MethodName: "GetCircleMessage",
			Handler:    _CircleMasterService_GetCircleMessage_Handler,
		},
		{
			MethodName: "DealMessage",
			Handler:    _CircleMasterService_DealMessage_Handler,
		},
		{
			MethodName: "DealApply",
			Handler:    _CircleMasterService_DealApply_Handler,
		},
		{
			MethodName: "GetApplyList",
			Handler:    _CircleMasterService_GetApplyList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "circle/circle.proto",
}

// CircleUserServiceClient is the client API for CircleUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CircleUserServiceClient interface {
	// 获取列表
	GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error)
	// 申请加入圈子
	ApplyJoinCircle(ctx context.Context, in *ApplyJoinCircleRequest, opts ...grpc.CallOption) (*ApplyJoinCircleResponse, error)
	// 获取圈子的消息
	GetCircleMessage(ctx context.Context, in *GetCircleMsgRequest, opts ...grpc.CallOption) (*GetCircleMsgResponse, error)
}

type circleUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewCircleUserServiceClient(cc *grpc.ClientConn) CircleUserServiceClient {
	return &circleUserServiceClient{cc}
}

func (c *circleUserServiceClient) GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error) {
	out := new(GetCircleListResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/GetCircleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) ApplyJoinCircle(ctx context.Context, in *ApplyJoinCircleRequest, opts ...grpc.CallOption) (*ApplyJoinCircleResponse, error) {
	out := new(ApplyJoinCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/ApplyJoinCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) GetCircleMessage(ctx context.Context, in *GetCircleMsgRequest, opts ...grpc.CallOption) (*GetCircleMsgResponse, error) {
	out := new(GetCircleMsgResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/GetCircleMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CircleUserServiceServer is the server API for CircleUserService service.
type CircleUserServiceServer interface {
	// 获取列表
	GetCircleList(context.Context, *GetCircleListRequest) (*GetCircleListResponse, error)
	// 申请加入圈子
	ApplyJoinCircle(context.Context, *ApplyJoinCircleRequest) (*ApplyJoinCircleResponse, error)
	// 获取圈子的消息
	GetCircleMessage(context.Context, *GetCircleMsgRequest) (*GetCircleMsgResponse, error)
}

func RegisterCircleUserServiceServer(s *grpc.Server, srv CircleUserServiceServer) {
	s.RegisterService(&_CircleUserService_serviceDesc, srv)
}

func _CircleUserService_GetCircleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).GetCircleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/GetCircleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).GetCircleList(ctx, req.(*GetCircleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_ApplyJoinCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyJoinCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).ApplyJoinCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/ApplyJoinCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).ApplyJoinCircle(ctx, req.(*ApplyJoinCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_GetCircleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).GetCircleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/GetCircleMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).GetCircleMessage(ctx, req.(*GetCircleMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CircleUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CircleUserService",
	HandlerType: (*CircleUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCircleList",
			Handler:    _CircleUserService_GetCircleList_Handler,
		},
		{
			MethodName: "ApplyJoinCircle",
			Handler:    _CircleUserService_ApplyJoinCircle_Handler,
		},
		{
			MethodName: "GetCircleMessage",
			Handler:    _CircleUserService_GetCircleMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "circle/circle.proto",
}
