// Code generated by protoc-gen-go. DO NOT EDIT.
// source: circle/circle.proto

package circle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CircleMsg_Tp int32

const (
	CircleMsg_UNIVERSAL  CircleMsg_Tp = 0
	CircleMsg_JOIN       CircleMsg_Tp = 1
	CircleMsg_QUIT       CircleMsg_Tp = 2
	CircleMsg_KICK       CircleMsg_Tp = 3
	CircleMsg_APPLY      CircleMsg_Tp = 4
	CircleMsg_APPLY_QUIT CircleMsg_Tp = 5
)

var CircleMsg_Tp_name = map[int32]string{
	0: "UNIVERSAL",
	1: "JOIN",
	2: "QUIT",
	3: "KICK",
	4: "APPLY",
	5: "APPLY_QUIT",
}

var CircleMsg_Tp_value = map[string]int32{
	"UNIVERSAL":  0,
	"JOIN":       1,
	"QUIT":       2,
	"KICK":       3,
	"APPLY":      4,
	"APPLY_QUIT": 5,
}

func (x CircleMsg_Tp) String() string {
	return proto.EnumName(CircleMsg_Tp_name, int32(x))
}

func (CircleMsg_Tp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{32, 0}
}

type BuildCircleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Notice               string   `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	U                    *User    `protobuf:"bytes,3,opt,name=u,proto3" json:"u,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildCircleRequest) Reset()         { *m = BuildCircleRequest{} }
func (m *BuildCircleRequest) String() string { return proto.CompactTextString(m) }
func (*BuildCircleRequest) ProtoMessage()    {}
func (*BuildCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{0}
}

func (m *BuildCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildCircleRequest.Unmarshal(m, b)
}
func (m *BuildCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildCircleRequest.Marshal(b, m, deterministic)
}
func (m *BuildCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildCircleRequest.Merge(m, src)
}
func (m *BuildCircleRequest) XXX_Size() int {
	return xxx_messageInfo_BuildCircleRequest.Size(m)
}
func (m *BuildCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildCircleRequest proto.InternalMessageInfo

func (m *BuildCircleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildCircleRequest) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *BuildCircleRequest) GetU() *User {
	if m != nil {
		return m.U
	}
	return nil
}

type BuildCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildCircleResponse) Reset()         { *m = BuildCircleResponse{} }
func (m *BuildCircleResponse) String() string { return proto.CompactTextString(m) }
func (*BuildCircleResponse) ProtoMessage()    {}
func (*BuildCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{1}
}

func (m *BuildCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildCircleResponse.Unmarshal(m, b)
}
func (m *BuildCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildCircleResponse.Marshal(b, m, deterministic)
}
func (m *BuildCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildCircleResponse.Merge(m, src)
}
func (m *BuildCircleResponse) XXX_Size() int {
	return xxx_messageInfo_BuildCircleResponse.Size(m)
}
func (m *BuildCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildCircleResponse proto.InternalMessageInfo

func (m *BuildCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateCircleRequest struct {
	CircleId             int32             `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	OwnerId              int32             `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Update               map[string]string `protobuf:"bytes,3,rep,name=update,proto3" json:"update,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateCircleRequest) Reset()         { *m = UpdateCircleRequest{} }
func (m *UpdateCircleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCircleRequest) ProtoMessage()    {}
func (*UpdateCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{2}
}

func (m *UpdateCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCircleRequest.Unmarshal(m, b)
}
func (m *UpdateCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCircleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCircleRequest.Merge(m, src)
}
func (m *UpdateCircleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCircleRequest.Size(m)
}
func (m *UpdateCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCircleRequest proto.InternalMessageInfo

func (m *UpdateCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *UpdateCircleRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *UpdateCircleRequest) GetUpdate() map[string]string {
	if m != nil {
		return m.Update
	}
	return nil
}

type UpdateCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCircleResponse) Reset()         { *m = UpdateCircleResponse{} }
func (m *UpdateCircleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCircleResponse) ProtoMessage()    {}
func (*UpdateCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{3}
}

func (m *UpdateCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCircleResponse.Unmarshal(m, b)
}
func (m *UpdateCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCircleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCircleResponse.Merge(m, src)
}
func (m *UpdateCircleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCircleResponse.Size(m)
}
func (m *UpdateCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCircleResponse proto.InternalMessageInfo

func (m *UpdateCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetCircleListRequest struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCircleListRequest) Reset()         { *m = GetCircleListRequest{} }
func (m *GetCircleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetCircleListRequest) ProtoMessage()    {}
func (*GetCircleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{4}
}

func (m *GetCircleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleListRequest.Unmarshal(m, b)
}
func (m *GetCircleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleListRequest.Marshal(b, m, deterministic)
}
func (m *GetCircleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleListRequest.Merge(m, src)
}
func (m *GetCircleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetCircleListRequest.Size(m)
}
func (m *GetCircleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleListRequest proto.InternalMessageInfo

func (m *GetCircleListRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetCircleListResponse struct {
	Circles              []*Circle `protobuf:"bytes,1,rep,name=circles,proto3" json:"circles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCircleListResponse) Reset()         { *m = GetCircleListResponse{} }
func (m *GetCircleListResponse) String() string { return proto.CompactTextString(m) }
func (*GetCircleListResponse) ProtoMessage()    {}
func (*GetCircleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{5}
}

func (m *GetCircleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleListResponse.Unmarshal(m, b)
}
func (m *GetCircleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleListResponse.Marshal(b, m, deterministic)
}
func (m *GetCircleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleListResponse.Merge(m, src)
}
func (m *GetCircleListResponse) XXX_Size() int {
	return xxx_messageInfo_GetCircleListResponse.Size(m)
}
func (m *GetCircleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleListResponse proto.InternalMessageInfo

func (m *GetCircleListResponse) GetCircles() []*Circle {
	if m != nil {
		return m.Circles
	}
	return nil
}

type DelCircleRequest struct {
	OwnerId              int32    `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	CircleId             int32    `protobuf:"varint,2,opt,name=circleId,proto3" json:"circleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCircleRequest) Reset()         { *m = DelCircleRequest{} }
func (m *DelCircleRequest) String() string { return proto.CompactTextString(m) }
func (*DelCircleRequest) ProtoMessage()    {}
func (*DelCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{6}
}

func (m *DelCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCircleRequest.Unmarshal(m, b)
}
func (m *DelCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCircleRequest.Marshal(b, m, deterministic)
}
func (m *DelCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCircleRequest.Merge(m, src)
}
func (m *DelCircleRequest) XXX_Size() int {
	return xxx_messageInfo_DelCircleRequest.Size(m)
}
func (m *DelCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelCircleRequest proto.InternalMessageInfo

func (m *DelCircleRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DelCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type DelCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCircleResponse) Reset()         { *m = DelCircleResponse{} }
func (m *DelCircleResponse) String() string { return proto.CompactTextString(m) }
func (*DelCircleResponse) ProtoMessage()    {}
func (*DelCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{7}
}

func (m *DelCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCircleResponse.Unmarshal(m, b)
}
func (m *DelCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCircleResponse.Marshal(b, m, deterministic)
}
func (m *DelCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCircleResponse.Merge(m, src)
}
func (m *DelCircleResponse) XXX_Size() int {
	return xxx_messageInfo_DelCircleResponse.Size(m)
}
func (m *DelCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelCircleResponse proto.InternalMessageInfo

func (m *DelCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ApplyJoinCircleRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyJoinCircleRequest) Reset()         { *m = ApplyJoinCircleRequest{} }
func (m *ApplyJoinCircleRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyJoinCircleRequest) ProtoMessage()    {}
func (*ApplyJoinCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{8}
}

func (m *ApplyJoinCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyJoinCircleRequest.Unmarshal(m, b)
}
func (m *ApplyJoinCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyJoinCircleRequest.Marshal(b, m, deterministic)
}
func (m *ApplyJoinCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyJoinCircleRequest.Merge(m, src)
}
func (m *ApplyJoinCircleRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyJoinCircleRequest.Size(m)
}
func (m *ApplyJoinCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyJoinCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyJoinCircleRequest proto.InternalMessageInfo

func (m *ApplyJoinCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *ApplyJoinCircleRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ApplyJoinCircleResponse struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              *CircleMsg `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ApplyJoinCircleResponse) Reset()         { *m = ApplyJoinCircleResponse{} }
func (m *ApplyJoinCircleResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyJoinCircleResponse) ProtoMessage()    {}
func (*ApplyJoinCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{9}
}

func (m *ApplyJoinCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyJoinCircleResponse.Unmarshal(m, b)
}
func (m *ApplyJoinCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyJoinCircleResponse.Marshal(b, m, deterministic)
}
func (m *ApplyJoinCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyJoinCircleResponse.Merge(m, src)
}
func (m *ApplyJoinCircleResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyJoinCircleResponse.Size(m)
}
func (m *ApplyJoinCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyJoinCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyJoinCircleResponse proto.InternalMessageInfo

func (m *ApplyJoinCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ApplyJoinCircleResponse) GetMessage() *CircleMsg {
	if m != nil {
		return m.Message
	}
	return nil
}

type GetCircleLogRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCircleLogRequest) Reset()         { *m = GetCircleLogRequest{} }
func (m *GetCircleLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetCircleLogRequest) ProtoMessage()    {}
func (*GetCircleLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{10}
}

func (m *GetCircleLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleLogRequest.Unmarshal(m, b)
}
func (m *GetCircleLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleLogRequest.Marshal(b, m, deterministic)
}
func (m *GetCircleLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleLogRequest.Merge(m, src)
}
func (m *GetCircleLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetCircleLogRequest.Size(m)
}
func (m *GetCircleLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleLogRequest proto.InternalMessageInfo

func (m *GetCircleLogRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GetCircleLogRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCircleLogRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCircleLogRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetCircleLogResponse struct {
	ApplyMsgs            []*CircleMsg `protobuf:"bytes,1,rep,name=applyMsgs,proto3" json:"applyMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCircleLogResponse) Reset()         { *m = GetCircleLogResponse{} }
func (m *GetCircleLogResponse) String() string { return proto.CompactTextString(m) }
func (*GetCircleLogResponse) ProtoMessage()    {}
func (*GetCircleLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{11}
}

func (m *GetCircleLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleLogResponse.Unmarshal(m, b)
}
func (m *GetCircleLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleLogResponse.Marshal(b, m, deterministic)
}
func (m *GetCircleLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleLogResponse.Merge(m, src)
}
func (m *GetCircleLogResponse) XXX_Size() int {
	return xxx_messageInfo_GetCircleLogResponse.Size(m)
}
func (m *GetCircleLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleLogResponse proto.InternalMessageInfo

func (m *GetCircleLogResponse) GetApplyMsgs() []*CircleMsg {
	if m != nil {
		return m.ApplyMsgs
	}
	return nil
}

type DealApplyRequest struct {
	U                    *User    `protobuf:"bytes,1,opt,name=u,proto3" json:"u,omitempty"`
	CircleId             int32    `protobuf:"varint,2,opt,name=circleId,proto3" json:"circleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	MsgId                int32    `protobuf:"varint,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	UserId               int32    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Agree                bool     `protobuf:"varint,6,opt,name=agree,proto3" json:"agree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealApplyRequest) Reset()         { *m = DealApplyRequest{} }
func (m *DealApplyRequest) String() string { return proto.CompactTextString(m) }
func (*DealApplyRequest) ProtoMessage()    {}
func (*DealApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{12}
}

func (m *DealApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealApplyRequest.Unmarshal(m, b)
}
func (m *DealApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealApplyRequest.Marshal(b, m, deterministic)
}
func (m *DealApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealApplyRequest.Merge(m, src)
}
func (m *DealApplyRequest) XXX_Size() int {
	return xxx_messageInfo_DealApplyRequest.Size(m)
}
func (m *DealApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealApplyRequest proto.InternalMessageInfo

func (m *DealApplyRequest) GetU() *User {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *DealApplyRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *DealApplyRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DealApplyRequest) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *DealApplyRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DealApplyRequest) GetAgree() bool {
	if m != nil {
		return m.Agree
	}
	return false
}

type DealApplyResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User                 *CircleUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DealApplyResponse) Reset()         { *m = DealApplyResponse{} }
func (m *DealApplyResponse) String() string { return proto.CompactTextString(m) }
func (*DealApplyResponse) ProtoMessage()    {}
func (*DealApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{13}
}

func (m *DealApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealApplyResponse.Unmarshal(m, b)
}
func (m *DealApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealApplyResponse.Marshal(b, m, deterministic)
}
func (m *DealApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealApplyResponse.Merge(m, src)
}
func (m *DealApplyResponse) XXX_Size() int {
	return xxx_messageInfo_DealApplyResponse.Size(m)
}
func (m *DealApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DealApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DealApplyResponse proto.InternalMessageInfo

func (m *DealApplyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DealApplyResponse) GetUser() *CircleUser {
	if m != nil {
		return m.User
	}
	return nil
}

type DealMessageRequest struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	CircleId             int32    `protobuf:"varint,3,opt,name=circleId,proto3" json:"circleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealMessageRequest) Reset()         { *m = DealMessageRequest{} }
func (m *DealMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DealMessageRequest) ProtoMessage()    {}
func (*DealMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{14}
}

func (m *DealMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealMessageRequest.Unmarshal(m, b)
}
func (m *DealMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealMessageRequest.Marshal(b, m, deterministic)
}
func (m *DealMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealMessageRequest.Merge(m, src)
}
func (m *DealMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DealMessageRequest.Size(m)
}
func (m *DealMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealMessageRequest proto.InternalMessageInfo

func (m *DealMessageRequest) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *DealMessageRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DealMessageRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type DealMessageResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealMessageResponse) Reset()         { *m = DealMessageResponse{} }
func (m *DealMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DealMessageResponse) ProtoMessage()    {}
func (*DealMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{15}
}

func (m *DealMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealMessageResponse.Unmarshal(m, b)
}
func (m *DealMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealMessageResponse.Marshal(b, m, deterministic)
}
func (m *DealMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealMessageResponse.Merge(m, src)
}
func (m *DealMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DealMessageResponse.Size(m)
}
func (m *DealMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DealMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DealMessageResponse proto.InternalMessageInfo

func (m *DealMessageResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetApplyListRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplyListRequest) Reset()         { *m = GetApplyListRequest{} }
func (m *GetApplyListRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplyListRequest) ProtoMessage()    {}
func (*GetApplyListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{16}
}

func (m *GetApplyListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyListRequest.Unmarshal(m, b)
}
func (m *GetApplyListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyListRequest.Marshal(b, m, deterministic)
}
func (m *GetApplyListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyListRequest.Merge(m, src)
}
func (m *GetApplyListRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplyListRequest.Size(m)
}
func (m *GetApplyListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyListRequest proto.InternalMessageInfo

func (m *GetApplyListRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GetApplyListRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetApplyListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetApplyListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetApplyListResponse struct {
	ApplyMsgs            []*CircleMsg `protobuf:"bytes,1,rep,name=applyMsgs,proto3" json:"applyMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetApplyListResponse) Reset()         { *m = GetApplyListResponse{} }
func (m *GetApplyListResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplyListResponse) ProtoMessage()    {}
func (*GetApplyListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{17}
}

func (m *GetApplyListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyListResponse.Unmarshal(m, b)
}
func (m *GetApplyListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyListResponse.Marshal(b, m, deterministic)
}
func (m *GetApplyListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyListResponse.Merge(m, src)
}
func (m *GetApplyListResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplyListResponse.Size(m)
}
func (m *GetApplyListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyListResponse proto.InternalMessageInfo

func (m *GetApplyListResponse) GetApplyMsgs() []*CircleMsg {
	if m != nil {
		return m.ApplyMsgs
	}
	return nil
}

type GetQuiteListRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuiteListRequest) Reset()         { *m = GetQuiteListRequest{} }
func (m *GetQuiteListRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuiteListRequest) ProtoMessage()    {}
func (*GetQuiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{18}
}

func (m *GetQuiteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuiteListRequest.Unmarshal(m, b)
}
func (m *GetQuiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuiteListRequest.Marshal(b, m, deterministic)
}
func (m *GetQuiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuiteListRequest.Merge(m, src)
}
func (m *GetQuiteListRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuiteListRequest.Size(m)
}
func (m *GetQuiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuiteListRequest proto.InternalMessageInfo

func (m *GetQuiteListRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GetQuiteListRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetQuiteListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetQuiteListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetQuiteListResponse struct {
	ApplyMsgs            []*CircleMsg `protobuf:"bytes,1,rep,name=applyMsgs,proto3" json:"applyMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetQuiteListResponse) Reset()         { *m = GetQuiteListResponse{} }
func (m *GetQuiteListResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuiteListResponse) ProtoMessage()    {}
func (*GetQuiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{19}
}

func (m *GetQuiteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuiteListResponse.Unmarshal(m, b)
}
func (m *GetQuiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuiteListResponse.Marshal(b, m, deterministic)
}
func (m *GetQuiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuiteListResponse.Merge(m, src)
}
func (m *GetQuiteListResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuiteListResponse.Size(m)
}
func (m *GetQuiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuiteListResponse proto.InternalMessageInfo

func (m *GetQuiteListResponse) GetApplyMsgs() []*CircleMsg {
	if m != nil {
		return m.ApplyMsgs
	}
	return nil
}

type DealQuitRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	MsgId                int32    `protobuf:"varint,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Agree                bool     `protobuf:"varint,5,opt,name=agree,proto3" json:"agree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealQuitRequest) Reset()         { *m = DealQuitRequest{} }
func (m *DealQuitRequest) String() string { return proto.CompactTextString(m) }
func (*DealQuitRequest) ProtoMessage()    {}
func (*DealQuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{20}
}

func (m *DealQuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealQuitRequest.Unmarshal(m, b)
}
func (m *DealQuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealQuitRequest.Marshal(b, m, deterministic)
}
func (m *DealQuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealQuitRequest.Merge(m, src)
}
func (m *DealQuitRequest) XXX_Size() int {
	return xxx_messageInfo_DealQuitRequest.Size(m)
}
func (m *DealQuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealQuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealQuitRequest proto.InternalMessageInfo

func (m *DealQuitRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *DealQuitRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *DealQuitRequest) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *DealQuitRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DealQuitRequest) GetAgree() bool {
	if m != nil {
		return m.Agree
	}
	return false
}

type DealQuitResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User                 *CircleUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DealQuitResponse) Reset()         { *m = DealQuitResponse{} }
func (m *DealQuitResponse) String() string { return proto.CompactTextString(m) }
func (*DealQuitResponse) ProtoMessage()    {}
func (*DealQuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{21}
}

func (m *DealQuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealQuitResponse.Unmarshal(m, b)
}
func (m *DealQuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealQuitResponse.Marshal(b, m, deterministic)
}
func (m *DealQuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealQuitResponse.Merge(m, src)
}
func (m *DealQuitResponse) XXX_Size() int {
	return xxx_messageInfo_DealQuitResponse.Size(m)
}
func (m *DealQuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DealQuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DealQuitResponse proto.InternalMessageInfo

func (m *DealQuitResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DealQuitResponse) GetUser() *CircleUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ApplyQuitCircleRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyQuitCircleRequest) Reset()         { *m = ApplyQuitCircleRequest{} }
func (m *ApplyQuitCircleRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyQuitCircleRequest) ProtoMessage()    {}
func (*ApplyQuitCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{22}
}

func (m *ApplyQuitCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyQuitCircleRequest.Unmarshal(m, b)
}
func (m *ApplyQuitCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyQuitCircleRequest.Marshal(b, m, deterministic)
}
func (m *ApplyQuitCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyQuitCircleRequest.Merge(m, src)
}
func (m *ApplyQuitCircleRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyQuitCircleRequest.Size(m)
}
func (m *ApplyQuitCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyQuitCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyQuitCircleRequest proto.InternalMessageInfo

func (m *ApplyQuitCircleRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *ApplyQuitCircleRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type ApplyQuitCircleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyQuitCircleResponse) Reset()         { *m = ApplyQuitCircleResponse{} }
func (m *ApplyQuitCircleResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyQuitCircleResponse) ProtoMessage()    {}
func (*ApplyQuitCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{23}
}

func (m *ApplyQuitCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyQuitCircleResponse.Unmarshal(m, b)
}
func (m *ApplyQuitCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyQuitCircleResponse.Marshal(b, m, deterministic)
}
func (m *ApplyQuitCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyQuitCircleResponse.Merge(m, src)
}
func (m *ApplyQuitCircleResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyQuitCircleResponse.Size(m)
}
func (m *ApplyQuitCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyQuitCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyQuitCircleResponse proto.InternalMessageInfo

func (m *ApplyQuitCircleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GerCircleDetailRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GerCircleDetailRequest) Reset()         { *m = GerCircleDetailRequest{} }
func (m *GerCircleDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GerCircleDetailRequest) ProtoMessage()    {}
func (*GerCircleDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{24}
}

func (m *GerCircleDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GerCircleDetailRequest.Unmarshal(m, b)
}
func (m *GerCircleDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GerCircleDetailRequest.Marshal(b, m, deterministic)
}
func (m *GerCircleDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GerCircleDetailRequest.Merge(m, src)
}
func (m *GerCircleDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GerCircleDetailRequest.Size(m)
}
func (m *GerCircleDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GerCircleDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GerCircleDetailRequest proto.InternalMessageInfo

func (m *GerCircleDetailRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type GerCircleDetailResponse struct {
	OwnerId              int32    `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	CreateAt             string   `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             string   `protobuf:"bytes,3,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CircleId             int32    `protobuf:"varint,5,opt,name=circleId,proto3" json:"circleId,omitempty"`
	MemberCount          int32    `protobuf:"varint,6,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	RoomCard             int32    `protobuf:"varint,7,opt,name=roomCard,proto3" json:"roomCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GerCircleDetailResponse) Reset()         { *m = GerCircleDetailResponse{} }
func (m *GerCircleDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GerCircleDetailResponse) ProtoMessage()    {}
func (*GerCircleDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{25}
}

func (m *GerCircleDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GerCircleDetailResponse.Unmarshal(m, b)
}
func (m *GerCircleDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GerCircleDetailResponse.Marshal(b, m, deterministic)
}
func (m *GerCircleDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GerCircleDetailResponse.Merge(m, src)
}
func (m *GerCircleDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GerCircleDetailResponse.Size(m)
}
func (m *GerCircleDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GerCircleDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GerCircleDetailResponse proto.InternalMessageInfo

func (m *GerCircleDetailResponse) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GerCircleDetailResponse) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *GerCircleDetailResponse) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *GerCircleDetailResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GerCircleDetailResponse) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GerCircleDetailResponse) GetMemberCount() int32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *GerCircleDetailResponse) GetRoomCard() int32 {
	if m != nil {
		return m.RoomCard
	}
	return 0
}

type GetCircleMembersRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	OwnerId              int32    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCircleMembersRequest) Reset()         { *m = GetCircleMembersRequest{} }
func (m *GetCircleMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GetCircleMembersRequest) ProtoMessage()    {}
func (*GetCircleMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{26}
}

func (m *GetCircleMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleMembersRequest.Unmarshal(m, b)
}
func (m *GetCircleMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleMembersRequest.Marshal(b, m, deterministic)
}
func (m *GetCircleMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleMembersRequest.Merge(m, src)
}
func (m *GetCircleMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GetCircleMembersRequest.Size(m)
}
func (m *GetCircleMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleMembersRequest proto.InternalMessageInfo

func (m *GetCircleMembersRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *GetCircleMembersRequest) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type GetCircleMembersResponse struct {
	Users                []*CircleUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCircleMembersResponse) Reset()         { *m = GetCircleMembersResponse{} }
func (m *GetCircleMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GetCircleMembersResponse) ProtoMessage()    {}
func (*GetCircleMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{27}
}

func (m *GetCircleMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleMembersResponse.Unmarshal(m, b)
}
func (m *GetCircleMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleMembersResponse.Marshal(b, m, deterministic)
}
func (m *GetCircleMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleMembersResponse.Merge(m, src)
}
func (m *GetCircleMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GetCircleMembersResponse.Size(m)
}
func (m *GetCircleMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleMembersResponse proto.InternalMessageInfo

func (m *GetCircleMembersResponse) GetUsers() []*CircleUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetCircleInfoRequest struct {
	CircleId             int32    `protobuf:"varint,1,opt,name=circleId,proto3" json:"circleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCircleInfoRequest) Reset()         { *m = GetCircleInfoRequest{} }
func (m *GetCircleInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCircleInfoRequest) ProtoMessage()    {}
func (*GetCircleInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{28}
}

func (m *GetCircleInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleInfoRequest.Unmarshal(m, b)
}
func (m *GetCircleInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetCircleInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleInfoRequest.Merge(m, src)
}
func (m *GetCircleInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCircleInfoRequest.Size(m)
}
func (m *GetCircleInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleInfoRequest proto.InternalMessageInfo

func (m *GetCircleInfoRequest) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

type GetCircleInfoResponse struct {
	Circle               *Circle       `protobuf:"bytes,1,opt,name=circle,proto3" json:"circle,omitempty"`
	Users                []*CircleUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCircleInfoResponse) Reset()         { *m = GetCircleInfoResponse{} }
func (m *GetCircleInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetCircleInfoResponse) ProtoMessage()    {}
func (*GetCircleInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{29}
}

func (m *GetCircleInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCircleInfoResponse.Unmarshal(m, b)
}
func (m *GetCircleInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCircleInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetCircleInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCircleInfoResponse.Merge(m, src)
}
func (m *GetCircleInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetCircleInfoResponse.Size(m)
}
func (m *GetCircleInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCircleInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCircleInfoResponse proto.InternalMessageInfo

func (m *GetCircleInfoResponse) GetCircle() *Circle {
	if m != nil {
		return m.Circle
	}
	return nil
}

func (m *GetCircleInfoResponse) GetUsers() []*CircleUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type CircleUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImgUrl               string   `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	JoinAt               string   `protobuf:"bytes,5,opt,name=joinAt,proto3" json:"joinAt,omitempty"`
	CircleId             int32    `protobuf:"varint,6,opt,name=circleId,proto3" json:"circleId,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	TotalGameCount       int32    `protobuf:"varint,8,opt,name=totalGameCount,proto3" json:"totalGameCount,omitempty"`
	PreGameCount         int32    `protobuf:"varint,9,opt,name=preGameCount,proto3" json:"preGameCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleUser) Reset()         { *m = CircleUser{} }
func (m *CircleUser) String() string { return proto.CompactTextString(m) }
func (*CircleUser) ProtoMessage()    {}
func (*CircleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{30}
}

func (m *CircleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleUser.Unmarshal(m, b)
}
func (m *CircleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleUser.Marshal(b, m, deterministic)
}
func (m *CircleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleUser.Merge(m, src)
}
func (m *CircleUser) XXX_Size() int {
	return xxx_messageInfo_CircleUser.Size(m)
}
func (m *CircleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleUser.DiscardUnknown(m)
}

var xxx_messageInfo_CircleUser proto.InternalMessageInfo

func (m *CircleUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CircleUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CircleUser) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *CircleUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CircleUser) GetJoinAt() string {
	if m != nil {
		return m.JoinAt
	}
	return ""
}

func (m *CircleUser) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *CircleUser) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CircleUser) GetTotalGameCount() int32 {
	if m != nil {
		return m.TotalGameCount
	}
	return 0
}

func (m *CircleUser) GetPreGameCount() int32 {
	if m != nil {
		return m.PreGameCount
	}
	return 0
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImgUrl               string   `protobuf:"bytes,2,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{31}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CircleMsg struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	T                    CircleMsg_Tp `protobuf:"varint,3,opt,name=t,proto3,enum=CircleMsg_Tp" json:"t,omitempty"`
	UpdateAt             string       `protobuf:"bytes,4,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	CreateAt             string       `protobuf:"bytes,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UserId               int32        `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	U                    *User        `protobuf:"bytes,7,opt,name=u,proto3" json:"u,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CircleMsg) Reset()         { *m = CircleMsg{} }
func (m *CircleMsg) String() string { return proto.CompactTextString(m) }
func (*CircleMsg) ProtoMessage()    {}
func (*CircleMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{32}
}

func (m *CircleMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleMsg.Unmarshal(m, b)
}
func (m *CircleMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleMsg.Marshal(b, m, deterministic)
}
func (m *CircleMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleMsg.Merge(m, src)
}
func (m *CircleMsg) XXX_Size() int {
	return xxx_messageInfo_CircleMsg.Size(m)
}
func (m *CircleMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CircleMsg proto.InternalMessageInfo

func (m *CircleMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CircleMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CircleMsg) GetT() CircleMsg_Tp {
	if m != nil {
		return m.T
	}
	return CircleMsg_UNIVERSAL
}

func (m *CircleMsg) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *CircleMsg) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *CircleMsg) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CircleMsg) GetU() *User {
	if m != nil {
		return m.U
	}
	return nil
}

type Circle struct {
	OwnerId  int32  `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	CreateAt string `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt string `protobuf:"bytes,3,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	//    string Notice = 4;
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CircleId             int32    `protobuf:"varint,5,opt,name=circleId,proto3" json:"circleId,omitempty"`
	MemberCount          int32    `protobuf:"varint,6,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circle) Reset()         { *m = Circle{} }
func (m *Circle) String() string { return proto.CompactTextString(m) }
func (*Circle) ProtoMessage()    {}
func (*Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5c720f4490ca94, []int{33}
}

func (m *Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circle.Unmarshal(m, b)
}
func (m *Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circle.Marshal(b, m, deterministic)
}
func (m *Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circle.Merge(m, src)
}
func (m *Circle) XXX_Size() int {
	return xxx_messageInfo_Circle.Size(m)
}
func (m *Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Circle proto.InternalMessageInfo

func (m *Circle) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Circle) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Circle) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *Circle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Circle) GetCircleId() int32 {
	if m != nil {
		return m.CircleId
	}
	return 0
}

func (m *Circle) GetMemberCount() int32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("CircleMsg_Tp", CircleMsg_Tp_name, CircleMsg_Tp_value)
	proto.RegisterType((*BuildCircleRequest)(nil), "BuildCircleRequest")
	proto.RegisterType((*BuildCircleResponse)(nil), "BuildCircleResponse")
	proto.RegisterType((*UpdateCircleRequest)(nil), "UpdateCircleRequest")
	proto.RegisterMapType((map[string]string)(nil), "UpdateCircleRequest.UpdateEntry")
	proto.RegisterType((*UpdateCircleResponse)(nil), "UpdateCircleResponse")
	proto.RegisterType((*GetCircleListRequest)(nil), "GetCircleListRequest")
	proto.RegisterType((*GetCircleListResponse)(nil), "GetCircleListResponse")
	proto.RegisterType((*DelCircleRequest)(nil), "DelCircleRequest")
	proto.RegisterType((*DelCircleResponse)(nil), "DelCircleResponse")
	proto.RegisterType((*ApplyJoinCircleRequest)(nil), "ApplyJoinCircleRequest")
	proto.RegisterType((*ApplyJoinCircleResponse)(nil), "ApplyJoinCircleResponse")
	proto.RegisterType((*GetCircleLogRequest)(nil), "GetCircleLogRequest")
	proto.RegisterType((*GetCircleLogResponse)(nil), "GetCircleLogResponse")
	proto.RegisterType((*DealApplyRequest)(nil), "DealApplyRequest")
	proto.RegisterType((*DealApplyResponse)(nil), "DealApplyResponse")
	proto.RegisterType((*DealMessageRequest)(nil), "DealMessageRequest")
	proto.RegisterType((*DealMessageResponse)(nil), "DealMessageResponse")
	proto.RegisterType((*GetApplyListRequest)(nil), "GetApplyListRequest")
	proto.RegisterType((*GetApplyListResponse)(nil), "GetApplyListResponse")
	proto.RegisterType((*GetQuiteListRequest)(nil), "GetQuiteListRequest")
	proto.RegisterType((*GetQuiteListResponse)(nil), "GetQuiteListResponse")
	proto.RegisterType((*DealQuitRequest)(nil), "DealQuitRequest")
	proto.RegisterType((*DealQuitResponse)(nil), "DealQuitResponse")
	proto.RegisterType((*ApplyQuitCircleRequest)(nil), "ApplyQuitCircleRequest")
	proto.RegisterType((*ApplyQuitCircleResponse)(nil), "ApplyQuitCircleResponse")
	proto.RegisterType((*GerCircleDetailRequest)(nil), "GerCircleDetailRequest")
	proto.RegisterType((*GerCircleDetailResponse)(nil), "GerCircleDetailResponse")
	proto.RegisterType((*GetCircleMembersRequest)(nil), "GetCircleMembersRequest")
	proto.RegisterType((*GetCircleMembersResponse)(nil), "GetCircleMembersResponse")
	proto.RegisterType((*GetCircleInfoRequest)(nil), "GetCircleInfoRequest")
	proto.RegisterType((*GetCircleInfoResponse)(nil), "GetCircleInfoResponse")
	proto.RegisterType((*CircleUser)(nil), "CircleUser")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CircleMsg)(nil), "CircleMsg")
	proto.RegisterType((*Circle)(nil), "Circle")
}

func init() { proto.RegisterFile("circle/circle.proto", fileDescriptor_bb5c720f4490ca94) }

var fileDescriptor_bb5c720f4490ca94 = []byte{
	// 1294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x49, 0x51, 0xb2, 0x46, 0xb1, 0x23, 0xaf, 0x64, 0x99, 0x61, 0x0f, 0x71, 0x17, 0x45,
	0xe1, 0x4b, 0xd7, 0xad, 0x92, 0x43, 0x6a, 0x20, 0x40, 0x14, 0x27, 0x71, 0x95, 0xf8, 0x27, 0x61,
	0xac, 0x02, 0x41, 0x0f, 0x2d, 0x23, 0x6d, 0x05, 0x36, 0x92, 0xa8, 0xf2, 0x27, 0x85, 0x1f, 0xa0,
	0xa7, 0x3e, 0x45, 0xef, 0xbd, 0xf7, 0xda, 0xd7, 0xe8, 0x93, 0xb4, 0xc7, 0x62, 0x7f, 0x48, 0x2e,
	0x29, 0x2a, 0x72, 0xea, 0xa2, 0x40, 0x4e, 0xe6, 0xac, 0x76, 0x67, 0xe7, 0xe7, 0x9b, 0xd9, 0x6f,
	0x0c, 0xed, 0x91, 0x17, 0x8c, 0xa6, 0xf4, 0x40, 0xfc, 0x21, 0x8b, 0xc0, 0x8f, 0x7c, 0x3c, 0x04,
	0xf4, 0x30, 0xf6, 0xa6, 0xe3, 0x23, 0xbe, 0xe8, 0xd0, 0x1f, 0x63, 0x1a, 0x46, 0x08, 0x41, 0x75,
	0xee, 0xce, 0xa8, 0xa5, 0xed, 0x69, 0xfb, 0x0d, 0x87, 0x7f, 0xa3, 0x2e, 0xd4, 0xe6, 0x7e, 0xe4,
	0x8d, 0xa8, 0xa5, 0xf3, 0x55, 0x29, 0xa1, 0x36, 0x68, 0xb1, 0x65, 0xec, 0x69, 0xfb, 0xcd, 0x9e,
	0x49, 0x86, 0x21, 0x0d, 0x1c, 0x2d, 0xc6, 0x07, 0xd0, 0xce, 0xa9, 0x0d, 0x17, 0xfe, 0x3c, 0xa4,
	0xc8, 0x82, 0x7a, 0x18, 0x8f, 0x46, 0x34, 0x0c, 0xb9, 0xea, 0x0d, 0x27, 0x11, 0xf1, 0x1f, 0x1a,
	0xb4, 0x87, 0x8b, 0xb1, 0x1b, 0xd1, 0xbc, 0x25, 0x36, 0x6c, 0x08, 0x7b, 0x07, 0x63, 0x7e, 0xc4,
	0x74, 0x52, 0x99, 0x69, 0xf3, 0x7f, 0x9a, 0xd3, 0x60, 0x30, 0xe6, 0x26, 0x99, 0x4e, 0x22, 0xa2,
	0x7b, 0x50, 0x8b, 0xb9, 0x32, 0xcb, 0xd8, 0x33, 0xf6, 0x9b, 0xbd, 0x3d, 0x52, 0xa2, 0x5b, 0xae,
	0x3d, 0x9e, 0x47, 0xc1, 0xa5, 0x23, 0xf7, 0xdb, 0x5f, 0x42, 0x53, 0x59, 0x46, 0x2d, 0x30, 0xde,
	0xd0, 0x4b, 0x19, 0x07, 0xf6, 0x89, 0x3a, 0x60, 0xbe, 0x75, 0xa7, 0x71, 0x12, 0x05, 0x21, 0x1c,
	0xea, 0xf7, 0x34, 0xfc, 0x39, 0x74, 0xf2, 0xb7, 0xac, 0x75, 0x7a, 0x1f, 0x3a, 0xc7, 0x34, 0x12,
	0xdb, 0x4f, 0xbc, 0x30, 0x4a, 0x9c, 0x6e, 0x81, 0x11, 0x7b, 0x89, 0xbf, 0xec, 0x13, 0x1f, 0xc2,
	0x4e, 0x61, 0xa7, 0x54, 0xfe, 0x31, 0xd4, 0x45, 0x3c, 0x98, 0x72, 0xe6, 0x6a, 0x9d, 0xc8, 0xeb,
	0x93, 0x75, 0xfc, 0x15, 0xb4, 0x1e, 0xd1, 0x69, 0x3e, 0xac, 0x4a, 0xe8, 0xb4, 0x7c, 0xe8, 0xd4,
	0x80, 0xeb, 0xf9, 0x80, 0xe3, 0xcf, 0x60, 0x5b, 0xd1, 0xb4, 0xd6, 0xbd, 0x73, 0xe8, 0xf6, 0x17,
	0x8b, 0xe9, 0xe5, 0x53, 0xdf, 0x9b, 0x5f, 0x3d, 0xab, 0xb7, 0xa0, 0x1a, 0x87, 0x34, 0xe0, 0x97,
	0xa7, 0x90, 0xe2, 0x4b, 0xf8, 0x15, 0xec, 0x2e, 0x29, 0x5c, 0x67, 0x05, 0xfa, 0x04, 0xea, 0x33,
	0x1a, 0x86, 0xee, 0x84, 0x4a, 0x95, 0x20, 0x23, 0x74, 0x1a, 0x4e, 0x9c, 0xe4, 0x27, 0x1c, 0x42,
	0x3b, 0x0b, 0xb0, 0x3f, 0xb9, 0x8a, 0xa1, 0x08, 0xaa, 0x8b, 0x44, 0xab, 0xe9, 0xf0, 0x6f, 0x86,
	0x8e, 0xa9, 0x37, 0xf3, 0x22, 0x5e, 0x10, 0xa6, 0x23, 0x04, 0x56, 0x3a, 0xcc, 0xfe, 0xc1, 0xd8,
	0xaa, 0xf2, 0x65, 0x29, 0xe1, 0x07, 0x6a, 0xfe, 0xd9, 0xa5, 0xd2, 0x99, 0x7d, 0x68, 0xb8, 0xcc,
	0xcf, 0xd3, 0x70, 0x92, 0xa4, 0x55, 0x35, 0x3a, 0xfb, 0x11, 0xff, 0xaa, 0xb1, 0xe4, 0xba, 0x53,
	0x1e, 0x96, 0xc4, 0x68, 0x5e, 0x91, 0x5a, 0xbe, 0x22, 0xdf, 0x95, 0x57, 0x15, 0x0d, 0x46, 0x1e,
	0x0d, 0x1d, 0x30, 0x67, 0xe1, 0x24, 0x35, 0x5c, 0x08, 0x8a, 0x3f, 0xa6, 0xea, 0x0f, 0xdb, 0xed,
	0x4e, 0x02, 0x4a, 0xad, 0x1a, 0x4f, 0x81, 0x10, 0xf0, 0x19, 0x43, 0x4d, 0x6a, 0xe2, 0xda, 0x7c,
	0xdd, 0xce, 0xe5, 0xbf, 0x29, 0xfd, 0x56, 0x50, 0xf0, 0x1d, 0x20, 0xa6, 0xef, 0x54, 0x64, 0x2e,
	0x71, 0x3a, 0xb5, 0x54, 0x53, 0x2d, 0x5d, 0xdd, 0x22, 0xd4, 0x78, 0x18, 0x05, 0x9c, 0x1f, 0x40,
	0x3b, 0x77, 0xc3, 0x5a, 0xa4, 0xc7, 0x1c, 0x3d, 0xdc, 0x43, 0xb5, 0x8e, 0xff, 0x5d, 0xf3, 0x4a,
	0x70, 0x65, 0x94, 0xe1, 0xaa, 0xaa, 0xe0, 0x4a, 0xe2, 0x47, 0xb9, 0xf6, 0xbd, 0xf1, 0x23, 0x0c,
	0x7f, 0x11, 0x7b, 0x11, 0xfd, 0xff, 0x0d, 0x57, 0xae, 0x7d, 0x6f, 0xc3, 0x7f, 0xd1, 0xe0, 0x26,
	0xcb, 0x11, 0xd3, 0x71, 0x3d, 0xab, 0x53, 0xe0, 0x18, 0xe5, 0x10, 0xaf, 0x96, 0x43, 0xdc, 0x54,
	0x21, 0x7e, 0x2a, 0xaa, 0x50, 0x18, 0x73, 0x7d, 0x84, 0x3f, 0x91, 0x8d, 0x93, 0xe9, 0xbb, 0x7a,
	0xe3, 0x94, 0xaf, 0x86, 0x9e, 0xbd, 0x1a, 0x77, 0x64, 0xbf, 0x54, 0xf5, 0xac, 0xc5, 0xf2, 0x5d,
	0xe8, 0x1e, 0xd3, 0x40, 0x6c, 0x7f, 0x44, 0x23, 0xd7, 0x9b, 0x5e, 0xe1, 0x72, 0xfc, 0xa7, 0x06,
	0xbb, 0x4b, 0xc7, 0xb2, 0xbb, 0xde, 0xf1, 0xd8, 0x04, 0xd4, 0x8d, 0x68, 0x3f, 0x92, 0xef, 0x69,
	0x2a, 0xb3, 0xdf, 0xc4, 0x9b, 0xdc, 0x17, 0xdd, 0xb4, 0xe1, 0xa4, 0x72, 0xca, 0x4f, 0xaa, 0x0a,
	0x3f, 0x51, 0xad, 0x33, 0x0b, 0xa1, 0xd9, 0x83, 0xe6, 0x8c, 0xce, 0x5e, 0xd3, 0xe0, 0xc8, 0x8f,
	0xe7, 0x11, 0x6f, 0x4f, 0xa6, 0xa3, 0x2e, 0xb1, 0xd3, 0x81, 0xef, 0xcf, 0x8e, 0xdc, 0x60, 0x6c,
	0xd5, 0xc5, 0xe9, 0x44, 0xc6, 0xe7, 0xcc, 0x35, 0x19, 0xc0, 0x53, 0x7e, 0x26, 0xbc, 0x16, 0xe4,
	0xf0, 0x7d, 0xb0, 0x96, 0x15, 0xa6, 0x0f, 0xba, 0xc9, 0x30, 0x90, 0xc0, 0x3f, 0x87, 0x0e, 0xf1,
	0x0b, 0xee, 0x29, 0xcf, 0xc6, 0x60, 0xfe, 0xbd, 0x7f, 0x95, 0xfc, 0x7c, 0xa3, 0x10, 0x08, 0x71,
	0x46, 0xde, 0x77, 0x1b, 0x6a, 0x62, 0x93, 0x7c, 0x31, 0x52, 0xfe, 0x20, 0x97, 0x33, 0x83, 0xf4,
	0x95, 0x06, 0xfd, 0xad, 0x01, 0x64, 0xab, 0x68, 0x0b, 0xf4, 0x94, 0xbd, 0xe8, 0xde, 0x38, 0xcd,
	0x96, 0x9e, 0x67, 0x93, 0xde, 0x6c, 0x32, 0x0c, 0xa6, 0x32, 0xb7, 0x52, 0x5a, 0x59, 0x77, 0x5d,
	0xa8, 0xfd, 0xe0, 0x7b, 0xf3, 0x7e, 0xc4, 0x73, 0xdb, 0x70, 0xa4, 0x94, 0xf3, 0xb9, 0x56, 0x48,
	0x40, 0x17, 0x6a, 0x01, 0x9d, 0xb9, 0xc1, 0x1b, 0x9e, 0xd1, 0x86, 0x23, 0x25, 0xf4, 0x29, 0x6c,
	0x45, 0x7e, 0xe4, 0x4e, 0x8f, 0xdd, 0x19, 0x15, 0x80, 0xd8, 0xe0, 0x27, 0x0b, 0xab, 0x08, 0xc3,
	0x8d, 0x45, 0x40, 0xb3, 0x5d, 0x0d, 0xbe, 0x2b, 0xb7, 0x86, 0x1f, 0x42, 0xb5, 0xd4, 0xe7, 0xcc,
	0x3f, 0x3d, 0xe7, 0x5f, 0x12, 0x0b, 0x23, 0x8b, 0x05, 0xfe, 0x59, 0x87, 0x46, 0xda, 0xe4, 0x96,
	0x34, 0x59, 0x50, 0x1f, 0xf9, 0xf3, 0x88, 0xce, 0x93, 0x12, 0x49, 0x44, 0xf4, 0x11, 0x68, 0xa2,
	0x34, 0xb6, 0x7a, 0x9b, 0x59, 0x97, 0x24, 0x17, 0x0b, 0x47, 0xcb, 0x97, 0x4f, 0xb5, 0x50, 0x3e,
	0x6a, 0xd9, 0x99, 0x85, 0xb2, 0xcb, 0x12, 0x50, 0xcb, 0x25, 0x80, 0x93, 0x8a, 0x7a, 0x81, 0xe6,
	0x9f, 0x80, 0x7e, 0xb1, 0x40, 0x9b, 0xd0, 0x18, 0x9e, 0x0d, 0xbe, 0x7e, 0xec, 0xbc, 0xec, 0x9f,
	0xb4, 0x2a, 0x68, 0x03, 0xaa, 0x4f, 0xcf, 0x07, 0x67, 0x2d, 0x8d, 0x7d, 0xbd, 0x18, 0x0e, 0x2e,
	0x5a, 0x3a, 0xfb, 0x7a, 0x36, 0x38, 0x7a, 0xd6, 0x32, 0x50, 0x03, 0xcc, 0xfe, 0xf3, 0xe7, 0x27,
	0xaf, 0x5a, 0x55, 0xb4, 0x05, 0xc0, 0x3f, 0xbf, 0xe5, 0x9b, 0x4c, 0xfc, 0x9b, 0x06, 0x35, 0xe1,
	0xc6, 0x87, 0xd0, 0x32, 0x7a, 0x7f, 0x99, 0xd0, 0x96, 0x51, 0x77, 0xc3, 0x88, 0x06, 0x2f, 0x69,
	0xf0, 0x96, 0x0d, 0x44, 0x87, 0xd0, 0x54, 0x66, 0x1f, 0xd4, 0x26, 0xcb, 0x03, 0x96, 0xdd, 0x21,
	0x25, 0xe3, 0x11, 0xae, 0xa0, 0xfb, 0x70, 0x43, 0x9d, 0x21, 0x50, 0xa7, 0x6c, 0x70, 0xb1, 0x77,
	0x48, 0xd9, 0xa0, 0x81, 0x2b, 0xe8, 0x01, 0x6c, 0xe6, 0xc6, 0x04, 0xb4, 0x43, 0xca, 0x06, 0x0c,
	0xbb, 0x4b, 0x4a, 0xa7, 0x09, 0x5c, 0x41, 0x03, 0x68, 0x15, 0x5b, 0x13, 0xb2, 0xc8, 0x8a, 0xf6,
	0x67, 0xdf, 0x22, 0xab, 0xfa, 0x18, 0xae, 0xa0, 0xbb, 0xd0, 0x48, 0xa7, 0x05, 0xb4, 0x4d, 0x8a,
	0x33, 0x88, 0x8d, 0xc8, 0xd2, 0x30, 0x21, 0x22, 0xa0, 0x72, 0x62, 0xd4, 0x21, 0x25, 0xbc, 0xdc,
	0xde, 0x21, 0x65, 0xc4, 0x19, 0x57, 0x58, 0xf0, 0x15, 0xea, 0x86, 0xda, 0x64, 0x99, 0x2a, 0xda,
	0x1d, 0x52, 0xc2, 0xee, 0x12, 0x83, 0x25, 0x51, 0xe5, 0x06, 0xe7, 0x79, 0x35, 0x37, 0xb8, 0xc0,
	0x63, 0x53, 0x83, 0x53, 0x12, 0x26, 0x0c, 0x2e, 0x52, 0x41, 0x61, 0xf0, 0x12, 0x53, 0x4b, 0x8f,
	0xa7, 0x54, 0x48, 0x1c, 0x2f, 0x12, 0x32, 0x71, 0x7c, 0x89, 0x2f, 0xe1, 0x0a, 0xfa, 0x02, 0x36,
	0x12, 0xe6, 0x81, 0x5a, 0xa4, 0xc0, 0x88, 0xec, 0x6d, 0x52, 0xa4, 0x25, 0x05, 0x90, 0xb0, 0xa7,
	0x40, 0x05, 0x89, 0xf2, 0x9c, 0xa8, 0x20, 0x51, 0x5f, 0x0c, 0x5c, 0xe9, 0xfd, 0x6e, 0xc0, 0x76,
	0xd6, 0xef, 0x13, 0xdc, 0x5f, 0x1f, 0x7c, 0x4f, 0xe0, 0x66, 0x61, 0xbe, 0x43, 0xbb, 0xa4, 0x7c,
	0x84, 0xb4, 0x2d, 0xb2, 0x62, 0x14, 0xfc, 0x6f, 0x41, 0x7c, 0x4d, 0x38, 0x26, 0x1e, 0x65, 0x0c,
	0x2c, 0xf1, 0x68, 0x89, 0xdb, 0x25, 0x1e, 0x2d, 0x93, 0x35, 0xa1, 0xa7, 0xc0, 0xae, 0xd0, 0x2e,
	0x29, 0xa7, 0x69, 0xb6, 0x45, 0x56, 0x10, 0x31, 0x5c, 0x79, 0x5d, 0xe3, 0xff, 0xf5, 0xb9, 0xf3,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x38, 0x76, 0x89, 0x0c, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CircleMasterServiceClient is the client API for CircleMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CircleMasterServiceClient interface {
	// 创建
	BuildCircle(ctx context.Context, in *BuildCircleRequest, opts ...grpc.CallOption) (*BuildCircleResponse, error)
	// 更新
	UpdateCircle(ctx context.Context, in *UpdateCircleRequest, opts ...grpc.CallOption) (*UpdateCircleResponse, error)
	// 获取圈子列表
	GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error)
	// 获取成员列表
	GetCircleMembers(ctx context.Context, in *GetCircleMembersRequest, opts ...grpc.CallOption) (*GetCircleMembersResponse, error)
	// 删除圈子
	DelCircle(ctx context.Context, in *DelCircleRequest, opts ...grpc.CallOption) (*DelCircleResponse, error)
	// 获取圈子的日志
	GetCircleLog(ctx context.Context, in *GetCircleLogRequest, opts ...grpc.CallOption) (*GetCircleLogResponse, error)
	// 处理圈子消息
	DealMessage(ctx context.Context, in *DealMessageRequest, opts ...grpc.CallOption) (*DealMessageResponse, error)
	// 处理申请
	DealApply(ctx context.Context, in *DealApplyRequest, opts ...grpc.CallOption) (*DealApplyResponse, error)
	// 获取加入圈子申请
	GetApplyList(ctx context.Context, in *GetApplyListRequest, opts ...grpc.CallOption) (*GetApplyListResponse, error)
	// 获取退出圈子申请
	GetQuiteList(ctx context.Context, in *GetQuiteListRequest, opts ...grpc.CallOption) (*GetQuiteListResponse, error)
	// 处理用户退出申请
	DealQuit(ctx context.Context, in *DealQuitRequest, opts ...grpc.CallOption) (*DealQuitResponse, error)
	// 详细信息
	GetCircleInfo(ctx context.Context, in *GetCircleInfoRequest, opts ...grpc.CallOption) (*GetCircleInfoResponse, error)
}

type circleMasterServiceClient struct {
	cc *grpc.ClientConn
}

func NewCircleMasterServiceClient(cc *grpc.ClientConn) CircleMasterServiceClient {
	return &circleMasterServiceClient{cc}
}

func (c *circleMasterServiceClient) BuildCircle(ctx context.Context, in *BuildCircleRequest, opts ...grpc.CallOption) (*BuildCircleResponse, error) {
	out := new(BuildCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/BuildCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) UpdateCircle(ctx context.Context, in *UpdateCircleRequest, opts ...grpc.CallOption) (*UpdateCircleResponse, error) {
	out := new(UpdateCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/UpdateCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error) {
	out := new(GetCircleListResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetCircleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetCircleMembers(ctx context.Context, in *GetCircleMembersRequest, opts ...grpc.CallOption) (*GetCircleMembersResponse, error) {
	out := new(GetCircleMembersResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetCircleMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DelCircle(ctx context.Context, in *DelCircleRequest, opts ...grpc.CallOption) (*DelCircleResponse, error) {
	out := new(DelCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DelCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetCircleLog(ctx context.Context, in *GetCircleLogRequest, opts ...grpc.CallOption) (*GetCircleLogResponse, error) {
	out := new(GetCircleLogResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetCircleLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DealMessage(ctx context.Context, in *DealMessageRequest, opts ...grpc.CallOption) (*DealMessageResponse, error) {
	out := new(DealMessageResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DealMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DealApply(ctx context.Context, in *DealApplyRequest, opts ...grpc.CallOption) (*DealApplyResponse, error) {
	out := new(DealApplyResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DealApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetApplyList(ctx context.Context, in *GetApplyListRequest, opts ...grpc.CallOption) (*GetApplyListResponse, error) {
	out := new(GetApplyListResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetApplyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetQuiteList(ctx context.Context, in *GetQuiteListRequest, opts ...grpc.CallOption) (*GetQuiteListResponse, error) {
	out := new(GetQuiteListResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetQuiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) DealQuit(ctx context.Context, in *DealQuitRequest, opts ...grpc.CallOption) (*DealQuitResponse, error) {
	out := new(DealQuitResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/DealQuit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleMasterServiceClient) GetCircleInfo(ctx context.Context, in *GetCircleInfoRequest, opts ...grpc.CallOption) (*GetCircleInfoResponse, error) {
	out := new(GetCircleInfoResponse)
	err := c.cc.Invoke(ctx, "/CircleMasterService/GetCircleInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CircleMasterServiceServer is the server API for CircleMasterService service.
type CircleMasterServiceServer interface {
	// 创建
	BuildCircle(context.Context, *BuildCircleRequest) (*BuildCircleResponse, error)
	// 更新
	UpdateCircle(context.Context, *UpdateCircleRequest) (*UpdateCircleResponse, error)
	// 获取圈子列表
	GetCircleList(context.Context, *GetCircleListRequest) (*GetCircleListResponse, error)
	// 获取成员列表
	GetCircleMembers(context.Context, *GetCircleMembersRequest) (*GetCircleMembersResponse, error)
	// 删除圈子
	DelCircle(context.Context, *DelCircleRequest) (*DelCircleResponse, error)
	// 获取圈子的日志
	GetCircleLog(context.Context, *GetCircleLogRequest) (*GetCircleLogResponse, error)
	// 处理圈子消息
	DealMessage(context.Context, *DealMessageRequest) (*DealMessageResponse, error)
	// 处理申请
	DealApply(context.Context, *DealApplyRequest) (*DealApplyResponse, error)
	// 获取加入圈子申请
	GetApplyList(context.Context, *GetApplyListRequest) (*GetApplyListResponse, error)
	// 获取退出圈子申请
	GetQuiteList(context.Context, *GetQuiteListRequest) (*GetQuiteListResponse, error)
	// 处理用户退出申请
	DealQuit(context.Context, *DealQuitRequest) (*DealQuitResponse, error)
	// 详细信息
	GetCircleInfo(context.Context, *GetCircleInfoRequest) (*GetCircleInfoResponse, error)
}

func RegisterCircleMasterServiceServer(s *grpc.Server, srv CircleMasterServiceServer) {
	s.RegisterService(&_CircleMasterService_serviceDesc, srv)
}

func _CircleMasterService_BuildCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).BuildCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/BuildCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).BuildCircle(ctx, req.(*BuildCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_UpdateCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).UpdateCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/UpdateCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).UpdateCircle(ctx, req.(*UpdateCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetCircleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetCircleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetCircleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetCircleList(ctx, req.(*GetCircleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetCircleMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetCircleMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetCircleMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetCircleMembers(ctx, req.(*GetCircleMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DelCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DelCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DelCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DelCircle(ctx, req.(*DelCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetCircleLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetCircleLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetCircleLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetCircleLog(ctx, req.(*GetCircleLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DealMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DealMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DealMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DealMessage(ctx, req.(*DealMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DealApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DealApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DealApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DealApply(ctx, req.(*DealApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetApplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetApplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetApplyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetApplyList(ctx, req.(*GetApplyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetQuiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetQuiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetQuiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetQuiteList(ctx, req.(*GetQuiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_DealQuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealQuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).DealQuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/DealQuit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).DealQuit(ctx, req.(*DealQuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleMasterService_GetCircleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleMasterServiceServer).GetCircleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleMasterService/GetCircleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleMasterServiceServer).GetCircleInfo(ctx, req.(*GetCircleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CircleMasterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CircleMasterService",
	HandlerType: (*CircleMasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildCircle",
			Handler:    _CircleMasterService_BuildCircle_Handler,
		},
		{
			MethodName: "UpdateCircle",
			Handler:    _CircleMasterService_UpdateCircle_Handler,
		},
		{
			MethodName: "GetCircleList",
			Handler:    _CircleMasterService_GetCircleList_Handler,
		},
		{
			MethodName: "GetCircleMembers",
			Handler:    _CircleMasterService_GetCircleMembers_Handler,
		},
		{
			MethodName: "DelCircle",
			Handler:    _CircleMasterService_DelCircle_Handler,
		},
		{
			MethodName: "GetCircleLog",
			Handler:    _CircleMasterService_GetCircleLog_Handler,
		},
		{
			MethodName: "DealMessage",
			Handler:    _CircleMasterService_DealMessage_Handler,
		},
		{
			MethodName: "DealApply",
			Handler:    _CircleMasterService_DealApply_Handler,
		},
		{
			MethodName: "GetApplyList",
			Handler:    _CircleMasterService_GetApplyList_Handler,
		},
		{
			MethodName: "GetQuiteList",
			Handler:    _CircleMasterService_GetQuiteList_Handler,
		},
		{
			MethodName: "DealQuit",
			Handler:    _CircleMasterService_DealQuit_Handler,
		},
		{
			MethodName: "GetCircleInfo",
			Handler:    _CircleMasterService_GetCircleInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "circle/circle.proto",
}

// CircleUserServiceClient is the client API for CircleUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CircleUserServiceClient interface {
	// 获取圈子列表
	GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error)
	// 申请加入圈子
	ApplyJoinCircle(ctx context.Context, in *ApplyJoinCircleRequest, opts ...grpc.CallOption) (*ApplyJoinCircleResponse, error)
	// 获取成员列表
	GetCircleMembers(ctx context.Context, in *GetCircleMembersRequest, opts ...grpc.CallOption) (*GetCircleMembersResponse, error)
	// 获取圈子的日志
	GetCircleLog(ctx context.Context, in *GetCircleLogRequest, opts ...grpc.CallOption) (*GetCircleLogResponse, error)
	// 玩家申请离开圈子
	ApplyQuitCircle(ctx context.Context, in *ApplyQuitCircleRequest, opts ...grpc.CallOption) (*ApplyQuitCircleResponse, error)
	// 获取圈子详细信息
	GerCircleDetail(ctx context.Context, in *GerCircleDetailRequest, opts ...grpc.CallOption) (*GerCircleDetailResponse, error)
}

type circleUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewCircleUserServiceClient(cc *grpc.ClientConn) CircleUserServiceClient {
	return &circleUserServiceClient{cc}
}

func (c *circleUserServiceClient) GetCircleList(ctx context.Context, in *GetCircleListRequest, opts ...grpc.CallOption) (*GetCircleListResponse, error) {
	out := new(GetCircleListResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/GetCircleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) ApplyJoinCircle(ctx context.Context, in *ApplyJoinCircleRequest, opts ...grpc.CallOption) (*ApplyJoinCircleResponse, error) {
	out := new(ApplyJoinCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/ApplyJoinCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) GetCircleMembers(ctx context.Context, in *GetCircleMembersRequest, opts ...grpc.CallOption) (*GetCircleMembersResponse, error) {
	out := new(GetCircleMembersResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/GetCircleMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) GetCircleLog(ctx context.Context, in *GetCircleLogRequest, opts ...grpc.CallOption) (*GetCircleLogResponse, error) {
	out := new(GetCircleLogResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/GetCircleLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) ApplyQuitCircle(ctx context.Context, in *ApplyQuitCircleRequest, opts ...grpc.CallOption) (*ApplyQuitCircleResponse, error) {
	out := new(ApplyQuitCircleResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/ApplyQuitCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleUserServiceClient) GerCircleDetail(ctx context.Context, in *GerCircleDetailRequest, opts ...grpc.CallOption) (*GerCircleDetailResponse, error) {
	out := new(GerCircleDetailResponse)
	err := c.cc.Invoke(ctx, "/CircleUserService/GerCircleDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CircleUserServiceServer is the server API for CircleUserService service.
type CircleUserServiceServer interface {
	// 获取圈子列表
	GetCircleList(context.Context, *GetCircleListRequest) (*GetCircleListResponse, error)
	// 申请加入圈子
	ApplyJoinCircle(context.Context, *ApplyJoinCircleRequest) (*ApplyJoinCircleResponse, error)
	// 获取成员列表
	GetCircleMembers(context.Context, *GetCircleMembersRequest) (*GetCircleMembersResponse, error)
	// 获取圈子的日志
	GetCircleLog(context.Context, *GetCircleLogRequest) (*GetCircleLogResponse, error)
	// 玩家申请离开圈子
	ApplyQuitCircle(context.Context, *ApplyQuitCircleRequest) (*ApplyQuitCircleResponse, error)
	// 获取圈子详细信息
	GerCircleDetail(context.Context, *GerCircleDetailRequest) (*GerCircleDetailResponse, error)
}

func RegisterCircleUserServiceServer(s *grpc.Server, srv CircleUserServiceServer) {
	s.RegisterService(&_CircleUserService_serviceDesc, srv)
}

func _CircleUserService_GetCircleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).GetCircleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/GetCircleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).GetCircleList(ctx, req.(*GetCircleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_ApplyJoinCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyJoinCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).ApplyJoinCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/ApplyJoinCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).ApplyJoinCircle(ctx, req.(*ApplyJoinCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_GetCircleMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).GetCircleMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/GetCircleMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).GetCircleMembers(ctx, req.(*GetCircleMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_GetCircleLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircleLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).GetCircleLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/GetCircleLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).GetCircleLog(ctx, req.(*GetCircleLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_ApplyQuitCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyQuitCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).ApplyQuitCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/ApplyQuitCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).ApplyQuitCircle(ctx, req.(*ApplyQuitCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleUserService_GerCircleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GerCircleDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleUserServiceServer).GerCircleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CircleUserService/GerCircleDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleUserServiceServer).GerCircleDetail(ctx, req.(*GerCircleDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CircleUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CircleUserService",
	HandlerType: (*CircleUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCircleList",
			Handler:    _CircleUserService_GetCircleList_Handler,
		},
		{
			MethodName: "ApplyJoinCircle",
			Handler:    _CircleUserService_ApplyJoinCircle_Handler,
		},
		{
			MethodName: "GetCircleMembers",
			Handler:    _CircleUserService_GetCircleMembers_Handler,
		},
		{
			MethodName: "GetCircleLog",
			Handler:    _CircleUserService_GetCircleLog_Handler,
		},
		{
			MethodName: "ApplyQuitCircle",
			Handler:    _CircleUserService_ApplyQuitCircle_Handler,
		},
		{
			MethodName: "GerCircleDetail",
			Handler:    _CircleUserService_GerCircleDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "circle/circle.proto",
}
