// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 本地登录认证请求
type AuthLocalRequest struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImgUrl           string   `protobuf:"bytes,4,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	Gender               int32    `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	IsBot                bool     `protobuf:"varint,6,opt,name=isBot,proto3" json:"isBot,omitempty"`
	InviteUserId         int32    `protobuf:"varint,7,opt,name=inviteUserId,proto3" json:"inviteUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLocalRequest) Reset()         { *m = AuthLocalRequest{} }
func (m *AuthLocalRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLocalRequest) ProtoMessage()    {}
func (*AuthLocalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *AuthLocalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLocalRequest.Unmarshal(m, b)
}
func (m *AuthLocalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLocalRequest.Marshal(b, m, deterministic)
}
func (m *AuthLocalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLocalRequest.Merge(m, src)
}
func (m *AuthLocalRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLocalRequest.Size(m)
}
func (m *AuthLocalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLocalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLocalRequest proto.InternalMessageInfo

func (m *AuthLocalRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *AuthLocalRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthLocalRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *AuthLocalRequest) GetHeadImgUrl() string {
	if m != nil {
		return m.HeadImgUrl
	}
	return ""
}

func (m *AuthLocalRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *AuthLocalRequest) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func (m *AuthLocalRequest) GetInviteUserId() int32 {
	if m != nil {
		return m.InviteUserId
	}
	return 0
}

// 微信h5登录认证请求
type AuthWxH5Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthWxH5Request) Reset()         { *m = AuthWxH5Request{} }
func (m *AuthWxH5Request) String() string { return proto.CompactTextString(m) }
func (*AuthWxH5Request) ProtoMessage()    {}
func (*AuthWxH5Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *AuthWxH5Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthWxH5Request.Unmarshal(m, b)
}
func (m *AuthWxH5Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthWxH5Request.Marshal(b, m, deterministic)
}
func (m *AuthWxH5Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthWxH5Request.Merge(m, src)
}
func (m *AuthWxH5Request) XXX_Size() int {
	return xxx_messageInfo_AuthWxH5Request.Size(m)
}
func (m *AuthWxH5Request) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthWxH5Request.DiscardUnknown(m)
}

var xxx_messageInfo_AuthWxH5Request proto.InternalMessageInfo

// token信息
type PayloadToken struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpireAt             int32    `protobuf:"varint,3,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsNew                bool     `protobuf:"varint,5,opt,name=isNew,proto3" json:"isNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadToken) Reset()         { *m = PayloadToken{} }
func (m *PayloadToken) String() string { return proto.CompactTextString(m) }
func (*PayloadToken) ProtoMessage()    {}
func (*PayloadToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *PayloadToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadToken.Unmarshal(m, b)
}
func (m *PayloadToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadToken.Marshal(b, m, deterministic)
}
func (m *PayloadToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadToken.Merge(m, src)
}
func (m *PayloadToken) XXX_Size() int {
	return xxx_messageInfo_PayloadToken.Size(m)
}
func (m *PayloadToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadToken.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadToken proto.InternalMessageInfo

func (m *PayloadToken) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PayloadToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PayloadToken) GetExpireAt() int32 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func (m *PayloadToken) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *PayloadToken) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

// token验证请求
type SignInGameRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInGameRequest) Reset()         { *m = SignInGameRequest{} }
func (m *SignInGameRequest) String() string { return proto.CompactTextString(m) }
func (*SignInGameRequest) ProtoMessage()    {}
func (*SignInGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SignInGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInGameRequest.Unmarshal(m, b)
}
func (m *SignInGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInGameRequest.Marshal(b, m, deterministic)
}
func (m *SignInGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInGameRequest.Merge(m, src)
}
func (m *SignInGameRequest) XXX_Size() int {
	return xxx_messageInfo_SignInGameRequest.Size(m)
}
func (m *SignInGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInGameRequest proto.InternalMessageInfo

func (m *SignInGameRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 验证token请求
type VerifyTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

func (m *VerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResponse) Reset()         { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()    {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *VerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResponse.Unmarshal(m, b)
}
func (m *VerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResponse.Merge(m, src)
}
func (m *VerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResponse.Size(m)
}
func (m *VerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResponse proto.InternalMessageInfo

// 获取用户详细信息
type GetDetailInfoRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailInfoRequest) Reset()         { *m = GetDetailInfoRequest{} }
func (m *GetDetailInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetDetailInfoRequest) ProtoMessage()    {}
func (*GetDetailInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetDetailInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailInfoRequest.Unmarshal(m, b)
}
func (m *GetDetailInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetDetailInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailInfoRequest.Merge(m, src)
}
func (m *GetDetailInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetDetailInfoRequest.Size(m)
}
func (m *GetDetailInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailInfoRequest proto.InternalMessageInfo

func (m *GetDetailInfoRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 获取所有用户信息
type GetAllUserRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserRequest) Reset()         { *m = GetAllUserRequest{} }
func (m *GetAllUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllUserRequest) ProtoMessage()    {}
func (*GetAllUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *GetAllUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserRequest.Unmarshal(m, b)
}
func (m *GetAllUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserRequest.Marshal(b, m, deterministic)
}
func (m *GetAllUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserRequest.Merge(m, src)
}
func (m *GetAllUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllUserRequest.Size(m)
}
func (m *GetAllUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserRequest proto.InternalMessageInfo

func (m *GetAllUserRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetAllUserRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAllUserRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

// 获取所有用户信息响应
type GetAllUserResponse struct {
	List                 []*UserInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllUserResponse) Reset()         { *m = GetAllUserResponse{} }
func (m *GetAllUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllUserResponse) ProtoMessage()    {}
func (*GetAllUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetAllUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserResponse.Unmarshal(m, b)
}
func (m *GetAllUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserResponse.Marshal(b, m, deterministic)
}
func (m *GetAllUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserResponse.Merge(m, src)
}
func (m *GetAllUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllUserResponse.Size(m)
}
func (m *GetAllUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserResponse proto.InternalMessageInfo

func (m *GetAllUserResponse) GetList() []*UserInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// 增加物品请求
type AddItemsRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemsRequest) Reset()         { *m = AddItemsRequest{} }
func (m *AddItemsRequest) String() string { return proto.CompactTextString(m) }
func (*AddItemsRequest) ProtoMessage()    {}
func (*AddItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *AddItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemsRequest.Unmarshal(m, b)
}
func (m *AddItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemsRequest.Marshal(b, m, deterministic)
}
func (m *AddItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemsRequest.Merge(m, src)
}
func (m *AddItemsRequest) XXX_Size() int {
	return xxx_messageInfo_AddItemsRequest.Size(m)
}
func (m *AddItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemsRequest proto.InternalMessageInfo

func (m *AddItemsRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddItemsRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// 用户更新内容
type UserUpdate struct {
	GetItems             []*Item   `protobuf:"bytes,1,rep,name=getItems,proto3" json:"getItems,omitempty"`
	UserUpdate           *UserInfo `protobuf:"bytes,2,opt,name=userUpdate,proto3" json:"userUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserUpdate) Reset()         { *m = UserUpdate{} }
func (m *UserUpdate) String() string { return proto.CompactTextString(m) }
func (*UserUpdate) ProtoMessage()    {}
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UserUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdate.Unmarshal(m, b)
}
func (m *UserUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdate.Marshal(b, m, deterministic)
}
func (m *UserUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdate.Merge(m, src)
}
func (m *UserUpdate) XXX_Size() int {
	return xxx_messageInfo_UserUpdate.Size(m)
}
func (m *UserUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdate proto.InternalMessageInfo

func (m *UserUpdate) GetGetItems() []*Item {
	if m != nil {
		return m.GetItems
	}
	return nil
}

func (m *UserUpdate) GetUserUpdate() *UserInfo {
	if m != nil {
		return m.UserUpdate
	}
	return nil
}

// 物品
type Item struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 用户信息
type UserInfo struct {
	UserId               int32            `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName             string           `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImgUrl           string           `protobuf:"bytes,3,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	AccountType          int32            `protobuf:"varint,4,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Gender               int32            `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Diamond              int32            `protobuf:"varint,6,opt,name=diamond,proto3" json:"diamond,omitempty"`
	Gold                 int32            `protobuf:"varint,7,opt,name=gold,proto3" json:"gold,omitempty"`
	RoomCard             int32            `protobuf:"varint,8,opt,name=roomCard,proto3" json:"roomCard,omitempty"`
	Vip                  int32            `protobuf:"varint,9,opt,name=vip,proto3" json:"vip,omitempty"`
	VipExpc              int32            `protobuf:"varint,10,opt,name=vipExpc,proto3" json:"vipExpc,omitempty"`
	Lvl                  int32            `protobuf:"varint,11,opt,name=lvl,proto3" json:"lvl,omitempty"`
	LvlExpc              int32            `protobuf:"varint,12,opt,name=lvlExpc,proto3" json:"lvlExpc,omitempty"`
	Bag                  map[string]int32 `protobuf:"bytes,13,rep,name=bag,proto3" json:"bag,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfo) GetHeadImgUrl() string {
	if m != nil {
		return m.HeadImgUrl
	}
	return ""
}

func (m *UserInfo) GetAccountType() int32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *UserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *UserInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *UserInfo) GetRoomCard() int32 {
	if m != nil {
		return m.RoomCard
	}
	return 0
}

func (m *UserInfo) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *UserInfo) GetVipExpc() int32 {
	if m != nil {
		return m.VipExpc
	}
	return 0
}

func (m *UserInfo) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *UserInfo) GetLvlExpc() int32 {
	if m != nil {
		return m.LvlExpc
	}
	return 0
}

func (m *UserInfo) GetBag() map[string]int32 {
	if m != nil {
		return m.Bag
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthLocalRequest)(nil), "AuthLocalRequest")
	proto.RegisterType((*AuthWxH5Request)(nil), "AuthWxH5Request")
	proto.RegisterType((*PayloadToken)(nil), "PayloadToken")
	proto.RegisterType((*SignInGameRequest)(nil), "SignInGameRequest")
	proto.RegisterType((*VerifyTokenRequest)(nil), "VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "VerifyTokenResponse")
	proto.RegisterType((*GetDetailInfoRequest)(nil), "GetDetailInfoRequest")
	proto.RegisterType((*GetAllUserRequest)(nil), "GetAllUserRequest")
	proto.RegisterType((*GetAllUserResponse)(nil), "GetAllUserResponse")
	proto.RegisterType((*AddItemsRequest)(nil), "AddItemsRequest")
	proto.RegisterType((*UserUpdate)(nil), "UserUpdate")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterMapType((map[string]int32)(nil), "UserInfo.BagEntry")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdb, 0x6e, 0xf3, 0x44,
	0x10, 0x8e, 0x93, 0x38, 0x75, 0x26, 0x29, 0x6d, 0xa6, 0x07, 0x59, 0x41, 0xa0, 0xb0, 0xe2, 0x22,
	0x05, 0x61, 0xa4, 0x04, 0x0a, 0xe2, 0x2e, 0x81, 0x52, 0x22, 0x50, 0x05, 0xa6, 0x05, 0xa9, 0x77,
	0xdb, 0x78, 0xeb, 0xae, 0xba, 0xb1, 0x5d, 0x7b, 0x93, 0x36, 0x7d, 0x12, 0x9e, 0x8a, 0x47, 0xe0,
	0x59, 0xd0, 0xee, 0xda, 0x89, 0xd3, 0xb4, 0xfd, 0xef, 0xfc, 0xcd, 0xcc, 0xce, 0xf9, 0x1b, 0x03,
	0xcc, 0x33, 0x96, 0x7a, 0x49, 0x1a, 0xcb, 0x98, 0xfc, 0x67, 0xc1, 0xfe, 0x68, 0x2e, 0xef, 0x7e,
	0x8b, 0xa7, 0x54, 0xf8, 0xec, 0x61, 0xce, 0x32, 0x89, 0x3d, 0x68, 0xd1, 0xe9, 0x34, 0x9e, 0x47,
	0xf2, 0x82, 0xce, 0x98, 0x6b, 0xf5, 0xac, 0x7e, 0xd3, 0x2f, 0x8b, 0xb0, 0x0b, 0x4e, 0x42, 0xb3,
	0xec, 0x31, 0x4e, 0x03, 0xb7, 0xaa, 0xd5, 0x2b, 0xac, 0x74, 0x11, 0x9f, 0xde, 0xeb, 0xa7, 0x35,
	0xa3, 0x2b, 0x30, 0x7e, 0x0a, 0x70, 0xc7, 0x68, 0x30, 0x99, 0x85, 0x57, 0xa9, 0x70, 0xeb, 0x5a,
	0x5b, 0x92, 0xe0, 0x31, 0x34, 0x42, 0x16, 0x05, 0x2c, 0x75, 0xed, 0x9e, 0xd5, 0xb7, 0xfd, 0x1c,
	0xe1, 0x21, 0xd8, 0x3c, 0x1b, 0xc7, 0xd2, 0x6d, 0xf4, 0xac, 0xbe, 0xe3, 0x1b, 0x80, 0x04, 0xda,
	0x3c, 0x5a, 0x70, 0xc9, 0xae, 0x32, 0x96, 0x4e, 0x02, 0x77, 0x47, 0xbf, 0xd9, 0x90, 0x91, 0x0e,
	0xec, 0xa9, 0xfa, 0xfe, 0x7e, 0xfa, 0xe5, 0xdb, 0xbc, 0x3c, 0xf2, 0x0c, 0xed, 0xdf, 0xe9, 0x52,
	0xc4, 0x34, 0xb8, 0x8c, 0xef, 0x59, 0x84, 0x1f, 0x41, 0x95, 0x07, 0xba, 0x4a, 0xdb, 0xaf, 0xf2,
	0x40, 0x05, 0x93, 0x4a, 0x91, 0x57, 0x66, 0x80, 0x2a, 0x8b, 0x3d, 0x25, 0x3c, 0x65, 0x23, 0xa9,
	0xcb, 0xb2, 0xfd, 0x15, 0x46, 0x84, 0x7a, 0x1a, 0x0b, 0x96, 0x17, 0xa4, 0xbf, 0x4d, 0xca, 0x17,
	0xec, 0x51, 0x57, 0xa2, 0x53, 0xbe, 0x60, 0x8f, 0xe4, 0x04, 0x3a, 0x7f, 0xf2, 0x30, 0x9a, 0x44,
	0xe7, 0x74, 0xc6, 0x8a, 0x7e, 0xaf, 0x02, 0x5a, 0xa5, 0x80, 0xe4, 0x0b, 0xc0, 0xbf, 0x58, 0xca,
	0x6f, 0x97, 0x3a, 0xcb, 0xf7, 0x6d, 0x8f, 0xe0, 0x60, 0xc3, 0x36, 0x4b, 0xe2, 0x28, 0x63, 0xc4,
	0x83, 0xc3, 0x73, 0x26, 0x7f, 0x62, 0x92, 0x72, 0x31, 0x89, 0x6e, 0xe3, 0xc2, 0xc9, 0x31, 0x34,
	0xe6, 0xa6, 0x65, 0xa6, 0xea, 0x1c, 0x91, 0x5f, 0xa1, 0x73, 0xce, 0xe4, 0x48, 0x08, 0xd5, 0xbc,
	0xc2, 0x18, 0xa1, 0x9e, 0xd0, 0x90, 0xe5, 0xa6, 0xfa, 0x5b, 0x65, 0x21, 0xf8, 0x8c, 0x4b, 0xdd,
	0x22, 0xdb, 0x37, 0x00, 0xdb, 0x60, 0x3d, 0xe4, 0x23, 0xb7, 0x1e, 0xc8, 0x10, 0xb0, 0xec, 0xcc,
	0xa4, 0x84, 0x9f, 0x40, 0x5d, 0xf0, 0x4c, 0xba, 0x56, 0xaf, 0xd6, 0x6f, 0x0d, 0x9a, 0x9e, 0x1e,
	0x93, 0x4a, 0x4d, 0x8b, 0xc9, 0xcf, 0xb0, 0x37, 0x0a, 0x82, 0x89, 0x64, 0xb3, 0xec, 0x03, 0xc9,
	0xe2, 0xc7, 0x60, 0x73, 0x65, 0xe7, 0x56, 0xb5, 0x2b, 0xdb, 0x53, 0xaf, 0x7c, 0x23, 0x23, 0xd7,
	0x00, 0xca, 0xf3, 0x55, 0x12, 0x50, 0xc9, 0xf0, 0x33, 0x70, 0x42, 0x26, 0xb5, 0xd7, 0x3c, 0x70,
	0x6e, 0xbd, 0x12, 0xe3, 0x89, 0xa1, 0x85, 0x79, 0xa0, 0xcb, 0xda, 0xc8, 0xae, 0xa4, 0x24, 0xdf,
	0x40, 0x5d, 0xbd, 0x51, 0x89, 0xa9, 0x60, 0xeb, 0xc4, 0x0c, 0x52, 0xcd, 0xd1, 0x4c, 0x29, 0x9a,
	0xa3, 0x01, 0xf9, 0xa7, 0x06, 0x4e, 0xe1, 0xee, 0xcd, 0x9a, 0xca, 0xdc, 0xa9, 0xbe, 0xcb, 0x9d,
	0xda, 0x16, 0x77, 0xd6, 0xac, 0xbd, 0x5c, 0x26, 0x66, 0x17, 0x6d, 0xbf, 0x2c, 0x7a, 0x93, 0x5d,
	0x2e, 0xec, 0x04, 0x9c, 0xce, 0xe2, 0x28, 0xd0, 0xfc, 0xb2, 0xfd, 0x02, 0xaa, 0xd9, 0x87, 0xb1,
	0x28, 0x98, 0xa5, 0xbf, 0x55, 0x8e, 0x69, 0x1c, 0xcf, 0x7e, 0xa4, 0x69, 0xe0, 0x3a, 0x86, 0x08,
	0x05, 0xc6, 0x7d, 0xa8, 0x2d, 0x78, 0xe2, 0x36, 0xb5, 0x58, 0x7d, 0x2a, 0xdf, 0x0b, 0x9e, 0x9c,
	0x3d, 0x25, 0x53, 0x17, 0x8c, 0xef, 0x1c, 0x2a, 0x5b, 0xb1, 0x10, 0x6e, 0xcb, 0xd8, 0x8a, 0x85,
	0x50, 0xb6, 0x62, 0x21, 0xb4, 0x6d, 0xdb, 0xd8, 0xe6, 0x10, 0x3f, 0x87, 0xda, 0x0d, 0x0d, 0xdd,
	0x5d, 0x3d, 0x3b, 0x5c, 0x8d, 0xc5, 0x1b, 0xd3, 0xf0, 0x2c, 0x92, 0xe9, 0xd2, 0x57, 0xea, 0xee,
	0x29, 0x38, 0x85, 0x40, 0x79, 0xbf, 0x67, 0xcb, 0x9c, 0x25, 0xea, 0x53, 0x8d, 0x65, 0x41, 0xc5,
	0x9c, 0x15, 0x63, 0xd1, 0xe0, 0x87, 0xea, 0xf7, 0xd6, 0x60, 0x09, 0x4d, 0xe5, 0xf1, 0x8f, 0x39,
	0x4b, 0x97, 0x38, 0x84, 0xdd, 0x0d, 0xce, 0xe0, 0x91, 0xf7, 0x1a, 0x87, 0xba, 0xeb, 0xe5, 0x20,
	0x15, 0xfc, 0x0e, 0x60, 0xbd, 0xeb, 0x88, 0xde, 0x16, 0x8b, 0xba, 0x07, 0xde, 0x36, 0x19, 0x48,
	0x65, 0x70, 0x0a, 0x3b, 0x4a, 0x32, 0xe6, 0xcf, 0xf8, 0x25, 0x38, 0xc5, 0xea, 0xe3, 0xbe, 0xf7,
	0x82, 0x05, 0xdd, 0x96, 0xb7, 0xde, 0x67, 0x52, 0x19, 0xfc, 0x6b, 0x99, 0x6d, 0x52, 0xb7, 0x0d,
	0xbf, 0x86, 0xe6, 0xea, 0x86, 0x63, 0xc7, 0x7b, 0x79, 0xcf, 0xbb, 0xbb, 0x5e, 0xf9, 0xde, 0x91,
	0x0a, 0x7e, 0x05, 0x4e, 0x71, 0x14, 0x55, 0xa8, 0xcd, 0xfb, 0xf8, 0x9a, 0x39, 0xac, 0x8f, 0x16,
	0xa2, 0xb7, 0x75, 0xc1, 0x36, 0x9b, 0x31, 0x84, 0x56, 0xe9, 0x18, 0xe1, 0x81, 0xb7, 0x7d, 0xc6,
	0xb6, 0x62, 0x8c, 0x1b, 0xd7, 0x75, 0xc5, 0x81, 0x9b, 0x86, 0xfe, 0x2f, 0x0d, 0xff, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x78, 0xbd, 0xc7, 0xa5, 0x06, 0x00, 0x00,
}
